In [43]:
import pandas as pd

In [44]:
plp_68 = pd.read_parquet("../../data/datasets/PLP_68_2024_preprocessado.parquet")
mpv_612 = pd.read_parquet("../../data/datasets/MPV_612_2013_preprocessado.parquet")
pec_6 = pd.read_parquet("../../data/datasets/PEC_6_2019_preprocessado.parquet")

In [72]:
plp_68_temas = pd.read_parquet("../../data/temas/PLP_68_2024.parquet")
mpv_612_temas = pd.read_parquet("../../data/temas/MPV_612_2013.parquet")
pec_6_temas = pd.read_parquet("../../data/temas/PEC_6_2019.parquet")

In [66]:
plp_68_textos_e_temas = plp_68.merge(
    plp_68_temas[['num_emenda', 'tema', 'tema_macro', 'tema_nivel_2']],
    on='num_emenda',
    how='inner'
)

In [68]:
pec_6_textos_e_temas = pec_6.merge(
    pec_6_temas[['num_emenda', 'tema']],
    on='num_emenda',
    how='inner'
)

In [73]:
mpv_612_textos_e_temas = mpv_612.merge(
    mpv_612_temas[['num_emenda', 'tema']],
    on='num_emenda',
    how='inner'
)

In [76]:
plp_68_textos_e_temas.head()

,num_emenda,materia,nome_arquivo,texto,cabecalho,texto_sem_cabecalho,texto_preprocessado,texto_preprocessado_sem_justificativa,tema,tema_macro,tema_nivel_2
0,1,PLP_68_2024,EMENDA_1-U_-_PLP_68_2024.txt,Gabinete do Senador Esperidião Amin\nEMENDA Nº...,Gabinete do Senador Esperidião Amin\nEMENDA Nº...,\nSuprimam-se os §§ 1° e 2° do art. 384 do PLP...,Suprimam-se os §§ 1° e 2° do art. 384 do PLP n...,Suprimam-se os §§ 1° e 2° do art. 384 do PLP n...,Transição - Compensação Benefícios ICMS,Transição,Transição
1,10,PLP_68_2024,EMENDA_10-U_-_PLP_68_2024.txt,Gabinete do Senador Mecias de Jesus\nEMENDA Nº...,Gabinete do Senador Mecias de Jesus\nEMENDA Nº...,\nInclua-se o §6º no art. 23 e dê-se a seguint...,Inclua-se o §6º no art. 23 e dê-se a seguinte ...,Inclua-se o §6º no art. 23 e dê-se a seguinte ...,IBS e CBS (Sujeição Passiva),IBS e CBS,IBS e CBS (Sujeição Passiva)
2,100,PLP_68_2024,EMENDA_100-U_-_PLP_68_2024.txt,Gabinete do Senador Fabiano Contarato\nEMENDA ...,Gabinete do Senador Fabiano Contarato\nEMENDA ...,\nAcrescenta o inciso VIII ao §1º do artigo 40...,Acrescenta o inciso VIII ao §1º do artigo 406 ...,Acrescenta o inciso VIII ao §1º do artigo 406 ...,Imposto Seletivo (Incidência) - inclusão armas...,Imposto Seletivo,Imposto Seletivo (Incidência)
3,1000,PLP_68_2024,EMENDA_1000-U_-_PLP_68_2024.txt,EMENDA Nº \n(ao PLP 68/2024)\nAcrescen...,EMENDA Nº \n(ao PLP 68/2024),\nAcrescente-se inciso VI ao parágrafo único d...,Acrescente-se inciso VI ao parágrafo único do ...,Acrescente-se inciso VI ao parágrafo único do ...,IBS e CBS (Fato Gerador),IBS e CBS,IBS e CBS (Fato Gerador)
4,1001,PLP_68_2024,EMENDA_1001-U_-_PLP_68_2024.txt,EMENDA Nº \n(ao PLP 68/2024)\nDê-se ao...,EMENDA Nº \n(ao PLP 68/2024),\nDê-se ao § 7º do art. 163 do Projeto a segui...,Dê-se ao § 7º do art. 163 do Projeto a seguint...,Dê-se ao § 7º do art. 163 do Projeto a seguint...,Produtor Rural - Compensação,Produtor Rural,Produtor Rural

In [77]:
pec_6_textos_e_temas.head()

,num_emenda,materia,nome_arquivo,texto,cabecalho,texto_sem_cabecalho,texto_preprocessado,texto_preprocessado_sem_justificativa,tema
0,100,PEC_6_2019,EMENDA_100_-_PEC_6_2019.txt,PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019...,PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019...,"Suprima-se os §§ 2º, 3º e 5º do art. 24 da PE...","Suprima-se os §§ 2º, 3º e 5º do art. 24 da PEC...","Suprima-se os §§ 2º, 3º e 5º do art. 24 da PEC...",ACUM BENEF
1,101,PEC_6_2019,EMENDA_101_-_PEC_6_2019.txt,PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019...,PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019...,Dê-se ao art. 34 da PEC 6/2019 a seguinte reda...,Dê-se ao art. 34 da PEC 6 a seguinte redação: ...,Dê-se ao art. 34 da PEC 6 a seguinte redação: ...,SERVIDOR
2,102,PEC_6_2019,EMENDA_102_-_PEC_6_2019.txt,PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019...,PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019...,"Suprimam-se os §§ § 6º, 7º, 8º e 9° do art. 8°...","Suprimam-se os §§ § 6º, 7º, 8º e 9° do art. 8°...","Suprimam-se os §§ § 6º, 7º, 8º e 9° do art. 8°...",ANISTIADOS
3,103,PEC_6_2019,EMENDA_103_-_PEC_6_2019.txt,\nSENADO FEDERAL \nGabinete do Senador Lasier...,SENADO FEDERAL \nGabinete do Senador Lasier Ma...,Acrescente-se os seguintes artigos à Proposta ...,Acrescente-se os seguintes artigos à Proposta ...,Acrescente-se os seguintes artigos à Proposta ...,ESTADOS E MUN
4,104,PEC_6_2019,EMENDA_104_-_PEC_6_2019.txt,\nGabinete do Senador Humberto Costa \n \n \n...,Gabinete do Senador Humberto Costa \n \n \n \n...,"Dê-se aos §§ 3º, 7º, 14 e 19 do artigo 40 da C...","Dê-se aos §§ 3º, 7º, 14 e 19 do artigo 40 da C...","Dê-se aos §§ 3º, 7º, 14 e 19 do artigo 40 da C...",SERVIDOR

In [78]:
mpv_612.head()

,num_emenda,materia,nome_arquivo,texto,texto_preprocessado,texto_preprocessado_sem_justificativa
0,100,MPV_612_2013,EMENDA_100_-_MPV_612_2013.txt,Subsecretaria de Apoio às Comissões Mistas\n\n...,"O Art, 23 da Medida Provisória n.º 612, de 04 ...","O Art, 23 da Medida Provisória n.º 612, de 04 ..."
1,101,MPV_612_2013,EMENDA_101_-_MPV_612_2013.txt,Mistas\n\nissões À\n\na2\n\nGigliola Ansiliero...,"O Art. 23 da Medida Provisória n.º 612, de 04 ...","O Art. 23 da Medida Provisória n.º 612, de 04 ..."
2,102,MPV_612_2013,EMENDA_102_-_MPV_612_2013.txt,Subsecretaria de Apoio às Comissões Mistas\nRe...,"Modifica as alíneas “a” e “b” do incido 1l, do...","Modifica as alíneas “a” e “b” do incido 1l, do..."
3,103,MPV_612_2013,EMENDA_103_-_MPV_612_2013.txt,SE\n\nMPV 612\n\nCONGRESSO NACIONAL 00103\n\nA...,"O artigo 25 da MPV 612, de 2013, que altera o ...","O artigo 25 da MPV 612, de 2013, que altera o ..."
4,104,MPV_612_2013,EMENDA_104_-_MPV_612_2013.txt,"Mista,\n\nàs 1) /\n\norais, Mat. 258286\n\n-)\...","Acrescente-se o inciso Ill, no Art. 26 da Medi...","Acrescente-se o inciso Ill, no Art. 26 da Medi..."

In [79]:
cols = ["num_emenda", "materia", "texto", "texto_preprocessado", "texto_preprocessado_sem_justificativa", "tema"]
cols_plp_68 = cols + ["tema_macro", "tema_nivel_2"]

In [81]:
df_completo = pd.concat([plp_68_textos_e_temas[cols_plp_68], mpv_612_textos_e_temas[cols], pec_6_textos_e_temas[cols]])

In [82]:
df_completo.head()

,num_emenda,materia,texto,texto_preprocessado,texto_preprocessado_sem_justificativa,tema,tema_macro,tema_nivel_2
0,1,PLP_68_2024,Gabinete do Senador Esperidião Amin\nEMENDA Nº...,Suprimam-se os §§ 1° e 2° do art. 384 do PLP n...,Suprimam-se os §§ 1° e 2° do art. 384 do PLP n...,Transição - Compensação Benefícios ICMS,Transição,Transição
1,10,PLP_68_2024,Gabinete do Senador Mecias de Jesus\nEMENDA Nº...,Inclua-se o §6º no art. 23 e dê-se a seguinte ...,Inclua-se o §6º no art. 23 e dê-se a seguinte ...,IBS e CBS (Sujeição Passiva),IBS e CBS,IBS e CBS (Sujeição Passiva)
2,100,PLP_68_2024,Gabinete do Senador Fabiano Contarato\nEMENDA ...,Acrescenta o inciso VIII ao §1º do artigo 406 ...,Acrescenta o inciso VIII ao §1º do artigo 406 ...,Imposto Seletivo (Incidência) - inclusão armas...,Imposto Seletivo,Imposto Seletivo (Incidência)
3,1000,PLP_68_2024,EMENDA Nº \n(ao PLP 68/2024)\nAcrescen...,Acrescente-se inciso VI ao parágrafo único do ...,Acrescente-se inciso VI ao parágrafo único do ...,IBS e CBS (Fato Gerador),IBS e CBS,IBS e CBS (Fato Gerador)
4,1001,PLP_68_2024,EMENDA Nº \n(ao PLP 68/2024)\nDê-se ao...,Dê-se ao § 7º do art. 163 do Projeto a seguint...,Dê-se ao § 7º do art. 163 do Projeto a seguint...,Produtor Rural - Compensação,Produtor Rural,Produtor Rural

In [89]:
df_completo.describe()

        num_emenda
count  2462.000000
mean    826.229894
std     623.789648
min       1.000000
25%     207.250000
50%     751.500000
75%    1376.750000
max    1997.000000

In [84]:
df_completo.to_parquet("../../data/datasets/df_completo.parquet", index=False)

In [85]:
df_completo[df_completo.texto == df_completo.texto_preprocessado]

Empty DataFrame
Columns: [num_emenda, materia, texto, texto_preprocessado, texto_preprocessado_sem_justificativa, tema, tema_macro, tema_nivel_2]
Index: []

In [86]:
df_completo[df_completo.texto_preprocessado == df_completo.texto_preprocessado_sem_justificativa]

Empty DataFrame
Columns: [num_emenda, materia, texto, texto_preprocessado, texto_preprocessado_sem_justificativa, tema, tema_macro, tema_nivel_2]
Index: []

In [87]:
df_completo[df_completo.texto == df_completo.texto_preprocessado_sem_justificativa]

Empty DataFrame
Columns: [num_emenda, materia, texto, texto_preprocessado, texto_preprocessado_sem_justificativa, tema, tema_macro, tema_nivel_2]
Index: []