In [1]:
import re
import pandas as pd
from tqdm import tqdm

tqdm.pandas()

In [2]:
plp = pd.read_parquet("../data/datasets/PLP_68_2024_textos_emendas.parquet")
plp = plp[plp.num_emenda <= 1998]

In [3]:


def extract_until_any(text, stop_words):
    lower_text = text.lower()
    matches = []

    for word in stop_words:
        idx = lower_text.find(word.lower())
        if idx != -1:
            matches.append(idx)

    if not matches:
        print('---->', text)
        return text

    first_stop = min(matches)
    return text[:first_stop]


def remove_random_chars(text):
    pattern = r"[`´\^¨~]"
    return re.sub(pattern, "", text)

def remove_title(text):
    pattern = r'^([\s\r\n]*\d+[\s\r\n]+)?([\s\r\n]*Senado Federal[\s\r\n]*)?(?:(?:Gabinete)?\s*(?:d[oa]\s*)?Senadora?\s+[^\r\n]+[\s\r\n]+)?([\s\r\n]+\d+[\s\r\n]+)?(?:Emenda\s+da\s+CCJ[\s\r\n]+)?EMENDA\s+(?:N|n)[º°o]?\s*[,-–—_\s]*\s*(?:CCJ|)?\s*\r?\n?\s*(\(?ao\s+(PLP|Projeto[\s\r\n]+de[\s\r\n]+lei[\s\r\n]+complementar)\s*(?:n[º°o]\s*)?68(?:\/|,\s*de\s*)2024\.?\)?)?\s*\r?\n?'
    return re.sub(pattern, '=====================', text, flags=re.IGNORECASE | re.MULTILINE)


def remove_title(text):
    pattern = r'^([\s\S]*?)\((ao)?\s*(?:PLP|Projeto de lei complementar)\s*(?:n[º°o]\s*)?68(?:\/|,\s*de\s*)2024\)'
    return re.sub(pattern, '=====================', text, flags=re.IGNORECASE | re.MULTILINE)

def remove_address(text):
    pattern = r'(?:Praça\s+dos\s+Três\s+Poderes[\s\S]{0,200}?Senado\s+Federal[\s\S]{0,200}?(?:Gabinete\s*\d+|Gabinete\s+\d+|Gabinete\s*[A-Z0-9/.-]+))|(?:SENADO\s+FEDERAL|Senado\s+Federal)[\s|–-]+[\s\S]*?(?:(?:CEP\s*)?\d{2}\.?\d{3}-\d{3}[\s|–/-]*Brasília(?:\s*[–/-]?\s*DF)?|Brasília(?:\s*[–/-]?\s*DF)?[\s|–/-]*(?:CEP\s*)?\d{2}\.?\d{3}-\d{3})(?:[\s\S]{0,300}?(?:Telefone|Fone|Fax|E-?mail)\s*:?[^\n|]*)*(?:[\s\S]{0,150}?[A-Za-z0-9._%+-]+@senad(?:o|or)\.leg\.br)?\.?|(?:Gabinete\s+do\s+Senador[a]?\s+[^\n-]+[\s–|-]*?(?:Telefone|Fone)\s*:\s*\+?\d[\d\s().-]+)\.?'
    return re.sub(pattern, '', text, flags=re.IGNORECASE | re.MULTILINE)

def remove_gabinete(text):
    pattern = r'([\s\r\n]*Senado Federal[\s\r\n]*)?(?:Gabinete\s*(?:d[oa]\s*)?Senadora?\s+[a-zA-Zà-úÀ-Ú ]+[\s\r\n]+)'
    return re.sub(pattern, '', text, flags=re.IGNORECASE | re.MULTILINE)

def extract_after_pl(text):
    pattern = r'(?:\((?:ao)?\s*(?:substitutivo ao)?\s*(?:Projeto de Lei|PLP?|Projeto de Lei Complementar)\s*(?:n[ºo]\.?)?\s*[\d,\.]+/?(?:,?\s*de\s*|\s*/)\d{4}\))(.*)'
    match = re.search(pattern, text, flags=re.IGNORECASE | re.DOTALL)
    if match:
        return match.group(1).strip()
    return text  # Return original text if no match

def remove_lexedit_id(text):
    cleaned = re.sub(r'SF\/\d+\.\d+-\d{2}\s*(\(LexEdit\*?\))?', '', text)
    return cleaned

def remove_digital_signature(text):
    pattern = r'Assinado eletronicamente, por .*?\nPara verificar as assinaturas, acesse https://legis\.senado\.gov\.br/autenticadoc-legis/\d+'
    cleaned = re.sub(pattern, '', text)
    return cleaned.strip()

def remove_num_emenda(text):
    pattern = r'^\s*0\d+(?:-U)?\s*PLP 68\/2024\n?'
    
    return re.sub(pattern, '', text, flags=re.MULTILINE | re.IGNORECASE).strip()

## Pré-processamento

### Remover cabeçalho

#### Padrão geral

In [4]:
plp[plp.texto.str.contains("(ao PLP 68/2024)")]

C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_21364\3349167471.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  plp[plp.texto.str.contains("(ao PLP 68/2024)")]

,num_emenda,materia,nome_arquivo,texto
0,1,PLP_68_2024,EMENDA_1-U_-_PLP_68_2024.txt,Gabinete do Senador Esperidião Amin\nEMENDA Nº...
1,10,PLP_68_2024,EMENDA_10-U_-_PLP_68_2024.txt,Gabinete do Senador Mecias de Jesus\nEMENDA Nº...
2,100,PLP_68_2024,EMENDA_100-U_-_PLP_68_2024.txt,Gabinete do Senador Fabiano Contarato\nEMENDA ...
3,1000,PLP_68_2024,EMENDA_1000-U_-_PLP_68_2024.txt,EMENDA Nº \n(ao PLP 68/2024)\nAcrescen...
4,1001,PLP_68_2024,EMENDA_1001-U_-_PLP_68_2024.txt,EMENDA Nº \n(ao PLP 68/2024)\nDê-se ao...
...,...,...,...,...
2234,995,PLP_68_2024,EMENDA_995-U_-_PLP_68_2024.txt,EMENDA Nº \n(ao PLP 68/2024)\nDê-se ao...
2235,996,PLP_68_2024,EMENDA_996-U_-_PLP_68_2024.txt,EMENDA Nº \n(ao PLP 68/2024)\nAcrescen...
2236,997,PLP_68_2024,EMENDA_997-U_-_PLP_68_2024.txt,EMENDA Nº \n(ao PLP 68/2024)\nAcrescen...
2237,998,PLP_68_2024,EMENDA_998-U_-_PLP_68_2024.txt,EMENDA Nº \n(ao PLP 68/2024)\nDê-se no...
2238,999,PLP_68_2024,EMENDA_999-U_-_PLP_68_2024.txt,EMENDA Nº - CCJ\n(ao PLP 68/2024)\nAcr...

In [5]:
default_header_pattern = r'^([\s\S]*?\(ao\s*(?:PLP|Projeto de lei complementar)\s*(?:n[º°o]\s*)?68(?:\/|,\s*de\s*)2024\)(?:\s*\(ao\s*Projeto\s+de\s+Lei\s+Complementar\s*(?:n[º°o]\s*)?68,\s*de\s*2024\))?)'

plp["cabecalho"] = plp["texto"].str.extract(
    default_header_pattern,
    flags=re.IGNORECASE
)[0]

In [6]:
plp["texto_sem_cabecalho"] = plp["texto"].str.replace(
    default_header_pattern,
    "",
    regex=True,
    flags=re.IGNORECASE
)

In [7]:
plp[plp.cabecalho.str.len() < 100].cabecalho.values

array(['Gabinete do Senador Esperidião Amin\nEMENDA Nº         \n(ao PLP 68/2024)',
       'Gabinete do Senador Mecias de Jesus\nEMENDA Nº         \n(ao PLP 68/2024)',
       'Gabinete do Senador Fabiano Contarato\nEMENDA Nº         \n(ao PLP 68/2024)',
       ..., 'EMENDA Nº         \n(ao PLP 68/2024)',
       'EMENDA Nº         \n(ao PLP 68/2024)',
       'EMENDA Nº         - CCJ\n(ao PLP 68/2024)'],
      shape=(1871,), dtype=object)

#### Exceções

In [8]:
len(plp[plp.cabecalho.isna()])

27

In [9]:
for t in plp[(plp.cabecalho.isna())].texto.values:
    print(t[:500])
    print("+=========================================================")

Gabinete do Senador Jaime Bagattoli






Senado Federal –Anexo 2, Ala Teotônio Vilela, Gabinete 23 - Praça dos Três Poderes – CEP 70165-900 – Brasília DF
Gabinete do Senador Jaime Bagattoli -Telefone: +55 (61) 3303-2714

EMENDA nº

O artigo 9º, inciso III, alínea “b” do projeto passa a ter a redação seguinte:

Art.  9º - ................................................................................
III ................................................................
+=========================================================




Senado Federal – Anexo I – 3º Andar – Praça dos Três Poderes – CEP 70165-900 – Brasília DF
Telefone: +55 (61) 3303-6190 – sen.cironogueira@senado.leg.br
EMENDA Nº       AO PROJETO DE LEI
COMPLEMENTAR Nº 68/2024.

Acrescente-se inciso III ao caput do art. 136 do Projeto, com a
seguinte redação:
“Art.136. ...................................................................................
.............................................................................................
+=========================================================

Gabinete do Senador FLÁVIO ARNS

1


Senado Federal – Ala Dinarte Mariz, gabinete 2/3 – Brasília/DF – CEP 70.165-900
Fone: (61) 3303-6301 – sen.flavioarns@senado.leg.br


EMENDA nº      - 2024
(Projeto de Lei Complementar nº 68, de 2024)



O art. 270 do Projeto de Lei Complementar (PLP) nº 68, de 2024, passa a
vigorar com a seguinte redação:


“Art. 270 ...............................................................................................
..........................
+=========================================================

Gabinete do Senador FLÁVIO ARNS

1


Senado Federal – Ala Dinarte Mariz, gabinete 2/3 – Brasília/DF – CEP 70.165-900
Fone: (61) 3303-6301 – sen.flavioarns@senado.leg.br


EMENDA nº      - 2024
(Projeto de Lei Complementar nº 68, de 2024)



O art. 163 do Projeto de Lei Complementar (PLP) nº 68, de 2024, passa a
vigorar com a seguinte redação:

“Art. 163. O contribuinte de IBS e de CBS sujeito ao regime regular
poderá apropriar créditos presumidos dos referidos tributos relati
+=========================================================

Gabinete do Senador FLÁVIO ARNS

1


Senado Federal – Ala Dinarte Mariz, gabinete 2/3 – Brasília/DF – CEP 70.165-900
Fone: (61) 3303-6301 – sen.flavioarns@senado.leg.br


EMENDA nº      - 2024
(Projeto de Lei Complementar nº 68, de 2024)



O inciso II do §1º do art. 270 do Projeto de Lei Complementar (PLP) nº 68,
de 2024, passa a vigorar com a seguinte redação:

“Art. 270 ..............................................................................................
.........
+=========================================================


1


EMENDA Nº
(Projeto de Lei Complementar nº 68/2024)


Acrescente-se ao art. 406 do PLP 68/2024 o seguinte § 3º:

"§ 3º Ficam isentas do Imposto Seletivo a aquisição dos
bens previstos nos incisos I e II do § 1º deste artigo, bem
como de suas partes e peças separadas, quando
destinados à utilização nas atividades dos Corpos de
Bombeiros e da Defesa Civil em todo o território nacional."
(NR)



JUSTIFICAÇÃO


A proposta de inclusão do § 3º no artigo em questão visa a
+=========================================================


1



EMENDA Nº         - CCJ
(Projeto de Lei Complementar nº 68/2024)



Os arts. 51 a 55, 205 e 225 do PLP 68/2024 passam a vigorar
com a seguinte redação:
“Art. 51. Os prestadores de serviços de pagamento, participantes
de arranjos abertos e fechados, públicos e privados, que participam
da liquidação da transação de pagamento deverão observar a
vinculação entre:
.........................................................
§ 3º A prestação das informações de que trata o caput
+=========================================================


1

EMENDA Nº         - CCJ
(Projeto de Lei Complementar nº 68/2024)



Dê-se ao artigo 93 do Projeto de Lei Complementar nº 68, de
2024 nova redação, com a inserção da expressão “e os serviços”, e
com a inclusão de um novo parágrafo 7º:

“Art. 93. Fica suspenso o pagamento do IBS e da CBS incidentes na
importação enquanto os bens materiais e os serviços estiverem
submetidos a regime aduaneiro especial de aperfeiçoamento, observada
a disciplina estabelecida pela legislação adua
+=========================================================


1



EMENDA Nº         - CCJ
(Projeto de Lei Complementar nº 68/2024)




Dê-se ao artigo nº 137 do Projeto de Lei Complementar
nº 68, de 2024 nova redação, com a exclusão dos seus incisos I e II
e o acréscimo de um Parágrafo único:

“Art. 137. Ficam reduzidas em 60% (sessenta por cento) as
alíquotas do IBS e da CBS sobre a prestação dos serviços e a
venda, à administração pública direta, autarquias, fundações
públicas e empresas públicas de defesa, dos bens relativos à
so
+=========================================================





SENADO FEDERAL
Gabinete do Senador Beto Martins


EMENDA Nº    CCJ
 Projeto de Lei Complementar nº 68/2024


Inclui a Seção VIII, formada pelos arts. 270, 270-A, 270-B e 270-C, no
Projeto de Lei Complementar nº 68, de 2024:

“Seção VIII - Do Período de Transição”

“OPERAÇÕES INICIADAS ANTES DE 1º DE JANEIRO DE 2027.”

“SUBSEÇÃO I – Incorporação”

“Art. 270. O contribuinte que realizar incorporação imobiliária
submetida ao patrimônio de afetação, nos termos dos artigos
+=========================================================



SENADO FEDERAL
Gabinete do Senador Beto Martins

EMENDA Nº     CCJ

PROJETO DE LEI COMPLEMENTAR Nº 68/2024

Institui o Imposto sobre Bens e
Serviços IBS, a Contribuição
Social sobre Bens e Serviços -
CBS e o Imposto Seletivo - IS e
dá outras providências.

Alterem-se os artigos 103 e 488 do PLP nº 68/2024 para estender o
Regime Tributário para Incentivo à Modernização e à Ampliação da
Estrutura Portuária – Reporto aos Recintos Especiais para o Despacho
Aduaneiro de Export
+=========================================================



SENADO FEDERAL
Gabinete do Senador Beto Martins


EMENDA Nº __ CCJ
Projeto de Lei Complementar nº 68/2024

Altera a redação do caput e do parágrafo único do art. 257 do Projeto
de Lei Complementar nº 68, de 2024:


“Art. 257. As alíquotas do IBS e da CBS relativas às operações de
que trata este capítulo ficam reduzidas em 60% (sessenta por cento).”



JUSTIFICAÇÃO
A habitação é um direito social expressamente previsto no art. 6º da
Constituição Federal, motivo pelo qual m
+=========================================================


1



EMENDA Nº         - CCJ
(Projeto de Lei Complementar nº 68/2024)




Dê-se ao artigo nº 144, § 2º, II, do Projeto de Lei
Complementar nº 68, de 2024, nova redação, com o seguinte texto:

“Art. 144.................................................
...............................................................
§ 2º - As reduções de alíquotas de que trata o caput somente se
aplicam:
I - na hipótese do inciso I do caput deste artigo, a automóvel de
passageiros elétrico ou
+=========================================================


1



EMENDA Nº         - CCJ
(Projeto de Lei Complementar nº 68/2024)




Dê-se ao artigo nº 144, § 2º, II, do Projeto de Lei
Complementar nº 68, de 2024, nova redação, com o seguinte texto:

“Art. 144.................................................
...............................................................
§ 2º - As reduções de alíquotas de que trata o caput somente se
aplicam:
..................................................................
II – na hipótese do in
+=========================================================


1


EMENDA Nº         - CCJ
(Projeto de Lei Complementar nº 68/2024)




Suprima-se o § 3º, do artigo 144, do Projeto de Lei
Complementar nº 68, de 2024.

JUSTIFICAÇÃO
No Artigo 144, § 3º, o deficiente que adquirir o veículo sem
adaptações, para condução própria, seria tributado, enquanto aquele
que comprar o veículo com alguma adaptação não o seria.
Em termos práticos, um cidadão com a perna direita amputada
será contemplado com isenção tributária para a aquisição de veíc
+=========================================================


1



EMENDA Nº         - CCJ
(Projeto de Lei Complementar nº 68/2024)




Inclua-se o § 3º ao artigo nº 146 do Projeto de Lei
Complementar nº 68, de 2024, nova redação, com o seguinte texto:

“Art. 146.................................................
...............................................................
§ 3º - A comprovação da deficiência não será necessária nos casos
de pessoas com deficiência que comprovadamente tenham lesões
ou deficiências permanentes, determi
+=========================================================

Gabinete do Senador Hamilton Mourão


EMENDA PROJETO DE LEI COMPLEMENTAR Nº 68, DE 2024.


Institui o Imposto sobre Bens e Serviços – IBS,
a Contribuição Social sobre Bens e Serviços –
CBS
e o Imposto Seletivo – IS e dá outras
providências.



EMENDA Nº


Sugerimos a inclusão dos artigos 37-A e 37-B na Seção IX – Da Não
Cumulatividade, do Capítulo II, do Título I, do Livro I, do PLP nº 68/2024, nos
seguintes termos:
Art. 37-A. Sairão do estabelecimento industrial com sus
+=========================================================

Gabinete do Senador Hamilton Mourão


EMENDA PROJETO DE LEI COMPLEMENTAR Nº 68, DE 2024.


Institui o Imposto sobre Bens e Serviços – IBS,
a Contribuição Social sobre Bens e Serviços –
CBS
e o Imposto Seletivo – IS e dá outras
providências.



EMENDA Nº


Sugerimos nova redação, com alteração da redação do caput do art. 105 do
PLP 68, e inclusão do §6º ao dispositivo; e com alteração da redação do art. 58,
§4º, inciso I, nos seguintes termos:


Art. 58. O contribuinte
+=========================================================
O Art. 133 do PLP 68/2024 passa a ter a seguinte redação:
“Art.133. (...)
§ 1º A redução de alíquotas prevista no caput somente se aplica aos produtos de
que trata o Anexo IX que, quando exigido, estejam registrados como insumos agropecuários
ou aquícolas no órgão competente do Ministério da Agricultura e Pecuária e da NBS.
(...)
§ 5º A redução de alíquotas prevista no caput é vedada a produtos que apresentam
riscos à saúde ou ao meio ambiente, que de acordo com algum dos órgãos competentes
que
+=========================================================
1

Gabinete da Senadora Rosana Martinelli




Senado Federal – Praça dos Três Poderes – CEP 70165-900 – Brasília DF
PROJETO DE LEI COMPLEMENTAR Nº 68/2024
EMENDA Nº _______, DE 2024

Institui o Imposto sobre Bens e
Serviços IBS, a Contribuição Social
sobre Bens e Serviços - CBS e o
Imposto Seletivo - IS e dá outras
providências.

EMENDA

Substitua-se o seguinte artigo do Projeto de Lei Complementar nº 68 de 2024:
Art. 37. ....................................................
+=========================================================
1

Gabinete da Senadora Rosana Martinelli




Senado Federal – Praça dos Três Poderes – CEP 70165-900 – Brasília DF
PROJETO DE LEI COMPLEMENTAR Nº 68/2024
EMENDA Nº _______, DE 2024

Institui o Imposto sobre Bens e
Serviços IBS, a Contribuição Social
sobre Bens e Serviços - CBS e o
Imposto Seletivo - IS e dá outras
providências.

EMENDA

Substitua-se o seguinte artigo do Projeto de Lei Complementar nº 68 de 2024:
Art. 33.  No caso de operações sujeitas a redução ou alíquota
+=========================================================
1

Gabinete da Senadora Rosana Martinelli




Senado Federal – Praça dos Três Poderes – CEP 70165-900 – Brasília DF
PROJETO DE LEI COMPLEMENTAR Nº 68/2024
EMENDA Nº _______, DE 2024

Institui o Imposto sobre Bens e
Serviços IBS, a Contribuição Social
sobre Bens e Serviços - CBS e o
Imposto Seletivo - IS e dá outras
providências.

EMENDA

Substitua-se o seguinte artigo do Projeto de Lei Complementar nº 68 de 2024:
Art. 28 .....................................................
+=========================================================
1

Gabinete da Senadora Rosana Martinelli




Senado Federal – Praça dos Três Poderes – CEP 70165-900 – Brasília DF
PROJETO DE LEI COMPLEMENTAR Nº 68/2024
EMENDA Nº _______, DE 2024

Institui o Imposto sobre Bens e
Serviços IBS, a Contribuição Social
sobre Bens e Serviços - CBS e o
Imposto Seletivo - IS e dá outras
providências.

EMENDA

Suprima-se o inciso V do artigo 24 do Projeto de Lei Complementar nº 68 de 2024.

JUSTIFICATIVA
Esta previsão do art. 24, V, cria uma hi
+=========================================================
1

Gabinete da Senadora Rosana Martinelli




Senado Federal – Praça dos Três Poderes – CEP 70165-900 – Brasília DF
PROJETO DE LEI COMPLEMENTAR Nº 68/2024
EMENDA Nº _______, DE 2024

Institui o Imposto sobre Bens e
Serviços IBS, a Contribuição Social
sobre Bens e Serviços - CBS e o
Imposto Seletivo - IS e dá outras
providências.

EMENDA

Substitua-se o seguinte artigo do Projeto de Lei Complementar nº 68 de 2024:
Art. 12 .....................................................
+=========================================================
1

Gabinete da Senadora Rosana Martinelli




Senado Federal – Praça dos Três Poderes – CEP 70165-900 – Brasília DF
PROJETO DE LEI COMPLEMENTAR Nº 68/2024
EMENDA Nº _______, DE 2024

Institui o Imposto sobre Bens e
Serviços IBS, a Contribuição Social
sobre Bens e Serviços - CBS e o
Imposto Seletivo - IS e dá outras
providências.

EMENDA

Inclua-se o seguinte artigo do Projeto de Lei Complementar nº 68 de 2024:
Art. 7º ........................................................
+=========================================================
1

Gabinete da Senadora Rosana Martinelli




Senado Federal – Praça dos Três Poderes – CEP 70165-900 – Brasília DF
PROJETO DE LEI COMPLEMENTAR Nº 68/2024
EMENDA Nº _______, DE 2024

Institui o Imposto sobre Bens e
Serviços IBS, a Contribuição Social
sobre Bens e Serviços - CBS e o
Imposto Seletivo - IS e dá outras
providências.

EMENDA

Substitua-se o seguinte artigo do Projeto de Lei Complementar nº 68 de 2024:
Art. 419.....................................................
+=========================================================


1


EMENDA Nº         - CCJ
(Projeto de Lei Complementar nº 68/2024)


Dê-se ao art. 280 do Projeto de Lei Complementar nº 68/2024
a seguinte redação:

"Art. 280. Fica reduzida em 60% (sessenta por cento) a
alíquota do Imposto sobre Bens e Serviços (IBS) e da
Contribuição sobre Bens e Serviços (CBS) incidentes sobre
as atividades de hotelaria, parques de diversão e parques
temáticos.” (NR)

JUSTIFICAÇÃO

Essa proposta de emenda ao PLP 68/2024 visa a promover a
competitivi
+=========================================================

In [10]:
set(plp["texto_sem_cabecalho"].str.split().str[0].values)

{'(Do',
 '1',
 '1)',
 'A',
 'ANEXO',
 'Acrescenta',
 'Acrescenta-se',
 'Acrescentam-se',
 'Acrescente',
 'Acrescente-se',
 'Acrescente-se,',
 'Acrescentem-se',
 'Acrescentem-se,',
 'Acresça-se',
 'Acresçam-se',
 'Ajuste-se',
 'Altera',
 'Altera-se',
 'Alteram-se',
 'Alteração',
 'Altere-se',
 'Altere-se,',
 'Alterem-se',
 'Anexo',
 'Art.',
 'Art.1º',
 'Art.283.................................................................................................................................',
 'Atribua-se',
 'Confira-se',
 'Determine-se',
 'Dá',
 'Dá-se',
 'Dê',
 'Dê-se',
 'Dêem-se',
 'EMENDA',
 'Exclua-se',
 'Excluam-se',
 'Fica',
 'Ficam',
 'Gabinete',
 'Inclua-se',
 'Inclua-se,',
 'Incluam-se',
 'Inclui',
 'Inclui-se',
 'Inclusão',
 'Insere-se',
 'Inserir',
 'Insira-se',
 'Insiram-se',
 'Institui',
 'Item',
 'Modifica',
 'Modifica-se',
 'Modificação',
 'Modifique-se',
 'No',
 'O',
 'Os',
 'PROJETO',
 'SENADO',
 'Senado',
 'Substitua-se',
 'Suprima-se',
 'Suprimam-se',
 'Suprimam–se',
 'São',
 'a)',
 '“Art.'}

In [11]:
import re

CORRECT_START_PATTERNS = [
    r"O artigo\b",
    r"O art\.",
    r"\bOs arts?\.",
    r"\bO inciso\b",
    r"\bAcrescente-se\b",
    r"\bAcrescentem-se\b",
    r"\bAcrescente\b",
    r"\bAcrescenta-se\b",
    r"\bAcrescenta\b",
    r"\bAcrescentam-se\b",
    r"\bAcresça-se\b",
    r"\bAcresçam-se\b",
    r"\bInclua-se\b",
    r"\bIncluam-se\b",
    r"\bInclui\b",
    r"\bInclui-se\b",
    r"\bInclusão\b",
    r"\bInserir\b",
    r"\bInsira-se\b",
    r"\bInsiram-se\b",
    r"\bInsere-se\b",
    r"\bSuprima-se\b",
    r"\bSuprimam-se\b",
    r"\bSubstitua-se\b",
    r"\bDê-se\b",
    r"\bDê\b",
    r"\bDêem-se\b",
    r"\bDá-se\b",
    r"\bAltera\b",
    r"\bAltera-se\b",
    r"\bAlterem-se\b",
    r"\bAlteram-se\b",
    r"\bAltere-se\b",
    r"\bModifique-se\b",
    r"\bModifica\b",
    r"\bModifica-se\b",
    r"\bAjuste-se\b",
    r"\bDetermine-se\b",
    r"\bConfira-se\b",
    r"\bExclua-se\b",
    r"\bExcluam-se\b",
    r"\bAtribua-se\b",
    r"\bFica\b",
    r"\bFicam\b",
    r"\bSugerimos\b",
]

except_header_pattern = re.compile(
    rf"(?:{'|'.join(CORRECT_START_PATTERNS)})",
    re.IGNORECASE | re.MULTILINE
)

In [12]:
def get_exception_header(text, pattern=except_header_pattern):
    if not isinstance(text, str):
        return None, text

    m = pattern.search(text)

    if not m:
        return None, text

    idx = m.start()

    return text[:idx].strip(), text[idx:].strip()

In [13]:
mask = plp["cabecalho"].isna()

resultado = plp.loc[mask, "texto"].apply(get_exception_header)

plp.loc[mask, "cabecalho"] = resultado.str[0].to_numpy()
plp.loc[mask, "texto_sem_cabecalho"] = resultado.str[1].to_numpy()

In [14]:
plp[plp["cabecalho"].isna()]

Empty DataFrame
Columns: [num_emenda, materia, nome_arquivo, texto, cabecalho, texto_sem_cabecalho]
Index: []

#### Remover ementa

In [15]:
print(len(plp[plp["texto_sem_cabecalho"].str.contains("Institui o Imposto sobre Bens")]))

55

In [16]:
plp[plp["texto_sem_cabecalho"].str.contains("Institui o Imposto sobre Bens")].texto_sem_cabecalho.str[:500].values

array([' \nInstitui o Imposto sobre Bens e Serviços - \nIBS, a Contribuição Social sobre Bens e \nServiços - CBS e o Imposto Seletivo - IS e dá \noutras providências. \n \nArt. 1º. Suprima-se o artigo 35 do Projeto de Lei Complementar nº \n68 de 2024.  \nJUSTIFICAÇÃO \nA ausência de prazo para a utilização dos créditos tributários visa \nproporcionar maior flexibilidade e segurança jurídica aos contribuintes.  \nEm muitos casos, o prazo limitado para a utilização de créditos pode \nimpedir que empresas com fluxos d',
       ' \nInstitui o Imposto sobre Bens e Serviços - \nIBS, a Contribuição Social sobre Bens e \nServiços - CBS e o Imposto Seletivo - IS e dá \noutras providências. \n \nArt. 1º. Adicione-se o seguinte dispositivo do Projeto de Lei \nComplementar nº 68 de 2024: \n \nArt. 58. ............................................................................................... \n................................................................................................ \n§12º Nas operações efetuadas por contribuint',
       ' \nInstitui o Imposto sobre Bens e Serviços - \nIBS, a Contribuição Social sobre Bens e \nServiços - CBS e o Imposto Seletivo - IS e dá \noutras providências. \n \nArt. 1º. Adicione-se o seguinte dispositivo do Projeto de Lei \nComplementar nº 68 de 2024: \n \nArt. 101. ............................................................................................... \n................................................................................................ \nIII - do transporte de bens destinados à ex',
       ' \nInstitui o Imposto sobre Bens e Serviços - \nIBS, a Contribuição Social sobre Bens e \nServiços - CBS e o Imposto Seletivo - IS e dá \noutras providências. \n \nArt. 1º. Adicione-se o seguinte dispositivo do Projeto de Lei \nComplementar nº 68 de 2024: \n \nArt. 28. ............................................................................................... \n................................................................................................ \n§2º Os créditos de CBS poderão ser compensad',
       '\nPROJETO DE LEI COMPLEMENTAR Nº 68/2024\nEMENDA Nº _______, DE 2024\n(Do Sr. Senador Zequinha Marinho)\n \nInstitui o Imposto sobre Bens e Serviços IBS, a Contribuição Social\nsobre Bens e Serviços - CBS e o Imposto Seletivo - IS e dá outras providências.\n EMENDA\nArt. 1º. Inclua-se e ajuste-se os seguintes itens no Anexo I do\nProjeto de Lei Complementar nº 68 de 2024:\n .............................................................................................................\n9\nÓleos vegetais destin',
       '\nAcrescente-se um novo Artigo nº 509-A, ao Projeto de Lei\nComplementar nº 68, de 2024, que “Institui o Imposto sobre Bens e Serviços (IBS),\na Contribuição Social sobre Bens e Serviços (CBS) e o Imposto Seletivo (IS); e dá\noutras providências.” com a seguinte redação:\nArt. 509-A. A Lei Complementar nº 200, de 30 de agosto de 2023, passa\na vigorar com a seguinte alteração:\n“Art. 13. Os precatórios decorrentes de demandas relativas à\ncomplementação da União aos Estados e aos Municípios por conta do',
       '\nPROJETO DE LEI COMPLEMENTAR Nº 68/2024\nEMENDA Nº _______, DE 2024\n(Do Sr. Senador Zequinha Marinho)\n \nInstitui o Imposto sobre Bens e Serviços IBS, a Contribuição Social\nsobre Bens e Serviços - CBS e o Imposto Seletivo - IS e dá outras providências.\n EMENDA\nArt. 1º. Inclua-se os seguintes itens no Anexo IX do Projeto de Lei\nComplementar nº 68 de 2024:\n  Item\nDescrição\nNCM\n1\nCondicionadores de solo e\nsubstratos para plantas de\norigem orgânica ou mineral\n2520.20.90\n2503.00.90\n2510.10.10\n2510.10.9',
       '\nPROJETO DE LEI COMPLEMENTAR Nº 68/2024\nEMENDA Nº _______, DE 2024\n(Do Sr. Senador Zequinha Marinho)\n \nInstitui o Imposto sobre Bens e Serviços IBS, a Contribuição Social\nsobre Bens e Serviços - CBS e o Imposto Seletivo - IS e dá outras providências.\nEMENDA\nArt. 1º. Suprima-se o termo “bebidas açucaradas” e a NCM\n2202.10.00 do Anexo XVII do Projeto de Lei Complementar nº 68 de 2024.\nJUSTIFICAÇÃO\nA presente supressão se justifica pois a não incidência do imposto\nseletivo sobre bebidas açucaradas ',
       '\nPROJETO DE LEI COMPLEMENTAR Nº 68/2024\nEMENDA Nº _______, DE 2024\n(Do Sr. Senador Zequinha Marinho)\n \nInstitui o Imposto sobre Bens e Serviços IBS, a Contribuição Social\nsobre Bens e Serviços - CBS e o Imposto Seletivo - IS e dá outras providências.\n EMENDA\nArt. 1º. Inclua-se os seguintes itens no Anexo IX do Projeto de Lei\nComplementar nº 68 de 2024:\n  Item\nDescrição\nNCM\n1\nCondicionadores de solo e\nsubstratos para plantas de\norigem orgânica ou mineral\nCapítulos 12, 14, 25, 27, 44, 47\ne 53\n2\n..',
       '\nDê-se ao art. 125 da Proposta de Lei Complementar nº 68 de 2024, a\nseguinte redação:\nArt. 125.   Ficam reduzidas em 60% (sessenta por cento) as alíquotas do IBS\ne da CBS incidentes sobre o fornecimento dos serviços de saúde relacionados no Anexo III,\ncom a especificação das respectivas classificações da NBS.\nInclusão no Anexo III da NBS - 1.1405: Serviços veterinários ao lado\ndos demais serviços de saúde.\n \nDê-se ao inciso XIII do art. 122 da PLP nº 68 de 2024, a seguinte\nredação: \nArt. 122. Fi',
       '\nAcrescente-se art. 122-1 ao Capítulo II do Título IV do Livro I do\nProjeto, com a seguinte redação:\n“Art. 122-1. Ficam reduzidas em 30% (trinta por cento) as alíquotas\ndo IBS e da CBS incidentes sobre a prestação de serviços pelas pessoas jurídicas\nprestadoras de serviços veterinários para animais domésticos, independente da\nnatureza jurídica da sociedade e dos requisitos estabelecidos no inciso II do § 1º\ndo art. 122.”\nOs dispositivos acima propostos e adjacentes deverão ser devidamente renume',
       '\nEMENDA Nº   - CCJ\n(ao PLP 68/2024)\nPROPOSTA DE EMENDA AO PLP Nº 68/2024\nInstitui o Imposto sobre Bens e Serviços - IBS, a Contribuição Social\nsobre Bens e Serviços - CBS e o Imposto Seletivo - IS e dá outras providências.\n \nEMENDA MODIFICATIVA Nº\n \nDê-se à alínea “b” do item I do artigo 411; ao § 2º do art.419; e ao caput\ne §1º do art. 420 do PLP nº 68/2024, a seguinte redação.\nArt. 411. Aplica-se:\nI- Imunidade do Imposto Seletivo para:\n(...)\nb) as operações com energia elétrica, abrangendo os ',
       'Sugerimos a inclusão dos artigos 37-A e 37-B na Seção IX – Da Não \nCumulatividade, do Capítulo II, do Título I, do Livro I, do PLP nº 68/2024, nos \nseguintes termos: \nArt. 37-A. Sairão do estabelecimento industrial com suspensão \ndo IBS e da CBS as matérias-primas, os produtos intermediários \ne os materiais de embalagem, os componentes, chassis, \ncarroçarias, acessórios, partes e peças, adquiridos para \nemprego na industrialização dos produtos autopropulsados a \nque se refere o §5º, do art. 105 ',
       'Sugerimos nova redação, com alteração da redação do caput do art. 105 do \nPLP 68, e inclusão do §6º ao dispositivo; e com alteração da redação do art. 58, \n§4º, inciso I, nos seguintes termos: \n \n \nArt. 58. O contribuinte do IBS e da CBS que apurar saldo credor \nao final do período de apuração poderá solicitar seu \nressarcimento integral ou parcial.  \n[...] \n \n§4º O prazo para apreciação do pedido de ressarcimento será \nde:  \n \nI – até 30 (trinta) dias contados da data da solicitação de que \ntra',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nInclua-se o seguinte artigo ao PLP 68/2024: \n \nSeção IV  \n \nDO REGIME ESPECIAL TRIBUTÁRIO PARA A INDÚSTRIA DE DEFESA – \nRETID  \n \nArt. 105-A: Observada a disciplina estabelecida pela legislação específica, serão \nefetuadas com suspensão do pagamento do IBS e da CBS, as importações e as \naquisições de bens no mercado interno de máquinas, eq',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nDê-se nova redação ao seguinte dispositivo: \n \nArt. 393. Caso seja constatada irregularidade em procedimento de revisão da \napuração do crédito apresentado para pagamento, a autoridade competente \nlavrará despacho decisório que será cientificado ao interessado com os \nfundamentos e os elementos de prova necessários, denegando total ou \npar',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nDê-se nova redação ao seguinte dispositivo: \n \n“Art. 385. Em relação às compensações dos benefícios onerosos de que trata o \nart. 383 desta Lei Complementar, compete a RFB:  \n(...)  \nParágrafo único. Para fins deste Capítulo, aplica-se subsidiariamente a regulamentação do \nprocesso administrativo fiscal prevista na Lei nº 9.784, de 29 de j',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nDê-se nova redação ao seguinte dispositivo: \n \nArt. 317. O Conselho Administrativo de Recursos Fiscais, o Comitê Gestor do IBS, \na RFB e a Procuradoria-Geral da Fazenda Nacional atuarão com vistas a \nharmonizar normas, interpretações, obrigações acessórias e procedimentos \nrelativos ao IBS e à CBS.” \n \nJUSTIFICAÇÃO \nNo que se refere à harm',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nDê-se nova redação ao seguinte dispositivo: \n \nArt. 137. Ficam reduzidas em 60% (sessenta por cento) as alíquotas do IBS e da \nCBS sobre a prestação dos serviços e a venda, à administração pública direta, \nautarquias, fundações públicas e empresas públicas de defesa, dos bens \nrelativos à soberania e segurança nacional, segurança da inform',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nDê-se nova redação ao seguinte dispositivo: \n \nArt. 93. Fica suspenso o pagamento do IBS e da CBS incidentes na importação \nenquanto os bens materiais e os serviços estiverem submetidos a regime \naduaneiro especial de aperfeiçoamento, observada a disciplina estabelecida \npela legislação aduaneira.” \n(...) \n§ 2º A suspensão de que trata o c',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nDê-se nova redação ao seguinte dispositivo: \n \nArt. 280. Fica reduzida em 60% (sessenta por cento) a alíquota do Imposto sobre Bens e Serviços \n(IBS) e da Contribuição sobre Bens e Serviços (CBS) incidentes sobre as atividades de hotelaria, \nparques de diversão e parques temáticos.” \n \nJUSTIFICAÇÃO \n \nEssa proposta de emenda ao PLP 68/2024',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nDê-se nova redação ao seguinte dispositivo: \n \nArt. 134. Ficam reduzidas em 60% (sessenta por cento) as alíquotas \ndo IBS e da CBS incidentes sobre o fornecimento dos serviços e o \nlicenciamento ou cessão dos direitos relacionados no Anexo X desta \nLei Complementar, com a especificação das respectivas classificações \nda NBS, quando destina',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nDê-se nova redação ao seguinte dispositivo: \n \nAltera o anexo X - Produções Nacionais Artísticas, Culturais, de Eventos, Jornalísticas e \nAudiovisuais submetidas à Redução de 60% das Alíquotas do IBS e da CBS do texto substitutivo \ndo Projeto de Lei Complementar nº. 68/2024, adicionando os seguintes números de \nidentificação da Nomenclatur',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nDê-se nova redação ao seguinte dispositivo: \n \n“Art. 5º O IBS e a CBS também incidem sobre as seguintes operações, \nainda que não onerosas: \n... \nI - fornecimento não oneroso ou a valor inferior ao de mercado de bens e \nserviços para uso e consumo pessoal: \nc) dos empregados diretos dos contribuintes de que tratam as alíneas “a” \ne “b” des',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nDê-se nova redação ao seguinte dispositivo: \n“Art. 249. (...) \n \nIII - na locação, administração, cessão onerosa ou arrendamento de bem imóvel, \nno momento do vencimento da obrigação de pagar, conforme estabelecido pelo \ncontrato, e desde que o pagamento tenha sido realizado.” \n \n \n“Art. 256. Na operação de locação, cessão onerosa ou arren',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nDê-se nova redação ao seguinte dispositivo: \n \n“Art. 257. As alíquotas do IBS e da CBS relativas às operações de que trata este \ncapítulo ficam reduzidas em 60% (sessenta por cento). \n \nParágrafo único. As alíquotas do IBS e da CBS relativas às operações de locação, \ncessão onerosa e arrendamento de bens imóveis ficam reduzidas em 80% \n(oi',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nDê-se nova redação ao seguinte dispositivo: \n \n“Art. 3º O terreno e as acessões objeto da incorporação imobiliária sujeitas ao \nregime especial de tributação, bem como os demais bens e direitos a ela \nvinculados, não responderão por dívidas tributárias da incorporadora relativas \nao Imposto sobre a Renda das Pessoas Jurídicas – IRPJ, à Con',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nDê-se nova redação ao seguinte dispositivo: \n \n“Art. 248-A. Para efeito do disposto no art. 21, inciso I, “b”, desta lei, considera-\nse contribuinte do IBS e da CBS aquele que realizar alienação, locação, cessão \nonerosa ou arrendamento de bem imóvel de forma habitual ou em volume que \ncaracterize atividade econômica, quando: \n \nI - Na loc',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nInclua-se o seguinte dispositivo: \n \n“Seção VIII - Do Período de Transição”  \n \n“OPERAÇÕES INICIADAS ANTES DE 1º DE JANEIRO DE 2027.” \n \n“SUBSEÇÃO I – Incorporação” \n \n“Art. 270. O contribuinte que realizar incorporação imobiliária submetida ao \npatrimônio de afetação, nos termos dos artigos 31-A a 31-E da Lei nº 4.591, de \n16 de dezembro ',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nDê-se nova redação aos seguintes dispositivos: \n \n“Art. 378. Os créditos do PIS e da COFINS, inclusive \npresumidos, não apropriados ou não utilizados até a data de \nextinção dessas contribuições:  \nI - permanecerão válidos e utilizáveis na forma deste \nCapítulo, sem limite de prazo para sua utilização, \nobservado o disposto nos artigos 380',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nDê-se nova redação aos seguintes dispositivos: \n \nCAPÍTULO III \nDOS REGIMES DE BENS DE CAPITAL \nSEÇÃO II \nDO REGIME ESPECIAL DE INCENTIVOS PARA O \nDESENVOLVIMENTO DA INFRAESTRUTURA - REIDI \n \n“Art. 104. Observada a disciplina estabelecida na legislação \nespecífica, serão efetuadas com suspensão do pagamento do IBS \ne da CBS as importações ',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nDê-se nova redação aos seguintes dispositivos: \n \nCAPÍTULO IV \nDO REEQUILÍBRIO DE CONTRATOS ADMINISTRATIVOS \n \n(...) \nArt. 375. A administração pública poderá proceder, em comum \nacordo com a contratada, à revisão dos contratos para \nrestabelecimento do equilíbrio econômico-financeiro quando \nconstatada a redução da carga tributária efetiv',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nInclua-se o § 6º ao art. 105 do PLP nº 68/2024, com a seguinte redação. \n \n \nSeção III \nDa Desoneração da Aquisição de Bens de Capital \n \n \n“Art. 105. Ato conjunto do Poder Executivo da União e do Comitê \nGestor do IBS poderá definir hipóteses em que importações e \naquisições no mercado interno de bens de capital serão \nrealizadas com susp',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nExclua-se o § 7º do art. 103 do PLP nº 68/2024. \n \n \nJUSTIFICAÇÃO \n \nA regulamentação da Reforma Tributária implementada pela EC 132/23 \nproposta no Projeto de Lei Complementar (PLP) nº 68/24 seguiu o caminho \ncorreto e atendeu a um pleito geral do setor de infraestrutura ao manter \ndisposições já vigentes em relação ao REIDI, REPORTO e re',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nNo artigo 307 do Projeto de Lei Complementar 68 de 2024, acrescenta-se o parágrafo 3°, \no qual passará a vigorar com a seguinte redação:  \n \n \n“§ 3° - Não haverá incidência do IBS sobre as bolsas ofertadas \npelo PROUNI.” \n \n \nJUSTIFICAÇÃO \n \nA EC 132/23, que institui a Reforma Tributária, extingue a grande maioria dos benefícios \nfiscais v',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nNo anexo II do Projeto de Lei Complementar 68 de 2024 acrescenta-se quadro descrito \nabaixo:  \n \n \n2. Atividades Educacionais \nComplementares agregadas a \nqualquer das etapas de \neducação tratadas no item 1 \ndeste anexo \n \n2.1 Serviços de educação \ncom enfoque cultural  \nCódigo 1.2205.11.00 \n2.2 Serviços de educação \ndesportiva e recreacio',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nArt. 1º Suprima-se o art. o artigo 288 do Projeto de Lei Complementar nº 68, de 2024. \nArt. 2º Dê-se a seguinte redação ao artigo 289 do PLP 68/2024: \n \n“Art. 289. Na intermediação de serviços turísticos prestados por agências \nde turismo: (...)” \n \n \nJUSTIFICAÇÃO \n \nO PLP 68/24 optou por segregar as disposições relativas às atividades pre',
       ' \n \nInstitui o Imposto sobre Bens e \nServiços IBS, a Contribuição Social \nsobre Bens e Serviços - CBS e o \nImposto Seletivo - IS e dá outras \nprovidências. \n \nInsere os parágrafos 1º e 2º no artigo 290, do Projeto de Lei Complementar nº 68, de \n2024, com as seguintes redações: \n \n“Art. 290.  \n            (...) \n§1º – Os valores relativos às indenizações pagas pelas agências de \nturismo em virtude de responsabilização por serviços prestados pelos \nfornecedores intermediados, desde que decorrente ',

In [17]:
def remover_ementa(texto):
    pattern = (
    r'^\s*institui\s+o\s+imposto\s+sobre\s+bens\s+e\s+serviços[\s\S]*?provid[eê]ncias\.\s*'
    )
    
    return re.sub(
        pattern,
        '',
        texto,
        flags=re.IGNORECASE
    )

In [18]:
plp[plp["texto_sem_cabecalho"].str.contains("Institui o Imposto sobre Bens")].texto_sem_cabecalho.apply(remover_ementa).str[:50].values

array(['Art. 1º. Suprima-se o artigo 35 do Projeto de Lei ',
       'Art. 1º. Adicione-se o seguinte dispositivo do Pro',
       'Art. 1º. Adicione-se o seguinte dispositivo do Pro',
       'Art. 1º. Adicione-se o seguinte dispositivo do Pro',
       '\nPROJETO DE LEI COMPLEMENTAR Nº 68/2024\nEMENDA Nº ',
       '\nAcrescente-se um novo Artigo nº 509-A, ao Projeto',
       '\nPROJETO DE LEI COMPLEMENTAR Nº 68/2024\nEMENDA Nº ',
       '\nPROJETO DE LEI COMPLEMENTAR Nº 68/2024\nEMENDA Nº ',
       '\nPROJETO DE LEI COMPLEMENTAR Nº 68/2024\nEMENDA Nº ',
       '\nDê-se ao art. 125 da Proposta de Lei Complementar',
       '\nAcrescente-se art. 122-1 ao Capítulo II do Título',
       '\nEMENDA Nº   - CCJ\n(ao PLP 68/2024)\nPROPOSTA DE EM',
       'Sugerimos a inclusão dos artigos 37-A e 37-B na Se',
       'Sugerimos nova redação, com alteração da redação d',
       'Inclua-se o seguinte artigo ao PLP 68/2024: \n \nSeç',
       'Dê-se nova redação ao seguinte dispositivo: \n \nArt',
       'Dê-se nova redação ao seguinte dispositivo: \n \n“Ar',
       'Dê-se nova redação ao seguinte dispositivo: \n \nArt',
       'Dê-se nova redação ao seguinte dispositivo: \n \nArt',
       'Dê-se nova redação ao seguinte dispositivo: \n \nArt',
       'Dê-se nova redação ao seguinte dispositivo: \n \nArt',
       'Dê-se nova redação ao seguinte dispositivo: \n \nArt',
       'Dê-se nova redação ao seguinte dispositivo: \n \nAlt',
       'Dê-se nova redação ao seguinte dispositivo: \n \n“Ar',
       'Dê-se nova redação ao seguinte dispositivo: \n“Art.',
       'Dê-se nova redação ao seguinte dispositivo: \n \n“Ar',
       'Dê-se nova redação ao seguinte dispositivo: \n \n“Ar',
       'Dê-se nova redação ao seguinte dispositivo: \n \n“Ar',
       'Inclua-se o seguinte dispositivo: \n \n“Seção VIII -',
       'Dê-se nova redação aos seguintes dispositivos: \n \n',
       'Dê-se nova redação aos seguintes dispositivos: \n \n',
       'Dê-se nova redação aos seguintes dispositivos: \n \n',
       'Inclua-se o § 6º ao art. 105 do PLP nº 68/2024, co',
       'Exclua-se o § 7º do art. 103 do PLP nº 68/2024. \n ',
       'No artigo 307 do Projeto de Lei Complementar 68 de',
       'No anexo II do Projeto de Lei Complementar 68 de 2',
       'Art. 1º Suprima-se o art. o artigo 288 do Projeto ',
       'Insere os parágrafos 1º e 2º no artigo 290, do Pro',
       'Altere-se o § 1º do art. 246 do PLP nº 68/2024, co',
       'Altera o art. 11, que dispõe sobre as regras de de',
       'Alteração no Anexo I do PLP 68/24: \n \nANEXO I - PR',
       'Acrescente-se o parágrafo único ao art. 213 do PLP',
       'Alteração no Anexo VII do PLP 68/24: \n \nANEXO VII ',
       'Dê-se nova redação ao seguinte dispositivo: \n \nArt',
       'Inclua-se e ajuste-se os seguintes itens no Anexo ',
       'Inclua-se e ajuste-se os seguintes itens no Anexo ',
       '\nAcrescentem-se arts. 37-1 e 37-2 ao Projeto, com ',
       '\nDê-se nova redação ao inciso I do § 4º do art. 58',
       '\nPROJETO DE LEI COMPLEMENTAR Nº 68/2024\nEMENDA Nº ',
       'Art. 1º Altera o art. 134 do PLP 68/2024, adiciona',
       'Art. 1º Acrescenta-se os seguintes itens ao Anexo ',
       'Art. 1º Altera o inciso IV do art. 39 do Projeto d',
       'Art. 1º Alteram-se os artigos a seguir do Projeto ',
       'Art. 1º Alteram-se os artigos a seguir do Projeto ',
       'Dê-se aos artigos 320 e 321 do substitutivo do PLP'], dtype=object)

In [19]:
plp["texto_sem_cabecalho"] = plp.texto_sem_cabecalho.apply(remover_ementa)

#### Checagem da primeira palavra do texto da emenda

In [20]:
set(plp["texto_sem_cabecalho"].str.split().str[0].values)

{'(Do',
 '1)',
 'A',
 'ANEXO',
 'Acrescenta',
 'Acrescenta-se',
 'Acrescentam-se',
 'Acrescente',
 'Acrescente-se',
 'Acrescente-se,',
 'Acrescentem-se',
 'Acrescentem-se,',
 'Acresça-se',
 'Acresçam-se',
 'Ajuste-se',
 'Altera',
 'Altera-se',
 'Alteram-se',
 'Alteração',
 'Altere-se',
 'Altere-se,',
 'Alterem-se',
 'Anexo',
 'Art.',
 'Art.1º',
 'Art.283.................................................................................................................................',
 'Atribua-se',
 'Confira-se',
 'Determine-se',
 'Dá',
 'Dá-se',
 'Dê',
 'Dê-se',
 'Dêem-se',
 'EMENDA',
 'Exclua-se',
 'Excluam-se',
 'Fica',
 'Ficam',
 'Inclua-se',
 'Inclua-se,',
 'Incluam-se',
 'Inclui',
 'Inclui-se',
 'Inclusão',
 'Insere',
 'Insere-se',
 'Inserir',
 'Insira-se',
 'Insiram-se',
 'Item',
 'Modifica',
 'Modifica-se',
 'Modificação',
 'Modifique-se',
 'No',
 'O',
 'Os',
 'PROJETO',
 'Substitua-se',
 'Sugerimos',
 'Suprima-se',
 'Suprimam-se',
 'Suprimam–se',
 'São',
 'a)',
 '“Art.'}

In [21]:
palavras_suspeitas = ['(Do',
 #'1)',
 #'A',
 #'ANEXO',
 #'Anexo',
 'EMENDA',
 #'Item',
 #'No',
 #'O',
 #'Os',
'PROJETO',
 #'São',
 #'a)',
]

for palavra in palavras_suspeitas:
    s = plp[plp["texto_sem_cabecalho"].str.split().str[0] == palavra].texto.values
    print(f"{'-'*50}Palavra: {palavra}{'-'*50}")
    s = set([t[:400] for t in s])
    for texto in s:
        print(texto)
        print("===============================================")
    print("---------------------------------------------------------------------------------------------------")

--------------------------------------------------Palavra: (Do--------------------------------------------------
Gabinete do Senador Zequinha Marinho
EMENDA Nº
(ao PLP 68/2024)
(Do Sr. Senador Zequinha Marinho)
   Inclua-se os seguintes itens no Anexo IX do Projeto de Lei
Complementar nº 68 de 2024:

7
Inseticidas, fungicidas,
formicidas, herbicidas,
parasiticidas, germicidas,
acaricidas, nematicidas,
raticidas, desfolhantes,
dessecantes, espalhantes,
adesivos, estimuladores e
inibidores de c
===============================================
---------------------------------------------------------------------------------------------------
--------------------------------------------------Palavra: EMENDA--------------------------------------------------




SENADO FEDERAL
Gabinete do Senador Mecias de Jesus



Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabinete 02


EMENDA Nº             , DE 2024
(ao Projeto de Lei Complementar nº 68, de 2024)

EMENDA MODIFICATIVA
Inclua-se o §6º no artigo 23 e altere-se inciso IV do artigo 26 para incluir o §10º no
artigo 26 do PLP 68, de 2024, conferindo-lhes a
===============================================
Gabinete do Senador Jorge Seif
EMENDA Nº         - CCJ
(ao PLP 68/2024)
EMENDA Nº   - CCJ
(ao PLP 68/2024)
PROPOSTA DE EMENDA AO PLP Nº 68/2024
Institui o Imposto sobre Bens e Serviços - IBS, a Contribuição Social
sobre Bens e Serviços - CBS e o Imposto Seletivo - IS e dá outras providências.

EMENDA MODIFICATIVA Nº

Dê-se à alínea “b” do item I do artigo 411; ao § 2º do art.419; e ao caput
e §1
===============================================

EMENDA N° , de 2024 –
(ao PLP n° 68, de 2024)

EMENDA MODIFICATIVA


O art. 419, §1º, inciso II passa a constar com a seguinte redação:
“Art. 419. (...)
§1º. Aplicam-se alíquotas ad valorem cumuladas com alíquotas
específicas para:
(...)
II - bebidas alcoólicas, em que as alíquotas específicas devem
considerar o produto do teor alcoólico pelo volume dos produtos
e as alíquotas
===============================================




SENADO FEDERAL
Gabinete do Senador Mecias de Jesus



Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabinete 02


EMENDA Nº
(ao Projeto de Lei Complementar nº 68, de 2024)




EMENDA MODIFICATIVA


O Art. 450 do Projeto de Lei Complementar nº 68, de 2024, passa a vigorar com
a seguinte redação:

“Art. 450. A partir de 1º de janei
===============================================



EMENDA N° , de 2024 –
(ao PLP n° 68, de 2024)

EMENDA MODIFICATIVA

Migra os §§4º e 5º do artigo 420 para o artigo 419 ajustando sua redação e
inclui os §§8º a 13º no artigo 419:
“Art. 419.
(...)
§5º. As alíquotas do Imposto Seletivo incidente sobre bebidas
alcoólicas serão fixadas de forma escalonada, de modo a
incorporar, a partir de 2029 até 2033, progressivamente, o
difer
===============================================
Gabinete do Senador Dr. Hiran
EMENDA Nº         - CCJ
(ao PLP 68/2024)
EMENDA DE REDAÇÃO
Dê-se ao item 24 do Anexo III - Serviços de Saúde submetidos à redução
de 60% das alíquotas do IBS e da CBS do Projeto a seguinte redação:
ITEM
DESCRIÇAO DO SERVIÇO
NBS
...
...
...
24
Serviços de esterilização e
instrumentação cirúrgica
NBS 1.2301.99.00
...
...
...
JUSTIFICAÇÃO
A presente emenda visa corrigir,
===============================================
EMENDA Nº
(ao PLP 68/2024)
EMENDA SUPRESSIVA nº         , DE 2024.
Suprima-se a expressão "médicos veterinários" do inciso XIII do art.
122, suprima-se a palavra "humana" do art. 125, e altere-se o art. 236 e o Anexo
III.:


Art. 122.   (...)
XIII –   médicos veterinários   e zootecnistas;
Art. 125.   Ficam reduzidas em 60% (sessenta por cento) as alíquotas do IBS
e da CBS incidentes so
===============================================
EMENDA Nº
(ao PLP 68/2024)
EMENDA SUBSTITUTIVA
CAPÍTULO I
DAS DISPOSIÇÕES PRELIMINARES
Art.
1º.................................................................................................................................
..............................................................................................................................................
 § 1º Os três níveis da
===============================================
Gabinete do Senador Mecias de Jesus
EMENDA Nº
(ao PLP 68/2024)
EMENDA MODIFICATIVA

Art. 1º. Suprima-se o Parágrafo Único do art. 237 do Substitutivo ao
Projeto de Lei Complementar nº 68, de 2024.
Art. 2º. Acrescenta-se ao art. 136 do Projeto de Lei Complementar nº
68, de 2024, o inciso III, com o seguinte teor:
"Art. 136. ……………………………………………………………………………………
III – a prestação de serviço rel
===============================================
---------------------------------------------------------------------------------------------------
--------------------------------------------------Palavra: PROJETO--------------------------------------------------
Gabinete do Senador Zequinha Marinho
EMENDA Nº
(ao PLP 68/2024)
PROJETO DE LEI COMPLEMENTAR Nº 68/2024
EMENDA Nº _______, DE 2024
(Do Sr. Senador Zequinha Marinho)

Institui o Imposto sobre Bens e Serviços IBS, a Contribuição Social
sobre Bens e Serviços - CBS e o Imposto Seletivo - IS e dá outras providências.
 EMENDA
Art. 1º. Inclua-se os seguintes itens no Anexo IX do Projeto de Lei
C
===============================================
Gabinete do Senador Zequinha Marinho
EMENDA Nº
(ao PLP 68/2024)
PROJETO DE LEI COMPLEMENTAR Nº 68/2024
EMENDA Nº _______, DE 2024
(Do Sr. Senador Zequinha Marinho)

Institui o Imposto sobre Bens e Serviços IBS, a Contribuição Social
sobre Bens e Serviços - CBS e o Imposto Seletivo - IS e dá outras providências.
EMENDA
Art. 1º. Suprima-se o termo “bebidas açucaradas” e a NCM
2202.10.00 do
===============================================
Gabinete do Senador Zequinha Marinho
EMENDA Nº
(ao PLP 68/2024)
PROJETO DE LEI COMPLEMENTAR Nº 68/2024
EMENDA Nº _______, DE 2024
(Do Sr. Senador Zequinha Marinho)

Institui o Imposto sobre Bens e Serviços IBS, a Contribuição Social
sobre Bens e Serviços - CBS e o Imposto Seletivo - IS e dá outras providências.
 EMENDA
Art. 1º. Inclua-se e ajuste-se os seguintes itens no Anexo I do
Proje
===============================================
Gabinete do Senador Zequinha Marinho
EMENDA Nº
(ao PLP 68/2024)
PROJETO DE LEI COMPLEMENTAR Nº 68/2024
EMENDA Nº _______, DE 2024
(Do Sr. Senador  Zequinha Marinho)

Institui o Imposto sobre Bens e Serviços IBS, a Contribuição Social
sobre Bens e Serviços - CBS e o Imposto Seletivo - IS e dá outras providências.
 EMENDA
Art. 1º. Inclua-se e ajuste-se os seguintes itens no Anexo VII do
Pr
===============================================
---------------------------------------------------------------------------------------------------

##### Remover restante dos dados de cabeçalho

In [22]:
def remover_dados_restantes_cabecalho(texto):
    extrair_ate = [
        r"EMENDA SUPRESSIVA\s*n[º°o]?\s*,?\s*DE\s*2024\.?",
        r"EMENDA MODIFICATIVA Nº",
        r"EMENDA MODIFICATIVA",
        r"EMENDA SUBSTITUTIVA",
        r"EMENDA DE REDAÇÃO",
        r"\(Do Sr\. Senador Zequinha Marinho\)",
        r"\n\s*EMENDA\s*\n"
    ]
    
    pattern = re.compile(
        rf"^[\s\S]*?(?:{'|'.join(extrair_ate)})\s*\n*",
        flags=re.IGNORECASE
    )
    
    return pattern.sub('', texto, count=1)

In [23]:
plp[plp["texto_sem_cabecalho"].str.split().str[0].isin(palavras_suspeitas)]["texto_sem_cabecalho"]

196     \nEMENDA DE REDAÇÃO\nDê-se ao item 24 do Anexo...
201     \nPROJETO DE LEI COMPLEMENTAR Nº 68/2024\nEMEN...
212     \nPROJETO DE LEI COMPLEMENTAR Nº 68/2024\nEMEN...
224     \nPROJETO DE LEI COMPLEMENTAR Nº 68/2024\nEMEN...
235     \nPROJETO DE LEI COMPLEMENTAR Nº 68/2024\nEMEN...
538     \nEMENDA SUPRESSIVA nº         , DE 2024.\nSup...
1446    \nEMENDA MODIFICATIVA\n \nArt. 1º. Suprima-se ...
1522    \n(Do Sr. Senador Zequinha Marinho) \n   Inclu...
1580    \nEMENDA Nº   - CCJ\n(ao PLP 68/2024)\nPROPOST...
1653    \nEMENDA SUBSTITUTIVA\nCAPÍTULO I\nDAS DISPOSI...
1912     \n \nEMENDA MODIFICATIVA \n \nMigra os §§4º e...
1913     \n \nEMENDA MODIFICATIVA \n \n \nO art. 419, ...
2068    \nPROJETO DE LEI COMPLEMENTAR Nº 68/2024\nEMEN...
2221     \n \nEMENDA MODIFICATIVA \nInclua-se o §6º no...
2223     \n \n \n \n \nEMENDA MODIFICATIVA \n \n \nO A...
Name: texto_sem_cabecalho, dtype: object

In [24]:
mask = plp["texto_sem_cabecalho"].str.split().str[0].isin(palavras_suspeitas)

plp.loc[mask, "texto_sem_cabecalho"] = (
    plp.loc[mask, "texto_sem_cabecalho"]
       .apply(remover_dados_restantes_cabecalho)
)

In [25]:
plp.loc[mask].texto_sem_cabecalho

196     Dê-se ao item 24 do Anexo III - Serviços de Sa...
201     Institui o Imposto sobre Bens e Serviços IBS, ...
212     Institui o Imposto sobre Bens e Serviços IBS, ...
224     Institui o Imposto sobre Bens e Serviços IBS, ...
235     Institui o Imposto sobre Bens e Serviços IBS, ...
538     Suprima-se a expressão "médicos veterinários" ...
1446    Art. 1º. Suprima-se o Parágrafo Único do art. ...
1522    Inclua-se os seguintes itens no Anexo IX do Pr...
1580    Dê-se à alínea “b” do item I do artigo 411; ao...
1653    CAPÍTULO I\nDAS DISPOSIÇÕES PRELIMINARES\nArt....
1912    Migra os §§4º e 5º do artigo 420 para o artigo...
1913    O art. 419, §1º, inciso II passa a constar com...
2068    Art. 1º. Inclua-se e ajuste-se os seguintes it...
2221    Inclua-se o §6º no artigo 23 e altere-se incis...
2223    O Art. 450 do Projeto de Lei Complementar nº 6...
Name: texto_sem_cabecalho, dtype: object

In [26]:
set(plp["texto_sem_cabecalho"].str.split().str[0].values)

{'1)',
 'A',
 'ANEXO',
 'Acrescenta',
 'Acrescenta-se',
 'Acrescentam-se',
 'Acrescente',
 'Acrescente-se',
 'Acrescente-se,',
 'Acrescentem-se',
 'Acrescentem-se,',
 'Acresça-se',
 'Acresçam-se',
 'Ajuste-se',
 'Altera',
 'Altera-se',
 'Alteram-se',
 'Alteração',
 'Altere-se',
 'Altere-se,',
 'Alterem-se',
 'Anexo',
 'Art.',
 'Art.1º',
 'Art.283.................................................................................................................................',
 'Atribua-se',
 'CAPÍTULO',
 'Confira-se',
 'Determine-se',
 'Dá',
 'Dá-se',
 'Dê',
 'Dê-se',
 'Dêem-se',
 'Exclua-se',
 'Excluam-se',
 'Fica',
 'Ficam',
 'Inclua-se',
 'Inclua-se,',
 'Incluam-se',
 'Inclui',
 'Inclui-se',
 'Inclusão',
 'Insere',
 'Insere-se',
 'Inserir',
 'Insira-se',
 'Insiram-se',
 'Institui',
 'Item',
 'Migra',
 'Modifica',
 'Modifica-se',
 'Modificação',
 'Modifique-se',
 'No',
 'O',
 'Os',
 'Substitua-se',
 'Sugerimos',
 'Suprima-se',
 'Suprimam-se',
 'Suprimam–se',
 'São',
 'a)',
 '“Art.'}

### Remover dados do corpo

#### Remover gabinete

In [27]:
print(len(plp[plp.texto_sem_cabecalho.str.contains(r"Gabinete (?:d[oa]\s)?Sen", case=False)]))

100

In [28]:
trechos_com_gabinete = (
    plp.loc[
        plp["texto_sem_cabecalho"].str.contains("Gabinete (?:d[oa]\s)?Sen", na=False, case=False),
        "texto_sem_cabecalho"
    ]
    .str.extract(r"(.{0,20}Gabinete (?:d[oa]\s)?Sen.{0,20})", expand=False)
)

print(trechos_com_gabinete.tolist())

<>:3: SyntaxWarning: invalid escape sequence '\s'
<>:3: SyntaxWarning: invalid escape sequence '\s'
C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_21364\3161471891.py:3: SyntaxWarning: invalid escape sequence '\s'
  plp["texto_sem_cabecalho"].str.contains("Gabinete (?:d[oa]\s)?Sen", na=False, case=False),

['Gabinete Senador Carlos Portinho', 'Gabinete do Senador NELSINHO TRAD ', 'Gabinete do Senador NELSINHO TRAD ', 'Gabinete do Senador NELSINHO TRAD ', 'Gabinete do Senador NELSINHO TRAD ', 'Gabinete do Senador Jaime Bagattoli', 'Gabinete do Senador Jaime Bagattoli', 'Gabinete do Senador ESPERIDIÃO AMIN', 'Gabinete do Senador ESPERIDIÃO AMIN', 'Gabinete do Senador Jaime Bagattoli', 'Gabinete do Senador Jaime Bagattoli', 'Gabinete do Senador Jaime Bagattoli', 'Gabinete do Senador Ciro Nogueira (', 'Gabinete do Senador FLÁVIO ARNS ', 'Gabinete do Senador FLÁVIO ARNS ', 'Gabinete do Senador FLÁVIO ARNS ', 'Gabinete do Senador Fabiano Contara', 'Gabinete do Senador Fabiano Contara', 'Gabinete do Senador Fabiano Contara', 'Gabinete do Senador Beto Martins ', 'Gabinete do Senador Beto Martins ', 'Gabinete do Senador Beto Martins ', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', nan, nan, nan, 'Gabinete do Senador ESPERIDIÃO AMIN', 'Gabinete do Senador ESPERIDIÃO AMIN', 'Gabinete do Senador ESPERIDIÃO AMIN', 'Gabinete do Senador ESPERIDIÃO AMIN', 'Gabinete do Senador ESPERIDIÃO AMIN', 'Gabinete do Senador ESPERIDIÃO AMIN', 'Gabinete do Senador Fabiano Contara', 'Gabinete do Senador Alan Rick ', 'Gabinete do Senador Alan Rick ', 'Gabinete do Senador Alan Rick ', 'Gabinete do Senador Alan Rick ', 'Gabinete do Senador Alan Rick ', 'Gabinete do Senador Alan Rick ', 'Gabinete do Senador Hamilton Mourão', 'Gabinete do Senador Hamilton Mourão', 'Gabinete do Senador OMAR AZIZ ', 'Gabinete do Senador NELSINHO TRAD ', 'Gabinete do Senador NELSINHO TRAD ', 'Gabinete do Senador NELSINHO TRAD ', 'Gabinete do Senador NELSINHO TRAD ', 'Gabinete do Senador NELSINHO TRAD ', 'Gabinete do Senador NELSINHO TRAD ', 'Gabinete da Senadora Rosana Martine', 'Gabinete da Senadora Rosana Martine', 'Gabinete da Senadora Rosana Martine', 'Gabinete da Senadora Rosana Martine', 'Gabinete da Senadora Rosana Martine', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador Mecias de Jesus', 'Gabinete do Senador ESPERIDIÃO AMIN', 'Gabinete do Senador ESPERIDIÃO AMIN', 'Gabinete do Senador ESPERIDIÃO AMIN', 'Gabinete do Senador ESPERIDIÃO AMIN', 'Gabinete do Senador ESPERIDIÃO AMIN', 'Gabinete do Senador ESPERIDIÃO AMIN']

In [29]:
mask = plp["texto_sem_cabecalho"].str.contains(r"Gabinete (?:d[oa]\s)?Sen", na=False, case=False)

# linhas com "Gabinete d"
plp.loc[mask, "texto_preprocessado"] = (
    plp.loc[mask, "texto_sem_cabecalho"]
       .apply(remove_gabinete)
)

# linhas sem "Gabinete d"
plp.loc[~mask, "texto_preprocessado"] = (
    plp.loc[~mask, "texto_sem_cabecalho"]
)

trechos_restantes = (
    plp.loc[
        plp["texto_preprocessado"].str.contains(r"Gabinete (?:d[oa]\s)?Sen", na=False, case=False),
        "texto_preprocessado"
    ]
    .str.findall(r".{0,20}Gabinete (?:d[oa]\s)?Sen.{0,20}")
)

print(trechos_restantes.tolist())

[]

#### Tag do LexEdit

In [30]:
plp.head().texto_preprocessado

0    \nSuprimam-se os §§ 1° e 2° do art. 384 do PLP...
1    \nInclua-se o §6º no art. 23 e dê-se a seguint...
2    \nAcrescenta o inciso VIII ao §1º do artigo 40...
3    \nAcrescente-se inciso VI ao parágrafo único d...
4    \nDê-se ao § 7º do art. 163 do Projeto a segui...
Name: texto_preprocessado, dtype: object

In [31]:
print(len(plp[plp.texto_sem_cabecalho.str.contains("SF/")]))

1998

In [32]:
plp[plp.texto_sem_cabecalho.str.contains("SF/")].texto_sem_cabecalho.values[0]

'\nSuprimam-se os §§ 1° e 2° do art. 384 do PLP nº 68, de 2024,\nrenumerando-se os demais, e inclua-se a alínea “d” ao inciso IV do caput desse\ndispositivo, com a seguinte redação:\n“Art. 384.............................................................................\n............................................................................................\nIV –...................................................................................\n............................................................................................\nd) recolhimento a fundo estadual ou distrital como contrapartida para\nfruição de incentivo ou benefício ﬁscal.\n............................................................................................”\nJUSTIFICAÇÃO\nEsta Emenda visa corrigir a distorção aprovada pela Câmara dos\nDeputados que não considera a contribuição aos fundos estaduais e distrital como\numa condição onerosa, o que implica subtrair do contribuinte o direito de se\nressarcir de perdas decorrentes da redução gradual do ICMS no período de 2029 a\n3032, conforme previsto na Emenda Constitucional nº 132, de 2023.\nCaso seja mantida a redação da Câmara, estar-se-á impondo\ntratamento diferenciado aos contribuintes contemplados com benefício\nautorizado com fundamento na Lei Complementar nº 160, de 7 de agosto de 2017,\nSF/24205.71226-78  (LexEdit*)\nAssinado eletronicamente, por Sen. Esperidião Amin\nPara verificar as assinaturas, acesse https://legis.senado.gov.br/autenticadoc-legis/9962863790\n00001-U\nPLP 68/2024\numa vez que a contribuição ao fundo representa condição expressa na legislação\nestadual ou distrital para concessão e usufruto do benefício.\nCabe, assim, explicitar na lei que as contribuições aos fundos\nvinculados ao ICMS devem ser consideradas “condição”, o que preenche um dos\nrequisitos para caracterizar o conceito de onerosidade.\nConvicto da importância desta Emenda, pedimos o apoio de nossos\nPares.\nSala da comissão, 9 de agosto de 2024.\nSenador Esperidião Amin\n(PP - SC)\nSF/24205.71226-78  (LexEdit*)\nAssinado eletronicamente, por Sen. Esperidião Amin\nPara verificar as assinaturas, acesse https://legis.senado.gov.br/autenticadoc-legis/9962863790\n'

In [33]:
plp["texto_preprocessado"] = plp.texto_preprocessado.apply(remove_lexedit_id)

In [34]:
print(len(plp[plp.texto_preprocessado.str.contains(r"SF/\d")]))

0

#### Assinatura Digital

In [35]:
print(len(plp[plp.texto_preprocessado.str.contains("Assinado eletronicamente")]))

1907

In [36]:
plp["texto_preprocessado"] = plp.texto_preprocessado.apply(remove_digital_signature)

In [37]:
print(len(plp[plp.texto_preprocessado.str.contains("Assinado eletronicamente")]))

0

#### Endereço

In [38]:
plp[plp.texto_preprocessado.str.contains("Praça|CEP|Ala|Gabinete")].texto_preprocessado

2       Acrescenta o inciso VIII ao §1º do artigo 406 ...
27      Art. 1º. Suprima-se o artigo 35 do Projeto de ...
28      Art. 1º. Adicione-se o seguinte dispositivo do...
29      Art. 1º. Adicione-se o seguinte dispositivo do...
30      Art. 1º. Adicione-se o seguinte dispositivo do...
                              ...
2225    Dê-se ao artigo 280, do Projeto de Lei Complem...
2226    Dê-se ao artigo 278, do Projeto de Lei Complem...
2227    Inclua-se o art. 248-A no PLP 68, de 2024, com...
2229    Inclua-se o art. 253-A no PLP 68, de 2024, com...
2230    Altera-se a redação do caput do art. 257 do PL...
Name: texto_preprocessado, Length: 108, dtype: object

In [39]:
trechos_com_endereco = (
    plp.loc[
        plp["texto_preprocessado"].str.contains(r"Praça\s|CEP\s|Ala\s|Gabinete\s", na=False),
        "texto_preprocessado"
    ]
    # Regex atualizada que aceita dinamicamente os dois casos
    .str.extractall(r"([\s\S]{0,70}(Praça\s|CEP\s|Ala\s|Gabinete\s)[\s\S]{0,70})")
)

print(trechos_com_endereco[0].tolist())

['alados na referida Região. \n\n01022-U\nPLP 68/2024\n \n \nSenado Federal – Praça dos Três Poderes – Anexo I – 24º andar – CEP 70165-900 – Brasília DF \n', ' das empresas exportadoras \n\n01023-U\nPLP 68/2024\n \n \nSenado Federal – Praça dos Três Poderes – Anexo I – 24º andar – CEP 70165-900 – Brasília DF \n', ' área de livre comércio de \n\n01024-U\nPLP 68/2024\n \n \nSenado Federal – Praça dos Três Poderes – Anexo I – 24º andar – CEP 70165-900 – Brasília DF \n', 'rança jurídica, contábil e \n\n01025-U\nPLP 68/2024\n \n \nSenado Federal – Praça dos Três Poderes – Anexo I – 24º andar – CEP 70165-900 – Brasília DF \n', 'stitucional. \n\n01068-U\nPLP 68/2024\n \n \n \n \n \nSenado Federal –Anexo 2, Ala Teotônio Vilela, Gabinete 23 - Praça dos Três Poderes – CEP 70165-900 ', ' \neconômica. \n\n01069-U\nPLP 68/2024\n \n \n \n \n \nSenado Federal –Anexo 2, Ala Teotônio Vilela, Gabinete 23 - Praça dos Três Poderes – CEP 70165-900 ', 'letivos de trabalho. \n\n01072-U\nPLP 68/2024Senado Federal – Anexo II – Ala Senador Nilo Coelho – Gabinete 2 \n70165-900 – Brasília – DF \nTelefone:', 'e \nde inteligência;  \n\n01073-U\nPLP 68/2024Senado Federal – Anexo II – Ala Senador Nilo Coelho – Gabinete 2 \n70165-900 – Brasília – DF \nTelefone:', 'a zero, as alíquotas do IBS e da CBS:  \n \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – Gabinete 2 \n70165-900 – Brasília – DF \nTelefone:', 'ento o RETID.” \n \n \n \n \n \nJUSTIFICAÇÃO \n \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – Gabinete 2 \n70165-900 – Brasília – DF \nTelefone:', 'co em caráter econômico-social. Para que \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – Gabinete 2 \n70165-900 – Brasília – DF \nTelefone:', ' \n   \n \n \n \n \n\n01078-U\nPLP 68/2024\n \n \n \n \n \nSenado Federal –Anexo 2, Ala Teotônio Vilela, Gabinete 23 - Praça dos Três Poderes – CEP 70165-900 ', 'eneficiados. \n\n01080-U\nPLP 68/2024\n \n \n \n \n \nSenado Federal –Anexo 2, Ala Teotônio Vilela, Gabinete 23 - Praça dos Três Poderes – CEP 70165-900 ', 'cado ilícito no \nBrasil”, p. 18. \n\n \n \n \n \n \nSenado Federal –Anexo 2, Ala Teotônio Vilela, Gabinete 23 - Praça dos Três Poderes – CEP 70165-900 ', 'cally%20empowered)%20to%206%25.  \n\n \n \n \n \n \nSenado Federal –Anexo 2, Ala Teotônio Vilela, Gabinete 23 - Praça dos Três Poderes – CEP 70165-900 ', 'l para todos \n\n01081-U\nPLP 68/2024\n \n \n \n \n \nSenado Federal –Anexo 2, Ala Teotônio Vilela, Gabinete 23 - Praça dos Três Poderes – CEP 70165-900 ', 'ra os animais de \nestimação. \n \n \n\n \n \n \n \n \nSenado Federal –Anexo 2, Ala Teotônio Vilela, Gabinete 23 - Praça dos Três Poderes – CEP 70165-900 ', '84\nPLP 68/2024\n \n(PP/PI) \n \n \n \nSenado Federal – Anexo I – 3º Andar – Praça dos Três Poderes – CEP 70165-900 – Brasília DF  \nTelefone: +55 (61) 33', 'ao Ministério do Desenvolvimento, Indústria, Comércio e Serviços\ne ao Gabinete de Segurança Institucional da Presidência da República, revisarão,\na c', 'ao Ministério do Desenvolvimento, Indústria, Comércio e Serviços\ne ao Gabinete de Segurança Institucional da Presidência da República, revisarão,\na c', 'es do beneficiamento, \n\n00571-U\nPLP 68/2024\n \n2 \n \n \nSenado Federal – Ala Dinarte Mariz, gabinete 2/3 – Brasília/DF – CEP 70.165-900 \nFone: (61)', ' fase seguinte da circulação do bem. Esta \n\n \n3 \n \n \nSenado Federal – Ala Dinarte Mariz, gabinete 2/3 – Brasília/DF – CEP 70.165-900 \nFone: (61)', ' do ano subsequente;  \n\n00572-U\nPLP 68/2024\n \n2 \n \n \nSenado Federal – Ala Dinarte Mariz, gabinete 2/3 – Brasília/DF – CEP 70.165-900 \nFone: (61)', ' que tal fornecimento \n\n00573-U\nPLP 68/2024\n \n2 \n \n \nSenado Federal – Ala Dinarte Mariz, gabinete 2/3 – Brasília/DF – CEP 70.165-900 \nFone: (61)', ' outros \n00585-U\nPLP 68/2024\n \nSENADO FEDERAL – | Anexo I, 13 andar | CEP 70165-900 | Brasília DF \nTelefone: +55 (61) 3303-9049 |  E-mail: sen.f', 'sistemas alimentares. Segundo \nSENADO FEDERAL – | Anexo I, 13 andar | CEP 70165-900 | Brasília DF \nTelefone: +55 (61) 3303-9049 |  E-mail: sen.f', 'ara um sistema alimentar mais \nSENADO FEDERAL – | Anexo I, 13 andar | CEP 70165-900 | Brasília DF \nTelefone: +55 (61) 3303-9049 |  E-mail: sen.f', 'esporto \n00586-U\nPLP 68/2024\n \nSENADO FEDERAL – | Anexo I, 13 andar | CEP 70165-900 | Brasília DF \nTelefone: +55 (61) 3303-9049 |  E-mail: sen.f', 'do ilícito no Brasil”, p. 18. \nSENADO FEDERAL – | Anexo I, 13 andar | CEP 70165-900 | Brasília DF \nTelefone: +55 (61) 3303-9049 |  E-mail: sen.f', 'iew.com/incentives/spain-169  \nSENADO FEDERAL – | Anexo I, 13 andar | CEP 70165-900 | Brasília DF \nTelefone: +55 (61) 3303-9049 |  E-mail: sen.f', 'igo.  \n \n00588-U\nPLP 68/2024\n \nSENADO FEDERAL – | Anexo I, 13 andar | CEP 70165-900 | Brasília DF \nTelefone: +55 (61) 3303-9049 |  E-mail: sen.f', 'prejuízo ao consumidor final. \nSENADO FEDERAL – | Anexo I, 13 andar | CEP 70165-900 | Brasília DF \nTelefone: +55 (61) 3303-9049 |  E-mail: sen.f', ', preservando-se a geração de \nSENADO FEDERAL – | Anexo I, 13 andar | CEP 70165-900 | Brasília DF \nTelefone: +55 (61) 3303-9049 |  E-mail: sen.f', 'onal, devidamente indicados no documento fiscal. \n\n00627-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', ' econômica; b) de modo habitual ou em volume que \n\n00628-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', ', essencial para a oferta de moradias acessíveis e para o aumento da \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'loads/2020/06/IBS_Indústria-de-Construção_v2.pdf \n\n00629-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', ' que aprova o \nCódigo Português do Imposto Acrescentado (“CIVA/PT”). \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'Técnica do Ministério da Fazenda, que incluiu as \n\n00630-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 's em regime específico de caráter técnico, conforme texto \nabaixo: \n \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'Diretiva EU IVA \nnº 112”). Art. 137, “d”, da Diretiva EU IVA nº 112. \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', ' que aprova o \nCódigo Português do Imposto Acrescentado (“CIVA/PT”). \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'o definitivo, não gerando, em qualquer hipótese, \n\n00631-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'itas financeiras e variações monetárias \ndecorrentes desta operação. \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'itas financeiras e variações \nmonetárias decorrentes desta operação. \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'lementação do IBS durante o \nperíodo de transição da seguinte forma: \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'ido o regime não-cumulativo de PIS e COFINS, foi preservado o regime \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'sumido é realizada pelo regime de caixa, ou seja, os tributos apenas \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'plementar nº 68, de 2024. \n \n \nSala das Sessões,  de agosto de 2024. \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', ', no que couber, o disposto nos artigos 28 a 37; \n\n00632-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'e é a não cumulatividade. \n \nSala das Sessões,  de agosto de 2024. \n \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'as mesmas áreas, afastando novos \ninvestimentos. \n\n00633-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'ntos e aumentar a atratividade dos destinos \nturísticos brasileiros. \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'é muito elevado no Brasil. Atualmente, a taxa de \n\n00636-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'a redução de prazo pode alcançar um número \nlimitado de empresas.  \n \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'ntabilmente registrado como ativo imobilizado. \n \n\n00637-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', ' do montante equivalente ao saldo de credor \n\n00638-U\nPLP 68/2024\n \n \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'o, e que o regulamento não irá prever requisitos \n\n00639-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'lo Fundo de Compensação de Benefícios Fiscais ou \n\n00640-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'e garantir a participação dos Estados e da União \n\n00641-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'las guardas municipais, pela Agência Brasileira de Inteligência, pelo Gabinete\nde Segurança Institucional da Presidência da República, pelos tribunai', 'o \nfilé com alíquota zero. \n \n\n00692-U\nPLP 68/2024\n \nSenado Federal – Praça dos Três Poderes – Anexo II – Ala Teotônio Vilela – Gabinete 17 – 70.1', 'a promoção da saúde pública. \n\n00694-U\nPLP 68/2024\n \nSenado Federal – Praça dos Três Poderes – Anexo II – Ala Teotônio Vilela – Gabinete 17 – 70.1', '0 e \n1604.20.30 da NCM/SH; \n \n\n00695-U\nPLP 68/2024\n \nSenado Federal – Praça dos Três Poderes – Anexo II – Ala Teotônio Vilela – Gabinete 17 – 70.1', '. \n \n \n \n \n\n00696-U\nPLP 68/2024Brasília: \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – \nGabinete 2  \n70165-900 – Brasília – DF \nTelefon', 's-governamentais-consolidadas \nBrasília: \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – \nGabinete 2  \n70165-900 – Brasília – DF \nTelefon', '-28.pdf, acesso em 15.mai.24. \nBrasília: \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – \nGabinete 2  \n70165-900 – Brasília – DF \nTelefon', '00; 27.08 \n\n00697-U\nPLP 68/2024Brasília: \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – \nGabinete 2  \n70165-900 – Brasília – DF \nTelefon', 'cional nº \n\n00698-U\nPLP 68/2024Brasília: \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – \nGabinete 2  \n70165-900 – Brasília – DF \nTelefon', 'r. E vale \n\n00699-U\nPLP 68/2024Brasília: \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – \nGabinete 2  \n70165-900 – Brasília – DF \nTelefon', 'úmero \nlimitado de empresas.  \nBrasília: \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – \nGabinete 2  \n70165-900 – Brasília – DF \nTelefon', 'equisitos \n\n00700-U\nPLP 68/2024Brasília: \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – \nGabinete 2  \n70165-900 – Brasília – DF \nTelefon', ' DO IBS E DA CBS \n \n \n\n00701-U\nPLP 68/2024Senado Federal – Anexo II – Ala Senador Nilo Coelho – Gabinete 2 \n70165-900 – Brasília – DF \nTelefone:', 'a e \ntecnologia nucleares. \n1.1201.33.00 \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – Gabinete 2 \n70165-900 – Brasília – DF \nTelefone:', '\n39.12 \n2.16 \nEscudos Balísticos. \n39.26 \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – Gabinete 2 \n70165-900 – Brasília – DF \nTelefone:', 's compressores, \nautopropulsados. \n84.29 \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – Gabinete 2 \n70165-900 – Brasília – DF \nTelefone:', 'MCA \nutilizados \nem \nembarcações. \n85.02 \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – Gabinete 2 \n70165-900 – Brasília – DF \nTelefone:', 'e rádio detecção e rádio sondagem \n85.26 \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – Gabinete 2 \n70165-900 – Brasília – DF \nTelefone:', ' \n87.05 \n87.08 \n87.09 \n8710.00.00 \n87.16 \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – Gabinete 2 \n70165-900 – Brasília – DF \nTelefone:', ' \n89.03 \n8904.00.00 \n89.05 \n89.06 \n89.07 \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – Gabinete 2 \n70165-900 – Brasília – DF \nTelefone:', '.00 \n93.03 \n9304.00 \n93.05 \n93.06 \n93.07 \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – Gabinete 2 \n70165-900 – Brasília – DF \nTelefone:', 'ehicle – \nDPV ou scooter). \n90.20 \n95.06 \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – Gabinete 2 \n70165-900 – Brasília – DF \nTelefone:', 'a Nacional de Exportação e Importação de \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – Gabinete 2 \n70165-900 – Brasília – DF \nTelefone:', 'ção da alíquota geral em duas vertentes: \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – Gabinete 2 \n70165-900 – Brasília – DF \nTelefone:', 'ca, Industrial e Comercial (PComTIC), da \nSenado Federal – Anexo II – Ala Senador Nilo Coelho – Gabinete 2 \n70165-900 – Brasília – DF \nTelefone:', 'u seja, não empregados). \n \n\n00893-U\nPLP 68/2024\n \n \nSenado Federal – Praça dos Três Poderes – Anexo I – 24º andar – CEP 70165-900 – Brasília DF \n', 'sso da população à saúde.  \n\n00894-U\nPLP 68/2024\n \n \nSenado Federal – Praça dos Três Poderes – Anexo I – 24º andar – CEP 70165-900 – Brasília DF \n', 'ecialistas/. Acesso em: [03 de julho de 2024]. \n\n \n \nSenado Federal – Praça dos Três Poderes – Anexo I – 24º andar – CEP 70165-900 – Brasília DF \n', '5% deste mercado no país.  \n\n00895-U\nPLP 68/2024\n \n \nSenado Federal – Praça dos Três Poderes – Anexo I – 24º andar – CEP 70165-900 – Brasília DF \n', 'o apoio à presente emenda. \n\n00896-U\nPLP 68/2024\n \n \nSenado Federal – Praça dos Três Poderes – Anexo I – 24º andar – CEP 70165-900 – Brasília DF \n', 'spositivos não listados no \n\n00897-U\nPLP 68/2024\n \n \nSenado Federal – Praça dos Três Poderes – Anexo I – 24º andar – CEP 70165-900 – Brasília DF \n', 'ra executar suas operações de alto rendimento. \n\n \n \nSenado Federal – Praça dos Três Poderes – Anexo I – 24º andar – CEP 70165-900 – Brasília DF \n', '........................ \n \n\n00898-U\nPLP 68/2024\n \n \nSenado Federal – Praça dos Três Poderes – Anexo I – 24º andar – CEP 70165-900 – Brasília DF \n', 'gulamentação \ne a interpretação da legislação. \n\n \n \nSenado Federal – Praça dos Três Poderes – Anexo I – 24º andar – CEP 70165-900 – Brasília DF \n', 'ntarão com a participação de representantes da \n\n \n \nSenado Federal – Praça dos Três Poderes – Anexo I – 24º andar – CEP 70165-900 – Brasília DF \n', 'stas em Lei Complementar. \n\n00918-U\nPLP 68/2024\n2 \n \nSenado Federal – Praça dos Três Poderes – CEP 70165-900 – Brasília DF  \nO que se busca com re', 'ional, que, nos termos do \n\n00919-U\nPLP 68/2024\n2 \n \nSenado Federal – Praça dos Três Poderes – CEP 70165-900 – Brasília DF  \nart. 146, tem exatame', ' para fins de IBS e CBS.  \n\n00920-U\nPLP 68/2024\n2 \n \nSenado Federal – Praça dos Três Poderes – CEP 70165-900 – Brasília DF  \nNo entanto, há constr', 'em finalidade lucrativa.  \n\n00921-U\nPLP 68/2024\n2 \n \nSenado Federal – Praça dos Três Poderes – CEP 70165-900 – Brasília DF  \nAtualmente, tais tipo', 'na Constituição Federal.  \n\n00922-U\nPLP 68/2024\n2 \n \nSenado Federal – Praça dos Três Poderes – CEP 70165-900 – Brasília DF  \nA progressividade das', 'enda. \n \n \nSala das Sessões,  de agosto de 2024. \n\n00949-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'enda. \n \nSala das Sessões,  de agosto de 2024. \n \n\n00950-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', '; 27.02; \n2703.00.00; 2704.00; 2706.00.00; 27.08 \n\n00952-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', ' com energia elétrica e com \ntelecomunicações”.  \n\n00953-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', ' \ndaquele que trata dos demais bens minerais.  \n \n\n00955-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 's nobres pares na aprovação da \npresente emenda. \n\n00957-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'bens aplicados no processo de industrialização.  \n\n00958-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'iços destinados ao processo de industrialização, \n\n00959-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'S e da CBS prevista no \ncaput aplica-se também:  \n\n00963-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', ' \nestabelecimento industrial ou da pessoa jurídica a ele equiparado, \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'ncial de Projetos Navais (EMGEPRON), empresa pública federal, e cuja \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', ' necessários à fabricação, \nmanutenção e reparo dos bens de defesa.  \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'ém representa um meio tradicional de obtenção de \n\n00964-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'lor da locação para que não houvesse aumento substancial \nda carga.  \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', ' investido, seja por meio de juros ou aluguéis, sendo que no sistema \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'eceita do contribuinte é um percentual que incide sobre o \naluguel.  \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'lo Governo Federal em garantir que os incentivos \n\n00965-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'o o mercado de créditos de carbono no \nBrasil. \n \n\n00966-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'aprovação desta Emenda. \n \n \nSala das Sessões,  de agosto de 2024. \n \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'enefícios Fiscais ou Financeiro-Fiscais do ICMS. \n\n00967-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', '.........................................” \n \n \n \n\n00968-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'entos e importações e pela implementação do princípio do destino.” \n \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'os regulamentos feitos sob esta Lei que são aplicáveis \naos bens;” \n \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'dos, ou colocados em um navio ou \naeronave de viagem internacional.” \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'BS/CBS, pode criar distorções no mercado, afetar \n\n00970-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'anteriores à venda e ao recolhimento do tributo. \n\n00971-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'pecífica, de acordo com as regras deste artigo.  \n\n00972-U\nPLP 68/2024Praça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'de \nativos virtuais no regime específico de “serviços financeiros”.  \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', '  \nSala das Sessões,  de agosto de 2024. \n \nSenador Mecias de Jesus  \nPraça dos Três Poderes – Senado Federal – Anexo II – Ala Ruy Carneiro – Gabi', 'r créditos desses tributos com base no valor das \n\n00973-U\nPLP 68/2024Praça dos Três Poderes – Senado Fe

In [40]:
plp["texto_preprocessado"] = plp.texto_preprocessado.apply(remove_address)

In [41]:
trechos_com_endereco = (
    plp.loc[
        plp["texto_preprocessado"].str.contains(r"Praça\s|CEP\s|Ala\s|Gabinete\s", na=False),
        "texto_preprocessado"
    ]
    # Regex atualizada que aceita dinamicamente os dois casos
    .str.extractall(r"([\s\S]{0,70}(Praça\s|CEP\s|Ala\s|Gabinete\s)[\s\S]{0,70})")
)

print(trechos_com_endereco[0].tolist())

['ao Ministério do Desenvolvimento, Indústria, Comércio e Serviços\ne ao Gabinete de Segurança Institucional da Presidência da República, revisarão,\na c', 'ao Ministério do Desenvolvimento, Indústria, Comércio e Serviços\ne ao Gabinete de Segurança Institucional da Presidência da República, revisarão,\na c', 'las guardas municipais, pela Agência Brasileira de Inteligência, pelo Gabinete\nde Segurança Institucional da Presidência da República, pelos tribunai']

#### Remove número da emenda

In [42]:
plp["texto_preprocessado"] = plp.texto_preprocessado.apply(remove_num_emenda)

### Remover justificativa

In [43]:
def extract_until_any(texto, stop_words):
    if not texto:
        return texto
    
    # Primeiro passo: padronizar espaçamentos e remover quebras de linhas do PDF
    # Isso une palavras como "JUSTIFICAÇÃ\nO" caso apareçam no resto da base
    texto_normalizado = re.sub(r'(\w+)-\n\s*(\w+)', r'\1\2', texto)
    texto_normalizado = texto_normalizado.replace("JUSTIFICAÇÃ\nO", "JUSTIFICAÇÃO")
    texto_normalizado = texto_normalizado.replace("JUSTIFICAT\nIVA", "JUSTIFICATIVA")
    
    # Criamos um padrão que busca as palavras inteiras (\b) independente de estarem no início da linha
    # O [| ]*? serve para engolir aquela barra vertical " | JUSTIFICAÇÃO" que aparece no texto 5
    padrao = r"[| ]*?\b(?:" + "|".join([re.escape(word) for word in stop_words]) + r")\b"
    
    # Compilamos apenas com IGNORECASE (não precisamos de MULTILINE aqui)
    regex = re.compile(padrao, re.IGNORECASE)
    
    match = regex.search(texto_normalizado)
    
    if match:
        # Corta exatamente antes da palavra de parada (ou antes dos espaços/barras que a antecedem)
        return texto_normalizado[:match.start()].strip()
    
    return texto_normalizado

In [44]:
import re

# 1. Sua lista de variações original
just_variacoes = ["justificação", "justificativa", "j u s t i f i c a ç ã o", "j u s t i f i c a ç ã", "JUSTIFICAÇÃ\nO"]

# 2. Cria a regex dinamicamente colocando ^\s* no início de cada alternativa
# Isso vai gerar: ^\s*justificação|^\s*justificativa|^\s*j\ u\ s...
padrao_dinamico = "|".join([rf"^\s*{re.escape(word)}" for word in just_variacoes])

# 3. Compila com as flags de linha e caixa alta/baixa
regex_validacao = re.compile(padrao_dinamico, re.IGNORECASE | re.MULTILINE)

# 4. Seu loop de teste rodando no que a função antiga 'extract_until_any' gerou:
for idx, texto_filtrado in enumerate(plp.texto_preprocessado.apply(lambda x: extract_until_any(x, just_variacoes))):
    
    # Se a regex achar alguma das palavras iniciando uma linha no texto que deveria estar limpo:
    if regex_validacao.search(texto_filtrado):
        print(f"❌ Erro na PEC {idx}: Uma justificativa ainda foi encontrada no texto cortado!")
    else:
        print(f"✅ PEC {idx}: Passou no teste.")

✅ PEC 0: Passou no teste.
✅ PEC 1: Passou no teste.
✅ PEC 2: Passou no teste.
✅ PEC 3: Passou no teste.
✅ PEC 4: Passou no teste.
✅ PEC 5: Passou no teste.
✅ PEC 6: Passou no teste.
✅ PEC 7: Passou no teste.
✅ PEC 8: Passou no teste.
✅ PEC 9: Passou no teste.
✅ PEC 10: Passou no teste.
✅ PEC 11: Passou no teste.
✅ PEC 12: Passou no teste.
✅ PEC 13: Passou no teste.
✅ PEC 14: Passou no teste.
✅ PEC 15: Passou no teste.
✅ PEC 16: Passou no teste.
✅ PEC 17: Passou no teste.
✅ PEC 18: Passou no teste.
✅ PEC 19: Passou no teste.
✅ PEC 20: Passou no teste.
✅ PEC 21: Passou no teste.
✅ PEC 22: Passou no teste.
✅ PEC 23: Passou no teste.
✅ PEC 24: Passou no teste.
✅ PEC 25: Passou no teste.
✅ PEC 26: Passou no teste.
✅ PEC 27: Passou no teste.
✅ PEC 28: Passou no teste.
✅ PEC 29: Passou no teste.
✅ PEC 30: Passou no teste.
✅ PEC 31: Passou no teste.
✅ PEC 32: Passou no teste.
✅ PEC 33: Passou no teste.
✅ PEC 34: Passou no teste.
✅ PEC 35: Passou no teste.
✅ PEC 36: Passou no teste.
✅ PEC 37: Passou no teste.
✅ PEC 38: Passou no teste.
✅ PEC 39: Passou no teste.
✅ PEC 40: Passou no teste.
✅ PEC 41: Passou no teste.
✅ PEC 42: Passou no teste.
✅ PEC 43: Passou no teste.
✅ PEC 44: Passou no teste.
✅ PEC 45: Passou no teste.
✅ PEC 46: Passou no teste.
✅ PEC 47: Passou no teste.
✅ PEC 48: Passou no teste.
✅ PEC 49: Passou no teste.
✅ PEC 50: Passou no teste.
✅ PEC 51: Passou no teste.
✅ PEC 52: Passou no teste.
✅ PEC 53: Passou no teste.
✅ PEC 54: Passou no teste.
✅ PEC 55: Passou no teste.
✅ PEC 56: Passou no teste.
✅ PEC 57: Passou no teste.
✅ PEC 58: Passou no teste.
✅ PEC 59: Passou no teste.
✅ PEC 60: Passou no teste.
✅ PEC 61: Passou no teste.
✅ PEC 62: Passou no teste.
✅ PEC 63: Passou no teste.
✅ PEC 64: Passou no teste.
✅ PEC 65: Passou no teste.
✅ PEC 66: Passou no teste.
✅ PEC 67: Passou no teste.
✅ PEC 68: Passou no teste.
✅ PEC 69: Passou no teste.
✅ PEC 70: Passou no teste.
✅ PEC 71: Passou no teste.
✅ PEC 72: Passou no teste.
✅ PEC 73: Passou no teste.
✅ PEC 74: Passou no teste.
✅ PEC 75: Passou no teste.
✅ PEC 76: Passou no teste.
✅ PEC 77: Passou no teste.
✅ PEC 78: Passou no teste.
✅ PEC 79: Passou no teste.
✅ PEC 80: Passou no teste.
✅ PEC 81: Passou no teste.
✅ PEC 82: Passou no teste.
✅ PEC 83: Passou no teste.
✅ PEC 84: Passou no teste.
✅ PEC 85: Passou no teste.
✅ PEC 86: Passou no teste.
✅ PEC 87: Passou no teste.
✅ PEC 88: Passou no teste.
✅ PEC 89: Passou no teste.
✅ PEC 90: Passou no teste.
✅ PEC 91: Passou no teste.
✅ PEC 92: Passou no teste.
✅ PEC 93: Passou no teste.
✅ PEC 94: Passou no teste.
✅ PEC 95: Passou no teste.
✅ PEC 96: Passou no teste.
✅ PEC 97: Passou no teste.
✅ PEC 98: Passou no teste.
✅ PEC 99: Passou no teste.
✅ PEC 100: Passou no teste.
✅ PEC 101: Passou no teste.
✅ PEC 102: Passou no teste.
✅ PEC 103: Passou no teste.
✅ PEC 104: Passou no teste.
✅ PEC 105: Passou no teste.
✅ PEC 106: Passou no teste.
✅ PEC 107: Passou no teste.
✅ PEC 108: Passou no teste.
✅ PEC 109: Passou no teste.
✅ PEC 110: Passou no teste.
✅ PEC 111: Passou no teste.
✅ PEC 112: Passou no teste.
✅ PEC 113: Passou no teste.
✅ PEC 114: Passou no teste.
✅ PEC 115: Passou no teste.
✅ PEC 116: Passou no teste.
✅ PEC 117: Passou no teste.
✅ PEC 118: Passou no teste.
✅ PEC 119: Passou no teste.
✅ PEC 120: Passou no teste.
✅ PEC 121: Passou no teste.
✅ PEC 122: Passou no teste.
✅ PEC 123: Passou no teste.
✅ PEC 124: Passou no teste.
✅ PEC 125: Passou no teste.
✅ PEC 126: Passou no teste.
✅ PEC 127: Passou no teste.
✅ PEC 128: Passou no teste.
✅ PEC 129: Passou no teste.
✅ PEC 130: Passou no teste.
✅ PEC 131: Passou no teste.
✅ PEC 132: Passou no teste.
✅ PEC 133: Passou no teste.
✅ PEC 134: Passou no teste.
✅ PEC 135: Passou no teste.
✅ PEC 136: Passou no teste.
✅ PEC 137: Passou no teste.
✅ PEC 138: Passou no teste.
✅ PEC 139: Passou no teste.
✅ PEC 140: Passou no teste.
✅ PEC 141: Passou no teste.
✅ PEC 142: Passou no teste.
✅ PEC 143: Passou no teste.
✅ PEC 144: Passou no teste.
✅ PEC 145: Passou no teste.
✅ PEC 146: Passou no teste.
✅ PEC 147: Passou no teste.
✅ PEC 148: Passou no teste.
✅ PEC 149: Passou no teste.
✅ PEC 150: Passou no teste.
✅ PEC 151: Passou no teste.
✅ PEC 152: Passou no teste.
✅ PEC 153: Passou no teste.
✅ PEC 154: Passou no teste.
✅ PEC 155: Passou no teste.
✅ PEC 156: Passou no teste.
✅ PEC 157: Passou no teste.
✅ PEC 158: Passou no teste.
✅ PEC 159: Passou no teste.
✅ PEC 160: Passou no teste.
✅ PEC 161: Passou no teste.
✅ PEC 162: Passou no teste.
✅ PEC 163: Passou no teste.
✅ PEC 164: Passou no teste.
✅ PEC 165: Passou no teste.
✅ PEC 166: Passou no teste.
✅ PEC 167: Passou no teste.
✅ PEC 168: Passou no teste.
✅ PEC 169: Passou no teste.
✅ PEC 170: Passou no teste.
✅ PEC 171: Passou no teste.
✅ PEC 172: Passou no teste.
✅ PEC 173: Passou no teste.
✅ PEC 174: Passou no teste.
✅ PEC 175: Passou no teste.
✅ PEC 176: Passou no teste.
✅ PEC 177: Passou no teste.
✅ PEC 178: Passou no teste.
✅ PEC 179: Passou no teste.
✅ PEC 180: Passou no teste.
✅ PEC 181: Passou no teste.
✅ PEC 182: Passou no teste.
✅ PEC 183: Passou no teste.
✅ PEC 184: Passou no teste.
✅ PEC 185: Passou no teste.
✅ PEC 186: Passou no teste.
✅ PEC 187: Passou no teste.
✅ PEC 188: Passou no teste.
✅ PEC 189: Passou no teste.
✅ PEC 190: Passou no teste.
✅ PEC 191: Passou no teste.
✅ PEC 192: Passou no teste.
✅ PEC 193: Passou no teste.
✅ PEC 194: Passou no teste.
✅ PEC 195: Passou no teste.
✅ PEC 196: Passou no teste.
✅ PEC 197: Passou no teste.
✅ PEC 198: Passou no teste.
✅ PEC 199: Passou no teste.
✅ PEC 200: Passou no teste.
✅ PEC 201: Passou no teste.
✅ PEC 202: Passou no teste.
✅ PEC 203: Passou no teste.
✅ PEC 204: Passou no teste.
✅ PEC 205: Passou no teste.
✅ PEC 206: Passou no teste.
✅ PEC 207: Passou no teste.
✅ PEC 208: Passou no teste.
✅ PEC 209: Passou no teste.
✅ PEC 210: Passou no teste.
✅ PEC 211: Passou no teste.
✅ PEC 212: Passou no teste.
✅ PEC 213: Passou no teste.
✅ PEC 214: Passou no teste.
✅ PEC 215: Passou no teste.
✅ PEC 216: Passou no teste.
✅ PEC 217: Passou no teste.
✅ PEC 218: Passou no teste.
✅ PEC 219: Passou no teste.
✅ PEC 220: Passou no teste.
✅ PEC 221: Passou no teste.
✅ PEC 222: Passou no teste.
✅ PEC 223: Passou no teste.
✅ PEC 224: Passou no teste.
✅ PEC 225: Passou no teste.
✅ PEC 226: Passou no teste.
✅ PEC 227: Passou no teste.
✅ PEC 228: Passou no teste.
✅ PEC 229: Passou no teste.
✅ PEC 230: Passou no teste.
✅ PEC 231: Passou no teste.
✅ PEC 232: Passou no teste.
✅ PEC 233: Passou no teste.
✅ PEC 234: Passou no teste.
✅ PEC 235: Passou no teste.
✅ PEC 236: Passou no teste.
✅ PEC 237: Passou no teste.
✅ PEC 238: Passou no teste.
✅ PEC 239: Passou no teste.
✅ PEC 240: Passou no teste.
✅ PEC 241: Passou no teste.
✅ PEC 242: Passou no teste.
✅ PEC 243: Passou no teste.
✅ PEC 244: Passou no teste.
✅ PEC 245: Passou no teste.
✅ PEC 246: Passou no teste.
✅ PEC 247: Passou no teste.
✅ PEC 248: Passou no teste.
✅ PEC 249: Passou no teste.
✅ PEC 250: Passou no teste.
✅ PEC 251: Passou no teste.
✅ PEC 252: Passou no teste.
✅ PEC 253: Passou no teste.
✅ PEC 254: Passou no teste.
✅ PEC 255: Passou no teste.
✅ PEC 256: Passou no teste.
✅ PEC 257: Passou no teste.
✅ PEC 258: Passou no teste.
✅ PEC 259: Passou no teste.
✅ PEC 260: Passou no teste.
✅ PEC 261: Passou no teste.
✅ PEC 262: Passou no teste.
✅ PEC 263: Passou no teste.
✅ PEC 264: Passou no teste.
✅ PEC 265: Passou no teste.
✅ PEC 266: Passou no teste.
✅ PEC 267: Passou no teste.
✅ PEC 268: Passou no teste.
✅ PEC 269: Passou no teste.
✅ PEC 270: Passou no teste.
✅ PEC 271: Passou no teste.
✅ PEC 272: Passou no teste.
✅ PEC 273: Passou no teste.
✅ PEC 274: Passou no teste.
✅ PEC 275: Passou no teste.
✅ PEC 276: Passou no teste.
✅ PEC 277: Passou no teste.
✅ PEC 278: Passou no teste.
✅ PEC 279: Passou no teste.
✅ PEC 280: Passou no teste.
✅ PEC 281: Passou no teste.
✅ PEC 282: Passou no teste.
✅ PEC 283: Passou no teste.
✅ PEC 284: Passou no teste.
✅ PEC 285: Passou no teste.
✅ PEC 286: Passou no teste.
✅ PEC 287: Passou no teste.
✅ PEC 288: Passou no teste.
✅ PEC 289: Passou no teste.
✅ PEC 290: Passou no teste.
✅ PEC 291: Passou no teste.
✅ PEC 292: Passou no teste.
✅ PEC 293: Passou no teste.
✅ PEC 294: Passou no teste.
✅ PEC 295: Passou no teste.
✅ PEC 296: Passou no teste.
✅ PEC 297: Passou no teste.
✅ PEC 298: Passou no teste.
✅ PEC 299: Passou no teste.
✅ PEC 300: Passou no teste.
✅ PEC 301: Passou no teste.
✅ PEC 302: Passou no teste.
✅ PEC 303: Passou no teste.
✅ PEC 304: Passou no teste.
✅ PEC 305: Passou no teste.
✅ PEC 306: Passou no teste.
✅ PEC 307: Passou no teste.
✅ PEC 308: Passou no teste.
✅ PEC 309: Passou no teste.
✅ PEC 310: Passou no teste.
✅ PEC 311: Passou no teste.
✅ PEC 312: Passou no teste.
✅ PEC 313: Passou no teste.
✅ PEC 314: Passou no teste.
✅ PEC 315: Passou no teste.
✅ PEC 316: Passou no teste.
✅ PEC 317: Passou no teste.
✅ PEC 318: Passou no teste.
✅ PEC 319: Passou no teste.
✅ PEC 320: Passou no teste.
✅ PEC 321: Passou no teste.
✅ PEC 322: Passou no teste.
✅ PEC 323: Passou no teste.
✅ PEC 324: Passou no teste.
✅ PEC 325: Passou no teste.
✅ PEC 326: Passou no teste.
✅ PEC 327: Passou no teste.
✅ PEC 328: Passou no teste.
✅ PEC 329: Passou no teste.
✅ PEC 330: Passou no teste.
✅ PEC 331: Passou no teste.
✅ PEC 332: Passou no teste.
✅ PEC 333: Passou no teste.
✅ PEC 334: Passou no teste.
✅ PEC 335: Passou no teste.
✅ PEC 336: Passou no teste.
✅ PEC 337: Passou no teste.
✅ PEC 338: Passou no teste.
✅ PEC 339: Passou no teste.
✅ PEC 340: Passou no teste.
✅ PEC 341: Passou no teste.
✅ PEC 342: Passou no teste.
✅ PEC 343: Passou no teste.
✅ PEC 344: Passou no teste.
✅ PEC 345: Passou no teste.
✅ PEC 346: Passou no teste.
✅ PEC 347: Passou no teste.
✅ PEC 348: Passou no teste.
✅ PEC 349: Passou no teste.
✅ PEC 350: Passou no teste.
✅ PEC 351: Passou no teste.
✅ PEC 352: Passou no teste.
✅ PEC 353: Passou no teste.
✅ PEC 354: Passou no teste.
✅ PEC 355: Passou no teste.
✅ PEC 356: Passou no teste.
✅ PEC 357: Passou no teste.
✅ PEC 358: Passou no teste.
✅ PEC 359: Passou no teste.
✅ PEC 360: Passou no teste.
✅ PEC 361: Passou no teste.
✅ PEC 362: Passou no teste.
✅ PEC 363: Passou no teste.
✅ PEC 364: Passou no teste.
✅ PEC 365: Passou no teste.
✅ PEC 366: Passou no teste.
✅ PEC 367: Passou no teste.
✅ PEC 368: Passou no teste.
✅ PEC 369: Passou no teste.
✅ PEC 370: Passou no teste.
✅ PEC 371: Passou no teste.
✅ PEC 372: Passou no teste.
✅ PEC 373: Passou no teste.
✅ PEC 374: Passou no teste.
✅ PEC 375: Passou no teste.
✅ PEC 376: Passou no teste.
✅ PEC 377: Passou no teste.
✅ PEC 378: Passou no teste.
✅ PEC 379: Passou no teste.
✅ PEC 380: Passou no teste.
✅ PEC 381: Passou no teste.
✅ PEC 382: Passou no teste.
✅ PEC 383: Passou no teste.
✅ PEC 384: Passou no teste.
✅ PEC 385: Passou no teste.
✅ PEC 386: Passou no teste.
✅ PEC 387: Passou no teste.
✅ PEC 388: Passou no teste.
✅ PEC 389: Passou no teste.
✅ PEC 390: Passou no teste.
✅ PEC 391: Passou no teste.
✅ PEC 392: Passou no teste.
✅ PEC 393: Passou no teste.
✅ PEC 394: Passou no teste.
✅ PEC 395: Passou no teste.
✅ PEC 396: Passou no teste.
✅ PEC 397: Passou no teste.
✅ PEC 398: Passou no teste.
✅ PEC 399: Passou no teste.
✅ PEC 400: Passou no teste.
✅ PEC 401: Passou no teste.
✅ PEC 402: Passou no teste.
✅ PEC 403: Passou no teste.
✅ PEC 404: Passou no teste.
✅ PEC 405: Passou no teste.
✅ PEC 406: Passou no teste.
✅ PEC 407: Passou no teste.
✅ PEC 408: Passou no teste.
✅ PEC 409: Passou no teste.
✅ PEC 410: Passou no teste.
✅ PEC 411: Passou no teste.
✅ PEC 412: Passou no teste.
✅ PEC 413: Passou no teste.
✅ PEC 414: Passou no teste.
✅ PEC 415: Passou no teste.
✅ PEC 416: Passou no teste.
✅ PEC 417: Passou no teste.
✅ PEC 418: Passou no teste.
✅ PEC 419: Passou no teste.
✅ PEC 420: Passou no teste.
✅ PEC 421: Passou no teste.
✅ PEC 422: Passou no teste.
✅ PEC 423: Passou no teste.
✅ PEC 424: Passou no teste.
✅ PEC 425: Passou no teste.
✅ PEC 426: Passou no teste.
✅ PEC 427: Passou no teste.
✅ PEC 428: Passou no teste.
✅ PEC 429: Passou no teste.
✅ PEC 430: Passou no teste.
✅ PEC 431: Passou no teste.
✅ PEC 432: Passou no teste.
✅ PEC 433: Passou no teste.
✅ PEC 434: Passou no teste.
✅ PEC 435: Passou no teste.
✅ PEC 436: Passou no teste.
✅ PEC 437: Passou no teste.
✅ PEC 438: Passou no teste.
✅ PEC 439: Passou no teste.
✅ PEC 440: Passou no teste.
✅ PEC 441: Passou no teste.
✅ PEC 442: Passou no teste.
✅ PEC 443: Passou no teste.
✅ PEC 444: Passou no teste.
✅ PEC 445: Passou no teste.
✅ PEC 446: Passou no teste.
✅ PEC 447: Passou no teste.
✅ PEC 448: Passou no teste.
✅ PEC 449: Passou no teste.
✅ PEC 450: Passou no teste.
✅ PEC 451: Passou no teste.
✅ PEC 452: Passou no teste.
✅ PEC 453: Passou no teste.
✅ PEC 454: Passou no teste.
✅ PEC 455: Passou no teste.
✅ PEC 456: Passou no teste.
✅ PEC 457: Passou no teste.
✅ PEC 458: Passou no teste.
✅ PEC 459: Passou no teste.
✅ PEC 460: Passou no teste.
✅ PEC 461: Passou no teste.
✅ PEC 462: Passou no teste.
✅ PEC 463: Passou no teste.
✅ PEC 464: Passou no teste.
✅ PEC 465: Passou no teste.
✅ PEC 466: Passou no teste.
✅ PEC 467: Passou no teste.
✅ PEC 468: Passou no teste.
✅ PEC 469: Passou no teste.
✅ PEC 470: Passou no teste.
✅ PEC 471: Passou no teste.
✅ PEC 472: Passou no teste.
✅ PEC 473: Passou no teste.
✅ PEC 474: Passou no teste.
✅ PEC 475: Passou no teste.
✅ PEC 476: Passou no teste.
✅ PEC 477: Passou no teste.
✅ PEC 478: Passou no teste.
✅ PEC 479: Passou no teste.
✅ PEC 480: Passou no teste.
✅ PEC 481: Passou no teste.
✅ PEC 482: Passou no teste.
✅ PEC 483: Passou no teste.
✅ PEC 484: Passou no teste.
✅ PEC 485: Passou no teste.
✅ PEC 486: Passou no teste.
✅ PEC 487: Passou no teste.
✅ PEC 488: Passou no teste.
✅ PEC 489: Passou no teste.
✅ PEC 490: Passou no teste.
✅ PEC 491: Passou no teste.
✅ PEC 492: Passou no teste.
✅ PEC 493: Passou no teste.
✅ PEC 494: Passou no teste.
✅ PEC 495: Passou no teste.
✅ PEC 496: Passou no teste.
✅ PEC 497: Passou no teste.
✅ PEC 498: Passou no teste.
✅ PEC 499: Passou no teste.
✅ PEC 500: Passou no teste.
✅ PEC 501: Passou no teste.
✅ PEC 502: Passou no teste.
✅ PEC 503: Passou no teste.
✅ PEC 504: Passou no teste.
✅ PEC 505: Passou no teste.
✅ PEC 506: Passou no teste.
✅ PEC 507: Passou no teste.
✅ PEC 508: Passou no teste.
✅ PEC 509: Passou no teste.
✅ PEC 510: Passou no teste.
✅ PEC 511: Passou no teste.
✅ PEC 512: Passou no teste.
✅ PEC 513: Passou no teste.
✅ PEC 514: Passou no teste.
✅ PEC 515: Passou no teste.
✅ PEC 516: Passou no teste.
✅ PEC 517: Passou no teste.
✅ PEC 518: Passou no teste.
✅ PEC 519: Passou no teste.
✅ PEC 520: Passou no teste.
✅ PEC 521: Passou no teste.
✅ PEC 522: Passou no teste.
✅ PEC 523: Passou no teste.
✅ PEC 524: Passou no teste.
✅ PEC 525: Passou no teste.
✅ PEC 526: Passou no teste.
✅ PEC 527: Passou no teste.
✅ PEC 528: Passou no teste.
✅ PEC 529: Passou no teste.
✅ PEC 530: Passou no teste.
✅ PEC 531: Passou no teste.
✅ PEC 532: Passou no teste.
✅ PEC 533: Passou no teste.
✅ PEC 534: Passou no teste.
✅ PEC 535: Passou no teste.
✅ PEC 536: Passou no teste.
✅ PEC 537: Passou no teste.
✅ PEC 538: Passou no teste.
✅ PEC 539: Passou no teste.
✅ PEC 540: Passou no teste.
✅ PEC 541: Passou no teste.
✅ PEC 542: Passou no teste.
✅ PEC 543: Passou no teste.
✅ PEC 544: Passou no teste.
✅ PEC 545: Passou no teste.
✅ PEC 546: Passou no teste.
✅ PEC 547: Passou no teste.
✅ PEC 548: Passou no teste.
✅ PEC 549: Passou no teste.
✅ PEC 550: Passou no teste.
✅ PEC 551: Passou no teste.
✅ PEC 552: Passou no teste.
✅ PEC 553: Passou no teste.
✅ PEC 554: Passou no teste.
✅ PEC 555: Passou no teste.
✅ PEC 556: Passou no teste.
✅ PEC 557: Passou no teste.
✅ PEC 558: Passou no teste.
✅ PEC 559: Passou no teste.
✅ PEC 560: Passou no teste.
✅ PEC 561: Passou no teste.
✅ PEC 562: Passou no teste.
✅ PEC 563: Passou no teste.
✅ PEC 564: Passou no teste.
✅ PEC 565: Passou no teste.
✅ PEC 566: Passou no teste.
✅ PEC 567: Passou no teste.
✅ PEC 568: Passou no teste.
✅ PEC 569: Passou no teste.
✅ PEC 570: Passou no teste.
✅ PEC 571: Passou no teste.
✅ PEC 572: Passou no teste.
✅ PEC 573: Passou no teste.
✅ PEC 574: Passou no teste.
✅ PEC 575: Passou no teste.
✅ PEC 576: Passou no teste.
✅ PEC 577: Passou no teste.
✅ PEC 578: Passou no teste.
✅ PEC 579: Passou no teste.
✅ PEC 580: Passou no teste.
✅ PEC 581: Passou no teste.
✅ PEC 582: Passou no teste.
✅ PEC 583: Passou no teste.
✅ PEC 584: Passou no teste.
✅ PEC 585: Passou no teste.
✅ PEC 586: Passou no teste.
✅ PEC 587: Passou no teste.
✅ PEC 588: Passou no teste.
✅ PEC 589: Passou no teste.
✅ PEC 590: Passou no teste.
✅ PEC 591: Passou no teste.
✅ PEC 592: Passou no teste.
✅ PEC 593: Passou no teste.
✅ PEC 594: Passou no teste.
✅ PEC 595: Passou no teste.
✅ PEC 596: Passou no teste.
✅ PEC 597: Passou no teste.
✅ PEC 598: Passou no teste.
✅ PEC 599: Passou no teste.
✅ PEC 600: Passou no teste.
✅ PEC 601: Passou no teste.
✅ PEC 602: Passou no teste.
✅ PEC 603: Passou no teste.
✅ PEC 604: Passou no teste.
✅ PEC 605: Passou no teste.
✅ PEC 606: Passou no teste.
✅ PEC 607: Passou no teste.
✅ PEC 608: Passou no teste.
✅ PEC 609: Passou no teste.
✅ PEC 610: Passou no teste.
✅ PEC 611: Passou no teste.
✅ PEC 612: Passou no teste.
✅ PEC 613: Passou no teste.
✅ PEC 614: Passou no teste.
✅ PEC 615: Passou no teste.
✅ PEC 616: Passou no teste.
✅ PEC 617: Passou no teste.
✅ PEC 618: Passou no teste.
✅ PEC 619: Passou no teste.
✅ PEC 620: Passou no teste.
✅ PEC 621: Passou no teste.
✅ PEC 622: Passou no teste.
✅ PEC 623: Passou no teste.
✅ PEC 624: Passou no teste.
✅ PEC 625: Passou no teste.
✅ PEC 626: Passou no teste.
✅ PEC 627: Passou no teste.
✅ PEC 628: Passou no teste.
✅ PEC 629: Passou no teste.
✅ PEC 630: Passou no teste.
✅ PEC 631: Passou no teste.
✅ PEC 632: Passou no teste.
✅ PEC 633: Passou no teste.
✅ PEC 634: Passou no teste.
✅ PEC 635: Passou no teste.
✅ PEC 636: Passou no teste.
✅ PEC 637: Passou no teste.
✅ PEC 638: Passou no teste.
✅ PEC 639: Passou no teste.
✅ PEC 640: Passou no teste.
✅ PEC 641: Passou no teste.
✅ PEC 642: Passou no teste.
✅ PEC 643: Passou no teste.
✅ PEC 644: Passou no teste.
✅ PEC 645: Passou no teste.
✅ PEC 646: Passou no teste.
✅ PEC 647: Passou no teste.
✅ PEC 648: Passou no teste.
✅ PEC 649: Passou no teste.
✅ PEC 650: Passou no teste.
✅ PEC 651: Passou no teste.
✅ PEC 652: Passou no teste.
✅ PEC 653: Passou no teste.
✅ PEC 654: Passou no teste.
✅ PEC 655: Passou no teste.
✅ PEC 656: Passou no teste.
✅ PEC 657: Passou no teste.
✅ PEC 658: Passou no teste.
✅ PEC 659: Passou no teste.
✅ PEC 660: Passou no teste.
✅ PEC 661: Passou no teste.
✅ PEC 662: Passou no teste.
✅ PEC 663: Passou no teste.
✅ PEC 664: Passou no teste.
✅ PEC 665: Passou no teste.
✅ PEC 666: Passou no teste.
✅ PEC 667: Passou no teste.
✅ PEC 668: Passou no teste.
✅ PEC 669: Passou no teste.
✅ PEC 670: Passou no teste.
✅ PEC 671: Passou no teste.
✅ PEC 672: Passou no teste.
✅ PEC 673: Passou no teste.
✅ PEC 674: Passou no teste.
✅ PEC 675: Passou no teste.
✅ PEC 676: Passou no teste.
✅ PEC 677: Passou no teste.
✅ PEC 678: Passou no teste.
✅ PEC 679: Passou no teste.
✅ PEC 680: Passou no teste.
✅ PEC 681: Passou no teste.
✅ PEC 682: Passou no teste.
✅ PEC 683: Passou no teste.
✅ PEC 684: Passou no teste.
✅ PEC 685: Passou no teste.
✅ PEC 686: Passou no teste.
✅ PEC 687: Passou no teste.
✅ PEC 688: Passou no teste.
✅ PEC 689: Passou no teste.
✅ PEC 690: Passou no teste.
✅ PEC 691: Passou no teste.
✅ PEC 692: Passou no teste.
✅ PEC 693: Passou no teste.
✅ PEC 694: Passou no teste.
✅ PEC 695: Passou no teste.
✅ PEC 696: Passou no teste.
❌ Erro na PEC 697: Uma justificativa ainda foi encontrada no texto cortado!
✅ PEC 698: Passou no teste.
✅ PEC 699: Passou no teste.
✅ PEC 700: Passou no teste.
✅ PEC 701: Passou no teste.
✅ PEC 702: Passou no teste.
✅ PEC 703: Passou no teste.
✅ PEC 704: Passou no teste.
✅ PEC 705: Passou no teste.
✅ PEC 706: Passou no teste.
✅ PEC 707: Passou no teste.
✅ PEC 708: Passou no teste.
✅ PEC 709: Passou no teste.
✅ PEC 710: Passou no teste.
✅ PEC 711: Passou no teste.
✅ PEC 712: Passou no teste.
✅ PEC 713: Passou no teste.
✅ PEC 714: Passou no teste.
✅ PEC 715: Passou no teste.

In [45]:
def extract_until_any(texto, stop_words):
    if not texto:
        return texto
    
    # Primeiro passo: padronizar espaçamentos e remover quebras de linhas do PDF
    # Isso une palavras como "JUSTIFICAÇÃ\nO" caso apareçam no resto da base
    texto_normalizado = re.sub(r'(\w+)-\n\s*(\w+)', r'\1\2', texto)
    texto_normalizado = texto_normalizado.replace("JUSTIFICAÇÃ\nO", "JUSTIFICAÇÃO")
    texto_normalizado = texto_normalizado.replace("JUSTIFICAT\nIVA", "JUSTIFICATIVA")
    
    # Criamos um padrão que busca as palavras inteiras (\b) independente de estarem no início da linha
    # O [| ]*? serve para engolir aquela barra vertical " | JUSTIFICAÇÃO" que aparece no texto 5
    padrao = r"[| ]*?\b(?:" + "|".join([re.escape(word) for word in stop_words]) + r")\b"
    
    # Compilamos apenas com IGNORECASE (não precisamos de MULTILINE aqui)
    regex = re.compile(padrao, re.IGNORECASE)
    
    match = regex.search(texto_normalizado)
    
    if match:
        # Corta exatamente antes da palavra de parada (ou antes dos espaços/barras que a antecedem)
        return texto_normalizado[:match.start()].strip()
    
    return texto_normalizado

In [46]:
just_variacoes = ["justificação", "justificativa", "j u s t i f i c a ç ã o", "j u s t i f i c a ç ã", "JUSTIFICAÇÃ\nO", "JUSTIFICAÇÃO"]
plp["texto_preprocessado_sem_justificativa"] = plp['texto_preprocessado'].apply(lambda x: extract_until_any(x, just_variacoes))

In [47]:
plp[plp.texto_preprocessado == plp.texto_preprocessado_sem_justificativa]

Empty DataFrame
Columns: [num_emenda, materia, nome_arquivo, texto, cabecalho, texto_sem_cabecalho, texto_preprocessado, texto_preprocessado_sem_justificativa]
Index: []

In [48]:
plp.to_parquet("../data/datasets/PLP_68_2024_preprocessado.parquet", index=False)

In [49]:
plp

,num_emenda,materia,nome_arquivo,texto,cabecalho,texto_sem_cabecalho,texto_preprocessado,texto_preprocessado_sem_justificativa
0,1,PLP_68_2024,EMENDA_1-U_-_PLP_68_2024.txt,Gabinete do Senador Esperidião Amin\nEMENDA Nº...,Gabinete do Senador Esperidião Amin\nEMENDA Nº...,\nSuprimam-se os §§ 1° e 2° do art. 384 do PLP...,Suprimam-se os §§ 1° e 2° do art. 384 do PLP n...,Suprimam-se os §§ 1° e 2° do art. 384 do PLP n...
1,10,PLP_68_2024,EMENDA_10-U_-_PLP_68_2024.txt,Gabinete do Senador Mecias de Jesus\nEMENDA Nº...,Gabinete do Senador Mecias de Jesus\nEMENDA Nº...,\nInclua-se o §6º no art. 23 e dê-se a seguint...,Inclua-se o §6º no art. 23 e dê-se a seguinte ...,Inclua-se o §6º no art. 23 e dê-se a seguinte ...
2,100,PLP_68_2024,EMENDA_100-U_-_PLP_68_2024.txt,Gabinete do Senador Fabiano Contarato\nEMENDA ...,Gabinete do Senador Fabiano Contarato\nEMENDA ...,\nAcrescenta o inciso VIII ao §1º do artigo 40...,Acrescenta o inciso VIII ao §1º do artigo 406 ...,Acrescenta o inciso VIII ao §1º do artigo 406 ...
3,1000,PLP_68_2024,EMENDA_1000-U_-_PLP_68_2024.txt,EMENDA Nº \n(ao PLP 68/2024)\nAcrescen...,EMENDA Nº \n(ao PLP 68/2024),\nAcrescente-se inciso VI ao parágrafo único d...,Acrescente-se inciso VI ao parágrafo único do ...,Acrescente-se inciso VI ao parágrafo único do ...
4,1001,PLP_68_2024,EMENDA_1001-U_-_PLP_68_2024.txt,EMENDA Nº \n(ao PLP 68/2024)\nDê-se ao...,EMENDA Nº \n(ao PLP 68/2024),\nDê-se ao § 7º do art. 163 do Projeto a segui...,Dê-se ao § 7º do art. 163 do Projeto a seguint...,Dê-se ao § 7º do art. 163 do Projeto a seguint...
...,...,...,...,...,...,...,...,...
2234,995,PLP_68_2024,EMENDA_995-U_-_PLP_68_2024.txt,EMENDA Nº \n(ao PLP 68/2024)\nDê-se ao...,EMENDA Nº \n(ao PLP 68/2024),\nDê-se ao inciso IV do caput do art. 26 do Pr...,Dê-se ao inciso IV do caput do art. 26 do Proj...,Dê-se ao inciso IV do caput do art. 26 do Proj...
2235,996,PLP_68_2024,EMENDA_996-U_-_PLP_68_2024.txt,EMENDA Nº \n(ao PLP 68/2024)\nAcrescen...,EMENDA Nº \n(ao PLP 68/2024),"\nAcrescente-se § 4º ao art. 450 do Projeto, c...","Acrescente-se § 4º ao art. 450 do Projeto, com...","Acrescente-se § 4º ao art. 450 do Projeto, com..."
2236,997,PLP_68_2024,EMENDA_997-U_-_PLP_68_2024.txt,EMENDA Nº \n(ao PLP 68/2024)\nAcrescen...,EMENDA Nº \n(ao PLP 68/2024),"\nAcrescente-se § 0º ao art. 247 do Projeto, c...","Acrescente-se § 0º ao art. 247 do Projeto, com...","Acrescente-se § 0º ao art. 247 do Projeto, com..."
2237,998,PLP_68_2024,EMENDA_998-U_-_PLP_68_2024.txt,EMENDA Nº \n(ao PLP 68/2024)\nDê-se no...,EMENDA Nº \n(ao PLP 68/2024),\nDê-se nova redação ao inciso IV do § 2º do a...,Dê-se nova redação ao inciso IV do § 2º do art...,Dê-se nova redação ao inciso IV do § 2º do art...
2238,999,PLP_68_2024,EMENDA_999-U_-_PLP_68_2024.txt,EMENDA Nº - CCJ\n(ao PLP 68/2024)\nAcr...,EMENDA Nº - CCJ\n(ao PLP 68/2024),\nAcrescente-se parágrafo único ao art. 261 do...,Acrescente-se parágrafo único ao art. 261 do P...,Acrescente-se parágrafo único ao art. 261 do P...