In [1]:
import re
import pandas as pd
from tqdm import tqdm

import os
tqdm.pandas()

In [7]:
df = pd.read_parquet("../data/datasets/MPV_612_2013_textos_emendas.parquet")
df

,num_emenda,materia,nome_arquivo,texto
0,100,MPV_612_2013,EMENDA_100_-_MPV_612_2013.txt,Subsecretaria de Apoio às Comissões Mistas\n\n...
1,101,MPV_612_2013,EMENDA_101_-_MPV_612_2013.txt,Mistas\n\nissões À\n\na2\n\nGigliola Ansiliero...
2,102,MPV_612_2013,EMENDA_102_-_MPV_612_2013.txt,Subsecretaria de Apoio às Comissões Mistas\nRe...
3,103,MPV_612_2013,EMENDA_103_-_MPV_612_2013.txt,SE\n\nMPV 612\n\nCONGRESSO NACIONAL 00103\n\nA...
4,104,MPV_612_2013,EMENDA_104_-_MPV_612_2013.txt,"Mista,\n\nàs 1) /\n\norais, Mat. 258286\n\n-)\..."
...,...,...,...,...
215,96,MPV_612_2013,EMENDA_96_-_MPV_612_2013.txt,; Congresso Nacional MEPV 612\n\n00096\nAPRESE...
216,97,MPV_612_2013,EMENDA_97_-_MPV_612_2013.txt,s\n\n€ Ápoio às Comissões Miistas\n\nDÃ\ndu G\...
217,98,MPV_612_2013,EMENDA_98_-_MPV_612_2013.txt,Subsecretaria de Apois às Comissões Mustas\n\n...
218,99,MPV_612_2013,EMENDA_99_-_MPV_612_2013.txt,Subsecretaria de Apoio às Comissões i1stas\n\n...
219,9,MPV_612_2013,EMENDA_9_-_MPV_612_2013.txt,CONGRESSO NACIONAL MEV 612\n\n00009\nAPRESENTA...

In [8]:
TXT_DIR = "../data/txts/MPV_612_2013/txts_from_label_studio_annotations"

textos_preprocessados = {}
textos_preprocessados_sem_justificativa = {}

for arquivo in os.listdir(TXT_DIR):

    if not arquivo.endswith(".txt"):
        continue

    caminho = os.path.join(TXT_DIR, arquivo)

    with open(caminho, "r", encoding="utf-8") as f:
        texto_original = f.read()

    # ------------------------
    # Texto preprocessado normal
    # ------------------------
    texto = texto_original

    texto = re.sub(
        r"===\s*PÁGINA\s+\d+\s*===",
        "",
        texto,
        flags=re.IGNORECASE
    )

    texto = re.sub(
        r"\[EMENDA\]",
        "",
        texto,
        flags=re.IGNORECASE
    )

    texto = re.sub(r"\n{3,}", "\n\n", texto)
    texto = texto.strip()

    textos_preprocessados[arquivo] = texto

    # ------------------------
    # Texto sem justificativa
    # ------------------------
    texto = texto_original

    paginas = re.split(
        r"(===\s*PÁGINA\s+\d+\s*===)",
        texto,
        flags=re.IGNORECASE
    )

    paginas_limpas = []

    for i in range(1, len(paginas), 2):

        pagina = paginas[i + 1]

        pagina = re.sub(
            r"\[JUSTIFICATIVA\][\s\S]*",
            "",
            pagina,
            flags=re.IGNORECASE
        )

        pagina = re.sub(
            r"\[(EMENDA|JUSTIFICATIVA)\]",
            "",
            pagina,
            flags=re.IGNORECASE
        )

        pagina = pagina.strip()

        if pagina:
            paginas_limpas.append(pagina)

    texto_sem_justificativa = "\n\n".join(paginas_limpas)

    texto_sem_justificativa = re.sub(
        r"\n{3,}",
        "\n\n",
        texto_sem_justificativa
    )

    texto_sem_justificativa = texto_sem_justificativa.strip()

    textos_preprocessados_sem_justificativa[arquivo] = (
        texto_sem_justificativa
    )

print(f"Arquivos carregados: {len(textos_preprocessados)}")

df["texto_preprocessado"] = df["nome_arquivo"].map(
    textos_preprocessados
)

df["texto_preprocessado_sem_justificativa"] = (
    df["nome_arquivo"].map(
        textos_preprocessados_sem_justificativa
    )
)

print(
    "Com texto preprocessado:",
    df["texto_preprocessado"].notna().sum()
)

print(
    "Com texto sem justificativa:",
    df["texto_preprocessado_sem_justificativa"].notna().sum()
)

df[
    [
        "nome_arquivo",
        "texto_preprocessado",
        "texto_preprocessado_sem_justificativa",
    ]
].head()

Arquivos carregados: 220
Com texto preprocessado: 220
Com texto sem justificativa: 220

,nome_arquivo,texto_preprocessado,texto_preprocessado_sem_justificativa
0,EMENDA_100_-_MPV_612_2013.txt,"O Art, 23 da Medida Provisória n.º 612, de 04 ...","O Art, 23 da Medida Provisória n.º 612, de 04 ..."
1,EMENDA_101_-_MPV_612_2013.txt,"O Art. 23 da Medida Provisória n.º 612, de 04 ...","O Art. 23 da Medida Provisória n.º 612, de 04 ..."
2,EMENDA_102_-_MPV_612_2013.txt,"Modifica as alíneas “a” e “b” do incido 1l, do...","Modifica as alíneas “a” e “b” do incido 1l, do..."
3,EMENDA_103_-_MPV_612_2013.txt,"O artigo 25 da MPV 612, de 2013, que altera o ...","O artigo 25 da MPV 612, de 2013, que altera o ..."
4,EMENDA_104_-_MPV_612_2013.txt,"Acrescente-se o inciso Ill, no Art. 26 da Medi...","Acrescente-se o inciso Ill, no Art. 26 da Medi..."

In [9]:
df[
    [
        "nome_arquivo",
        "texto_preprocessado",
        "texto_preprocessado_sem_justificativa",
    ]
].head().values

array([['EMENDA_100_-_MPV_612_2013.txt',
        'O Art, 23 da Medida Provisória n.º 612, de 04 de Abril de 2013, passa a vigorar com a seguinte redação:\n\nArt. 283. A Lei nº 12.715, de 17 de setembro de 2012, passa a vigorar com as seguintes alterações:\n\n8) ficam limitadas a três por cento do imposto sobre a renda devido com relação aào programa de que trata\n| O art, 1º, e a um por cento do imposto sobre a renda devido com relação ao programa de que trata o art. 3º;\n\nd) ficam limitadas a três por cento do imposto sobre a renda devido em cada período de apuração\ntrimestral ou anual com relação ao programa de que trata o art. 1º, e a um por cento do imposto sobre a renda\ndevido em cada período de apuração trimestral! ou anual com relação ao programa de que trata o art. 3º,\nobservado em ambas as hipóteses o disposto no $ 4º do art. 3º da Lei nº 9.249, de 26 de dezembro de 1995.\n\n....................................................................................\n\n[JUSTIFICATIVA]\nA Medida Provisória n.º 612, de 04 de abril de 2013, altera a Lei n.º 12.715/2012 que trata do Programa\nNacional de Apoio à Atenção Oncológica e do Programa Nacional de Apoio à Atenção da Saúde da Pessoa com\nDeficiência. A presente emenda visa alterar de um para três por cento do valor do imposto de renda devido no\ncaso de doações de pessoas físicas para os referidos Programas. No caso de pessoas jurídicas tributadas pelo\nlucro real, a emenda visa alterar de um para três por cento o limite do imposto devido para as doações em cada\nperíodo de apuração trimestral ou anual. Vale ressaltar que o Art. 13 do PLV da MP 582/2012, que limitava o\nvalor das doações em até 4% dojímposto de renda devido foi vetado.\nPA',
        'O Art, 23 da Medida Provisória n.º 612, de 04 de Abril de 2013, passa a vigorar com a seguinte redação:\n\nArt. 283. A Lei nº 12.715, de 17 de setembro de 2012, passa a vigorar com as seguintes alterações:\n\n8) ficam limitadas a três por cento do imposto sobre a renda devido com relação aào programa de que trata\n| O art, 1º, e a um por cento do imposto sobre a renda devido com relação ao programa de que trata o art. 3º;\n\nd) ficam limitadas a três por cento do imposto sobre a renda devido em cada período de apuração\ntrimestral ou anual com relação ao programa de que trata o art. 1º, e a um por cento do imposto sobre a renda\ndevido em cada período de apuração trimestral! ou anual com relação ao programa de que trata o art. 3º,\nobservado em ambas as hipóteses o disposto no $ 4º do art. 3º da Lei nº 9.249, de 26 de dezembro de 1995.\n\n....................................................................................'],
       ['EMENDA_101_-_MPV_612_2013.txt',
        'O Art. 23 da Medida Provisória n.º 612, de 04 de Abril de 2013, passa a vigorar com a seguinte redação:\n\nArt. 283, A Lei nº 12.715, de 17 de setembro de 20i2, passa a vigorar com as seguintes alterações:\n\n..............................................................................................\n\ne) ficam limitadas a dois por cento do imposto sobre a renda devido com relação ao programa de que trata\no art. 1º, e a um por cento do imposto sobre a renda devido com relação ao programa de que trata o art. 3º;\n\nd) ficam limitadas a dois por cento do imposto sobre a renda devido em cada período de apuração\ntrimestral ou anual com relação ao programa de que trata o art. 1º, e a um por cento do imposto sobre a renda\n\ndevido em cada período de apuração trimestral ou anual com relação ao programa de que trata o art. 3º,\n: observado em ambas as hipóteses o disposto no $ 4º do art, 3º da Lei nº 9.249, de 26 de dezembro de 1995,\n\n....................................................................................\n\n[JUSTIFICATIVA]\nA Medida Provisória n.º 612, de 04 de abril de 2013, altera a Lei n.º 12,715/2012 que trata do Programa\nNacional de Apoio à Atenção Oncológica e do Programa Nacional de Apoio à Atenção da Saúde da Pessoa com\nDeficiência. A presente emenda visa alterar de um para dois por cento do valor do imposto de renda devido no\ncaso de doações de pessoas físicas para os referidos Programas. No caso de pessoas jurídicas tributadas pelo\nlucro real, a emenda visa alterar de um para dois por cento o limite do imposto devido para as doações em\ncada período de apuração trimestral ou anual. Vale ressaltar que o Art. 13 do PLV da MP 582/2012, que limitava\no valor das doações em até 4% do imposto de renda devido foi vetado.',
        'O Art. 23 da Medida Provisória n.º 612, de 04 de Abril de 2013, passa a vigorar com a seguinte redação:\n\nArt. 283, A Lei nº 12.715, de 17 de setembro de 20i2, passa a vigorar com as seguintes alterações:\n\n..............................................................................................\n\ne) ficam limitadas a dois por cento do imposto sobre a renda devido com relação ao programa de que trata\no art. 1º, e a um por cento do imposto sobre a renda devido com relação ao programa de que trata o art. 3º;\n\nd) ficam limitadas a dois por cento do imposto sobre a renda devido em cada período de apuração\ntrimestral ou anual com relação ao programa de que trata o art. 1º, e a um por cento do imposto sobre a renda\n\ndevido em cada período de apuração trimestral ou anual com relação ao programa de que trata o art. 3º,\n: observado em ambas as hipóteses o disposto no $ 4º do art, 3º da Lei nº 9.249, de 26 de dezembro de 1995,\n\n....................................................................................'],
       ['EMENDA_102_-_MPV_612_2013.txt',
        "Modifica as alíneas “a” e “b” do incido 1l, do Art. 28 da MP 612/2013, dando a ela\na seguinte redação:\n\n---------------------\n\na) aos incisos V e VIll a Xl do caput do art. 7º da Lei nº 12.546, de 2011,\nacrescentados pelo art. 25 desta Medida Provisória;\n\nb) aos incisos de XIll a XVill e XX do $ 3º e ao $ 6º, do art. 8º da Lei nº\n12.546, de 2011, acrescentados pelo art. 25 desta Medida' Provisória;\n\n.................................\n\n[JUSTIFICATIVA]\nO transporte metroferroviário e ferroviário de passageiros se caracterizam por ser\num serviço público, de cunho social, que contribui efetivamente com a mobilidade\nurbana devido a sua alta capacidade de transporte. Atualmente no Brasil, mais de\n8,5 milhões de pessoas são transportadas diariamente por esses sistemas,\nexigindo uma operação cada vez mais segura, rápida e eficiente.\n\nJá o transporte ferroviário de cargas, também serviço público, é responsável pela\nmovimentação de 481 milhões de toneladas de cargas ao ano, e gera mais de 45\nmil empregos diretos e indiretos, contribuindo decisivamente para que a logística\nseja capaz de atender às demandas e desafios do crescimento do País.\n\nOs transportes metroferroviário e ferroviário de passageiros e cargas são\naltamente inflacionários. No caso do passageiro porque pesa diretamente no\nboiso do cidadão brasileiro de média e baixa renda e no caso da carga porque\ngera efeitos sobre toda a cadeia produtiva brasileira. Dessa forma, com a\ndesoneração imediata do setor metroferroviário e ferroviário de passageiros e\ncargas as empresas que operam esse tipo de transporte ficarão mais sadias do\nponto de vista econômico-financeiro, fazendo com que sejam capazes de ampliar\nsua capacidade de investimento, refletindo-se numa maior capacitação da mão-\nde-obra, na ampliação dos sistemas e de sua capacidade de transporte e na\ngeração de emprego e renda, além de contribuir para a redução da pressão\ninflacionária sobre o preço das tarifas de transporte de todos os sistemas no\nBrasil. ; o\n\n[JUSTIFICATIVA]\nTendo em vista os cuidados que o Governo Federal vem tendo com o controle da\ninflação, aliado ao advento dos grandes jogos e ao caos instalado no transporte\nurbano e na logística brasileira, não pode justamente o sistema metroferroviário e\nferroviário de passageiros e de cargas, que servem diretamente ao cidadão\nbrasileiro e ao Brasil, ficar à espera de um benefício já concedido a diversos\noutros setores econômicos.\n\nPor todo o exposto, defende-se a aplicação imediata dos efeitos desta MP aos\nsetores metroferroviário e ferroviário de /p'assageiros e Cargas.",
        "Modifica as alíneas “a” e “b” do incido 1l, do Art. 28 da MP 612/2013, dando a ela\na seguinte redação:\n\n---------------------\n\na) aos incisos V e VIll a Xl do caput do art. 7º da Lei nº 12.546, de 2011,\nacrescentados pelo art. 25 desta Medida Provisória;\n\nb) aos incisos de XIll a XVill e XX do $ 3º e ao $ 6º, do art. 8º da Lei nº\n12.546, de 2011, acrescentados pelo art. 25 desta Medida' Provisória;\n\n................................."],
       ['EMENDA_103_-_MPV_612_2013.txt',
        'O artigo 25 da MPV 612, de 2013, que altera o art. 7º da Lei nº 12.546, de 14 de\ndezembro de 2011, passa a vigorar com a seguinte alteração no texto proposto ao\n\ninciso VIH do artigo da lei:\n“Vill - as empresas que prestam os serviços classificados na Nomenciatura\nBrasileira de Serviços - NBS, instituída pelo Decreto nº 7.708, de 2 de abril de\n2012, nos códigos 1.1201.25.00, 1,.1403.29.10, 1.2001.33.00, 1.2001.39.12,\n1.2001.54.00, — 1,.2003.60.00, — 1.2003.70.00, 1.1804.11.00, 1.1804.19.00,\n1.1804.21.00, — 1.1804.22.00,  1.1804.23.00, 1.1804.30.00, 1.1804.40.00,\n\n1.1804.50.00, 1.1804.61.00 e 1.1804.62.00;" (NR)\n\n[JUSTIFICATIVA]\nA presente emenda adiciona à MPV 612/2013 os serviços listados na seguinte tabela:\n\nCódigoNBS — Descrição\n\n1.1804.11.00 - Serviços de reservas em transportes aéreos\n\n1.1804,19.00 — Outros serviços de planejamento e reserva em transportes\n1.1804.21.00 - Serviços de reservas de hospedagem\n\n1.1804.22.00 - Serviços de reservas em cruzeiros\n\n1.1804.23.00 - Serviços de reservas de pacotes turísticos\n\n1.1804,30,00 - Outros serviços de reservas\n\n1.1804.40.00 - Serviços de operadoras de turismo\n\n1.1804.50.00 — Serviços de guias turísticos\n\n1.1804.61.00 - Serviços de promoção turística\n\n1.1804.62.00 - Serviços de informação a visitantes\n\nServiços estes que se encontram sob o código 1.1804, Serviços de planejamento de\nviagens e de operador de turismo, da Nomenclatura Brasileira de Serviços.\n\n[JUSTIFICATIVA]\nO potencial inexplorado do turismo brasileiro é enorme além da proximidade de\neventos esportivos a serem realizados no Brasil. Assim a intenção da presente\nproposição é estimular o desenvolvimento deste setor, atraindo investimentos com\nvistas à criação da estrutura de serviços necessária à realização, nos próximos anos,\nda Copa da FIFA e das Olimpíadas.\n\nA estrutura empresarial e a especialização de mão de obra construídas durante\nesse período preparatório servirá, findas as comemorações, para explorar esse\npotencial de nosso País ainda praticamente intocado. Apesar de a imagem do Brasil\nser amplamente difundida no âmbito internacional, a atual falta de estrutura e de\nserviços especializados faz com que nossa participação no turismo internacional\nainda esteja muito aquém de nosso potencial.\n\nVale ainda ressaltar que por se tratar de um setor intensivo no uso de mão de\nobra, o estímulo proposto, de desoneração da folha de pagamentos, será de grande\nvalia.\n\nPor esses motivos e seguro de que a alteração proposta representará um\navanço no sentido do desenvolvimento balanceado da economia de nosso País, rogo\no apoio dos nobres colegas.',
        'O artigo 25 da MPV 612, de 2013, que altera o art. 7º da Lei nº 12.546, de 14 de\ndezembro de 2011, passa a vigorar com a seguinte alteração no texto proposto ao\n\ninciso VIH do artigo da lei:\n“Vill - as empresas que prestam os serviços classificados na Nomenciatura\nBrasileira de Serviços - NBS, instituída pelo Decreto nº 7.708, de 2 de abril de\n2012, nos códigos 1.1201.25.00, 1,.1403.29.10, 1.2001.33.00, 1.2001.39.12,\n1.2001.54.00, — 1,.2003.60.00, — 1.2003.70.00, 1.1804.11.00, 1.1804.19.00,\n1.1804.21.00, — 1.1804.22.00,  1.1804.23.00, 1.1804.30.00, 1.1804.40.00,\n\n1.1804.50.00, 1.1804.61.00 e 1.1804.62.00;" (NR)'],
       ['EMENDA_104_-_MPV_612_2013.txt',
        'Acrescente-se o inciso Ill, no Art. 26 da Medida Provisória nº 612, de 04 de Abril de\n2013, que inclui produtos no Anexo à Lei nº 12.546, de 14 de dezembro de 2011, passa a\nvigorar acrescido do “álcool etílico para fins carburantes, com especificações determinadas\npela ANP”, classificado nos seguintes códigos da Tabela de Incidência do Imposto sobre\nProdutos Industrializados — TIPI, aprovada pelo Decreto nº 7.660, de 23 de dezembro de\n2011:\n\n---------------------------------------------------------------------------------------------------------------------\n\n11 - 2207.10.10 Ex O1; - 2207.10.90 Ex 01; - 2207.20.11 Ex 01; - 2207.20.19 Ex 071.”\n\n[JUSTIFICATIVA]\nA presente emenda visa fomentar o setor produtivo de etanol combustível, tendo em\nvista que a falta de políticas públicas de longo prazo para o setor, tem gerado impactos no\naumento do custo de produção (especialmente decorrente do aumento do preço da terra),\nbem como a minimização das difículdades geradas pela política de preços artíficiais da\ngasolina, desestimularam os investimentos e atingiram fortemente toda a cadeia procdutiva.\n\nPor isso, que a aprovação desta emenda é imprescindível para que a agroindústria\nprodutora de etanol combustível possa continuar a oferecer um produto de qualidade com\npreço competiítivo para os mercados nacional e internacional.',
        'Acrescente-se o inciso Ill, no Art. 26 da Medida Provisória nº 612, de 04 de Abril de\n2013, que inclui produtos no Anexo à Lei nº 12.546, de 14 de dezembro de 2011, passa a\nvigorar acrescido do “álcool etílico para fins carburantes, com especificações determinadas\npela ANP”, classificado nos seguintes códigos da Tabela de Incidência do Imposto sobre\nProdutos Industrializados — TIPI, aprovada pelo Decreto nº 7.660, de 23 de dezembro de\n2011:\n\n---------------------------------------------------------------------------------------------------------------------\n\n11 - 2207.10.10 Ex O1; - 2207.10.90 Ex 01; - 2207.20.11 Ex 01; - 2207.20.19 Ex 071.”']],
      dtype=object)

In [10]:
df[df.texto_preprocessado == df.texto_preprocessado_sem_justificativa]

Empty DataFrame
Columns: [num_emenda, materia, nome_arquivo, texto, texto_preprocessado, texto_preprocessado_sem_justificativa]
Index: []

In [11]:
df.to_parquet("../data/datasets/MPV_612_2013_preprocessado.parquet", index=False)