In [1]:
import re
import pandas as pd
from tqdm import tqdm

tqdm.pandas()

In [2]:
pec = pd.read_parquet("../data/datasets/PEC_6_2019_textos_emendas.parquet")
pec.head()

,num_emenda,materia,nome_arquivo,texto
0,100,PEC_6_2019,EMENDA_100_-_PEC_6_2019.txt,PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019...
1,101,PEC_6_2019,EMENDA_101_-_PEC_6_2019.txt,PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019...
2,102,PEC_6_2019,EMENDA_102_-_PEC_6_2019.txt,PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019...
3,103,PEC_6_2019,EMENDA_103_-_PEC_6_2019.txt,\nSENADO FEDERAL \nGabinete do Senador Lasier...
4,104,PEC_6_2019,EMENDA_104_-_PEC_6_2019.txt,\nGabinete do Senador Humberto Costa \n \n \n...

In [3]:
pec.describe()

       num_emenda
count  269.000000
mean   135.000000
std     77.797815
min      1.000000
25%     68.000000
50%    135.000000
75%    202.000000
max    269.000000

In [4]:
pec[~pec.texto.str.contains("(à PEC nº 6, de 2019)|(à Proposta de Emenda à Constituição nº 6, de 2019)")].texto.str[:300].values

C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_7272\2222540548.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  pec[~pec.texto.str.contains("(à PEC nº 6, de 2019)|(à Proposta de Emenda à Constituição nº 6, de 2019)")].texto.str[:300].values

<ArrowStringArray>
[        'PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019 \n \nEMENDA SUPRESSIVA \n \nSuprima-se os §§ 2º,  3º e 5º do art. 24 da PEC 6/2019. \n \nJUSTIFICAÇÃO \n \n \n \nA regra do § 2º e 3º do art. 24 implica na redução da parcela acumulável \ndos benefícios permitidos, mediante a aplicação de percentuais sobre faixas ',
             'PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019 \n \nEMENDA MODIFICATIVA \n \nDê-se ao art. 34 da PEC 6/2019 a seguinte redação: \n“Art. 34. Na hipótese de extinção por lei de regime previdenciário e \nmigração dos respectivos segurados para o Regime Geral de Previdência \nSocial, serão observados os seguin',
       'PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019 \n \nEMENDA SUPRESSIVA \n \n \n \nSuprimam-se os §§ § 6º, 7º, 8º e 9° do art. 8° do Ato das Disposições \nConstitucionais Transitórias (ADCT), incluídos pelo art. 2° da Proposta de Emenda à \nConstituição n° 06/2019. \n \nJUSTIFICAÇÃO \n \n \nA PEC 06/2019, sem qual',
      ' \n \n \nSENADO FEDERAL \nCOMISSÃO DE CONSTITUIÇÃO, JUSTIÇA E CIDADANIA \n \nPROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019 \n \nEMENDA SUPRESSIVA \n \n \n \nSuprima-se: \nI - As alterações ao art. 239 da CF, constantes do art. 1º da PEC 6/2019; \nII – a expressão “E o acesso ao abono de que trata o § 3º do art. ',
     ' \n \n \nCOMISSÃO DE CONSTITUIÇÃO, JUSTIÇA E CIDADANIA \n \n \nPROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019 \n \n \nEMENDA MODIFICATIVA Nº \n \nI – Dê-se ao § 19 do art. 40 da CF, alterado pelo  art. 1º, a \nseguinte redação: \n \n“§ 19. Observados critérios a serem estabelecidos em lei do \nrespectivo ente fede',
   ' \n \n \n \n \nSENADO FEDERAL \nSenador Weverton \n  \n  \nEMENDA MODIFICATIVA - CCJ \n \nPEC n.º 6 de 2019 \nModifica o sistema de previdência \nsocial, estabelece regras de transição e \ndisposições transitórias, e dá outras \nprovidências.  \n \nDê-se ao §5º do art. 40 e ao §8º do art. 201 constantes no art. 1º d',
 ' \n \n \nSENADO FEDERAL \nCOMISSÃO DE CONSTITUIÇÃO, JUSTIÇA E CIDADANIA \n \n \nPROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019 \n \n \nEMENDA SUPRESSIVA Nº  \n \nSuprima-se os §§ 2º,  3º e 5º do art. 24 da PEC 6/2019. \n \nJUSTIFICAÇÃO \n \n \n \nA regra do § 2º e 3º do art. 24 implica na redução da \nparcela acumuláv',
       ' \n \n \nSENADO FEDERAL \nCOMISSÃO DE CONSTITUIÇÃO, JUSTIÇA E CIDADANIA \n \nPROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019 \n \nEMENDA SUPRESSIVA  Nº  \n \nSuprima-se o § 1º do art. 21 da PEC 6/2019, assim redigido: \n \n“§ 1º A partir de 1º de janeiro de 2020, as pontuações a que se referem os \nincisos I a II',
      ' \n \n \nSENADO FEDERAL \nCOMISSÃO DE CONSTITUIÇÃO, JUSTIÇA E CIDADANIA \n \nPROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019 \n \nEMENDA SUPRESSIVA Nº  \n \n \n \nSuprima-se a alteração ao art. 203 da Constituição, constante \ndo art. 1º do Substitutivo, assim redigida: \nArt. 203..................................',
       ' \n \n \nCOMISSÃO DE CONSTITUIÇÃO, JUSTIÇA E CIDADANIA \n \n \nPROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019 \n \n \nEMENDA MODIFICATIVA \n \nDê-se ao art. 26 da PEC 6/2019 a seguinte redação: \n“Art. 26. Para o cálculo dos benefícios do regime próprio de previdência \nsocial da União e do Regime Geral de Previ',
 ...
          'PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019 \n \nEMENDA SUPRESSIVA \n \n \n \nSuprima-se a alteração ao art. 203 da Constituição, constante do art. 1º do \nSubstitutivo, assim redigida: \n \nArt. 203...................................................................................  \n.....................',
            'PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019 \nEMENDA SUPRESSIVA \n \n \n \n \nSuprima-se a alteração ao art. 149 da Constituição constante do art. 1º do \nSubstitutivo, e a expressão “e extraordinárias”, na redação dada ao inciso X do § 22 do \nart. 40 da Constituição, pelo art. 1º; e o § 8º do art. 9º d',
         'PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019 \n \nEMENDA SUPRESSIVA \n \nSuprima-se os §§ 1º a 4º do art. 11 da PEC 6/2019. \n \nJUSTIFICAÇÃO \n \n \n \nO art. 11 da PEC 6/2019, sem qualquer comprovação técnica de sua \nadequação, eleva, de imediato, a alíquota de contribuição dos servidores federais de 11% ',
              'PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019 \n \nEMENDA MODIFICATIVA \n \nI – Dê-se ao § 19 do art. 40 da CF, alterado pelo  art. 1º, a seguinte redação: \n“§ 19. Observados critérios a serem estabelecidos em lei do respectivo ente \nfederativo, o servidor titular de cargo efetivo que tenha completado ',
            'PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019 \n \nEMENDA MODIFICATIVA \n \nDê-se ao inciso IV do “caput” art. 20 a seguinte redação: \n“Art. 20 .................... \n................................ \nIV – período adicional de contribuição de trinta por cento do tempo que, \nna data de entrada em vigor d',
         'PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019 \n \nEMENDA SUPRESSIVA \n \nSuprima-se os incisos III e IV do art. 35 da PEC 6/2019. \n \nJUSTIFICAÇÃO \n \n \n \nA revogação pelos incisos III e IV do art. 35 das regras de transição das \nEC 41/03 e 47/05 afeta drasticamente a expectativa legítima de direito dos',
            'PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019 \n \nEMENDA SUPRESSIVA \n \n \nSuprima-se o inciso II do § 8º do art. 4º da PEC 6/2019, assim redigido: \n“Art. 4º ........................................................................ \n \n§ 8º Considera-se remuneração do servidor público no cargo efetivo, ',
      'PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019 \n \nEMENDA SUPRESSIVA \nSuprima-se: \nI – a alteração ao § 15 do art. 40 da CF, constante do art. 1º da PEC 6/2019; \nII – a alteração ao art. 202 da CF, constante do art. 1º da PEC 6/2019; \nII – o art. 33 da PEC 6/2019. \n \n \nJUSTIFICAÇÃO \n \n \n \n \nA alteraç',
             'PROPOSTA DE EMENDA À CONSTITUIÇÃO Nº 6 DE 2019 \n \nEMENDA MODIFICATIVA \n \nDê-se ao art. 26 da PEC 6/2019 a seguinte redação: \n“Art. 26. Para o cálculo dos benefícios do regime próprio de previdência \nsocial da União e do Regime Geral de Previdência Social, será utilizada a \nmédia aritmética simples d',
  ' \n \n \n \n \nSENADO FEDERAL \nSenador Weverton \n  \n  \nEMENDA ADITIVA - CCJ \n \nPEC n.º 6 de 2019 \nModifica o sistema de previdência \nsocial, estabelece regras de transição e \ndisposições transitórias, e dá outras \nprovidências.  \n \nInclua-se o art. 20-A na PEC 06 de 2019, com a seguinte redação:  \nArt. 2']
Length: 119, dtype: str

In [5]:
pattern = r"""
(?:à\s+
    (?:
        PEC\s*n[º°o]?\s*0?6(?:,\s*(?:de\s*)?2019)?
        |
        Proposta\s+de\s+Emenda\s+à\s+Constituição\s*n[º°o]?\s*0?6,\s*de\s*2019
    )
)
|
EMENDA\s+
(?:
    SUPRESSIVA
    |
    MODIFICATIVA
    |
    ADITIVA
    |
    N\.?[º°o]?\s*
    (?:_+|\d+)?
    \s*(?:[-–]\s*CCJ|/CCJ)?
)
|
\(?\s*PEC\s*6\s*/\s*2019\s*\)?
|
\(Do\s+Sr\.?\s+Randolfe\s+Rodrigues\s+e\s+outros\)
|
À\s+PEC\s+N[º°o]?\s*0?6,\s*de\s*2019\.\s*\n\s*\([^\n]+\)
"""

In [6]:
pattern = (
    "(à PEC nº 6, 2019)|"
    "(à PEC nº 6, de 2019)|"
"(à Proposta de Emenda à Constituição nº 6, de 2019)|"
"EMENDA SUPRESSIVA|"
"EMENDA MODIFICATIVA|"
"EMENDA ADITIVA|"
"EMENDA Nº    - CCJ|"
"EMENDA Nº     - CCJ|"
"EMENDA N.º _______/CCJ|"
"\(PEC 6\/2019|"
"\(Do Sr. Randolfe Rodrigues e outros\)|"
"À PEC Nº 06, de 2019\. \n\s*\([^\n]+\)|"
"(PEC\s+n.º\s+6\s+de\s+2019|À\s+Proposta\s+de\s+Emenda\s+à\s+Constituição\s+nº\s+6/2019\s+que)\s+modifica\s+o\s+sistema\s+de\s+previdência\s+social[\s\S]+provid[eê]ncias")
print(len(pec[~pec.texto.str.contains(pattern, case=False)]))

0

<>:11: SyntaxWarning: invalid escape sequence '\('
<>:12: SyntaxWarning: invalid escape sequence '\('
<>:13: SyntaxWarning: invalid escape sequence '\.'
<>:14: SyntaxWarning: invalid escape sequence '\s'
<>:11: SyntaxWarning: invalid escape sequence '\('
<>:12: SyntaxWarning: invalid escape sequence '\('
<>:13: SyntaxWarning: invalid escape sequence '\.'
<>:14: SyntaxWarning: invalid escape sequence '\s'
C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_7272\596253113.py:11: SyntaxWarning: invalid escape sequence '\('
  "\(PEC 6\/2019|"
C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_7272\596253113.py:12: SyntaxWarning: invalid escape sequence '\('
  "\(Do Sr. Randolfe Rodrigues e outros\)|"
C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_7272\596253113.py:13: SyntaxWarning: invalid escape sequence '\.'
  "À PEC Nº 06, de 2019\. \n\s*\([^\n]+\)|"
C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_7272\596253113.py:14: SyntaxWarning: invalid escape sequence '\s'
  "(PEC\s+n.º\s+6\s+de\s+2019|À\s+Proposta\s+de\s+Emenda\s+à\s+Constituição\s+nº\s+6/2019\s+que)\s+modifica\s+o\s+sistema\s+de\s+previdência\s+social[\s\S]+provid[eê]ncias")
C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_7272\596253113.py:15: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  print(len(pec[~pec.texto.str.contains(pattern, case=False)]))

In [7]:
for v in pec[~pec.texto.str.contains(pattern)].texto.str[:700].values:
    print(v)
    print("="*100)

SENADO FEDERAL
Senador Weverton

EMENDA ADITIVIA - CCJ
PEC n.º 6 de 2019
Modifica o sistema de previdência
social, estabelece regras de transição e
disposições transitórias, e dá outras
providências.
Art. 1º. - O art. 1º desta Emenda à Constituição passa a vigorar com a seguinte
redação:
Art. 1º .........................................................................................................
Art. 40. .............................................................................................
§ 1º .......................................................................................
..........................................................................
====================================================================================================

C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_7272\1196289154.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  for v in pec[~pec.texto.str.contains(pattern)].texto.str[:700].values:

## Pré-processamento

### Remover cabeçalho

#### Padrão geral

In [8]:
pattern = (
    "(à PEC nº 6, 2019)|"
    "(à PEC nº 6, de 2019)|"
"(à Proposta de Emenda à Constituição nº 6, de 2019)|"
"EMENDA SUPRESSIVA|"
"EMENDA MODIFICATIVA|"
"EMENDA ADITIVA|"
"EMENDA Nº    - CCJ|"
"EMENDA Nº     - CCJ|"
"EMENDA N.º _______/CCJ|"
"\(PEC 6\/2019|"
"\(Do Sr. Randolfe Rodrigues e outros\)|"
"À PEC Nº 06, de 2019\. \n\s*\([^\n]+\)|"
"(PEC\s+n.º\s+6\s+de\s+2019|À\s+Proposta\s+de\s+Emenda\s+à\s+Constituição\s+nº\s+6/2019\s+que)\s+modifica\s+o\s+sistema\s+de\s+previdência\s+social[\s\S]+provid[eê]ncias")
pec[~pec.texto.str.contains(pattern, case=False)]

<>:11: SyntaxWarning: invalid escape sequence '\('
<>:12: SyntaxWarning: invalid escape sequence '\('
<>:13: SyntaxWarning: invalid escape sequence '\.'
<>:14: SyntaxWarning: invalid escape sequence '\s'
<>:11: SyntaxWarning: invalid escape sequence '\('
<>:12: SyntaxWarning: invalid escape sequence '\('
<>:13: SyntaxWarning: invalid escape sequence '\.'
<>:14: SyntaxWarning: invalid escape sequence '\s'
C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_7272\3285442828.py:11: SyntaxWarning: invalid escape sequence '\('
  "\(PEC 6\/2019|"
C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_7272\3285442828.py:12: SyntaxWarning: invalid escape sequence '\('
  "\(Do Sr. Randolfe Rodrigues e outros\)|"
C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_7272\3285442828.py:13: SyntaxWarning: invalid escape sequence '\.'
  "À PEC Nº 06, de 2019\. \n\s*\([^\n]+\)|"
C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_7272\3285442828.py:14: SyntaxWarning: invalid escape sequence '\s'
  "(PEC\s+n.º\s+6\s+de\s+2019|À\s+Proposta\s+de\s+Emenda\s+à\s+Constituição\s+nº\s+6/2019\s+que)\s+modifica\s+o\s+sistema\s+de\s+previdência\s+social[\s\S]+provid[eê]ncias")
C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_7272\3285442828.py:15: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  pec[~pec.texto.str.contains(pattern, case=False)]

Empty DataFrame
Columns: [num_emenda, materia, nome_arquivo, texto]
Index: []

In [9]:
default_header_pattern =  r"^[\s\S]*?((PEC\s+n\.º\s+6\s+de\s+2019|À\s+Proposta\s+de\s+Emenda\s+à\s+Constituição\s+n[º°o]\s*6\/2019\s+que)\s+modifica\s+o\s+sistema\s+de\s+previdência\s+social[\s\S]+?provid[eê]ncias)|(\(à\s+PEC\s+n[º°o]\s*6,\s*2019\)|\(à\s+PEC\s+n[º°o]\s*6,\s*de\s*2019\)|\(à\s+Proposta\s+de\s+Emenda\s+à\s+Constituição\s+n[º°o]\s*6,\s*de\s*2019\)\s+(Aditiva|Modificativa)?|À\s+PEC\s+N[º°o]\s*06,\s*de\s*2019\.\s*\n\s*\([^\n]+\)|EMENDA\s+N[º°o]\s+CCJ\s+\(PEC\s6\/2019\s+|EMENDA\s+SUPRESSIVA(?:\s*-\s*CCJ|\s+À\s+PEC\s+06/2019\.)?|EMENDA\s+MODIFICATIVA(\s+Nº)?|EMENDA\s+ADITIVA|EMENDA\s+N[º°o\.]*\s*-\s*CCJ\s*\n?\s*(\(à\s+PEC\s+n[º°o]\s*6,\s*de\s*2019\))?(\s*EMENDA.*?\s+À\s+PEC\s+06/2019\.)?|EMENDA\s+N\.º\s*_______\/CCJ|\(PEC\s*6\/2019\)|\(Do\s+Sr\.\s+Randolfe\s+Rodrigues\s+e\s+outros\))"
default_header_regex = re.compile(default_header_pattern, re.VERBOSE | re.IGNORECASE)

In [10]:
print(default_header_pattern)

^[\s\S]*?((PEC\s+n\.º\s+6\s+de\s+2019|À\s+Proposta\s+de\s+Emenda\s+à\s+Constituição\s+n[º°o]\s*6\/2019\s+que)\s+modifica\s+o\s+sistema\s+de\s+previdência\s+social[\s\S]+?provid[eê]ncias)|(\(à\s+PEC\s+n[º°o]\s*6,\s*2019\)|\(à\s+PEC\s+n[º°o]\s*6,\s*de\s*2019\)|\(à\s+Proposta\s+de\s+Emenda\s+à\s+Constituição\s+n[º°o]\s*6,\s*de\s*2019\)\s+(Aditiva|Modificativa)?|À\s+PEC\s+N[º°o]\s*06,\s*de\s*2019\.\s*\n\s*\([^\n]+\)|EMENDA\s+N[º°o]\s+CCJ\s+\(PEC\s6\/2019\s+|EMENDA\s+SUPRESSIVA(?:\s*-\s*CCJ|\s+À\s+PEC\s+06/2019\.)?|EMENDA\s+MODIFICATIVA(\s+Nº)?|EMENDA\s+ADITIVA|EMENDA\s+N[º°o\.]*\s*-\s*CCJ\s*\n?\s*(\(à\s+PEC\s+n[º°o]\s*6,\s*de\s*2019\))?(\s*EMENDA.*?\s+À\s+PEC\s+06/2019\.)?|EMENDA\s+N\.º\s*_______\/CCJ|\(PEC\s*6\/2019\)|\(Do\s+Sr\.\s+Randolfe\s+Rodrigues\s+e\s+outros\))

In [11]:
def split_header(text, regex=default_header_regex):
    if pd.isna(text):
        return pd.Series([None, None])

    match = regex.search(text)

    if match:
        fim = match.end()

        # inclui o termo encontrado no cabeçalho
        cabecalho = text[:fim].strip()

        # restante após o termo
        texto_sem_cabecalho = text[fim:].strip()

        return pd.Series([cabecalho, texto_sem_cabecalho])

    return pd.Series([None, text])

In [12]:
pec[["cabecalho", "texto_sem_cabecalho"]] = (
    pec["texto"]
    .apply(split_header)
)

In [13]:
pec.texto_sem_cabecalho

0      Suprima-se os §§ 2º,  3º e 5º do art. 24 da PE...
1      Dê-se ao art. 34 da PEC 6/2019 a seguinte reda...
2      Suprimam-se os §§ § 6º, 7º, 8º e 9° do art. 8°...
3      Acrescente-se os seguintes artigos à Proposta ...
4      Dê-se aos §§ 3º, 7º, 14 e 19 do artigo 40 da C...
                             ...
264    Suprima-se os incisos III e IV do art. 35 da P...
265    Suprima-se o inciso II do § 8º do art. 4º da P...
266    Suprima-se: \nI – a alteração ao § 15 do art. ...
267    Dê-se ao art. 26 da PEC 6/2019 a seguinte reda...
268    .  \n \nInclua-se o art. 20-A na PEC 06 de 201...
Name: texto_sem_cabecalho, Length: 269, dtype: str

#### Exceções

In [14]:
len(pec[pec.cabecalho.isna()])

0

### Checagem da primeira palavra do texto sem cabeçalho

In [15]:
start_patterns = sorted(set(pec.texto_sem_cabecalho.str.split().str[0]))
start_patterns

['.',
 'Acrescente',
 'Acrescente-se',
 'Acrescente-se,',
 'Acrescentem-se',
 'Altera-se',
 'Altere-se',
 'Alterem-se,',
 'Art',
 'Art.',
 'Deem-se',
 'Dê-se',
 'Emenda',
 'Fica',
 'I',
 'Inclua-se',
 'Inclua-se,',
 'Inclui',
 'Insira-se',
 'Modifica',
 'Modifiquem-se',
 'No',
 'Nº',
 'O',
 'Substitua-se',
 'Supressiva',
 'Suprima-se',
 'Suprima-se:',
 'Suprimam-se',
 'Suprimem-se,',
 'Surpima-se',
 'Surpima-se,',
 'À']

#### Remover ementa

In [16]:
print(len(pec[pec["texto_sem_cabecalho"].str.contains("Modifica o sistema de previdência")]))

0

### Remover dados do corpo

#### Remover gabinete

In [17]:
print(len(pec[pec.texto_sem_cabecalho.str.contains("Gabinete d")]))

38

In [18]:
trechos_com_gabinete = (
    pec.loc[
        pec["texto_sem_cabecalho"].str.contains("Gabinete d", na=False),
        "texto_sem_cabecalho"
    ]
    .str.extract(r"(.{0,20}Gabinete d.{0,20})", expand=False)
)

print(trechos_com_gabinete.tolist())

['Gabinete do Senador Lasier Mar', 'Gabinete do Senador Humberto C', 'Gabinete do Senador Humberto C', 'Gabinete do Senador Humberto C', 'Gabinete do Senador Humberto C', 'Gabinete do Senador MARCOS ROG', 'Gabinete do Senador PAULO PAIM', 'Gabinete do Senador PAULO PAIM', 'Gabinete do Senador PAULO PAIM', 'Gabinete do Senador PAULO PAIM', 'Gabinete do Senador PAULO PAIM', 'Gabinete do Senador PAULO PAIM', 'Gabinete do Senador PAULO PAIM', 'Gabinete do Senador PAULO PAIM', 'Gabinete do Senador PAULO PAIM', 'Gabinete do Senador PAULO PAIM', 'Gabinete do Senador PAULO PAIM', 'Gabinete do Senador PAULO PAIM', 'Gabinete do Senador Luis Carlo', 'Gabinete do Senador Rogério Ca', 'Gabinete do Senador Rogério Ca', 'Gabinete do Senador Rogério Ca', 'Gabinete do Senador Rogério Ca', 'Gabinete do Senador Rogério Ca', 'Gabinete do Senador Rogério Ca', 'Gabinete do Senador Rogério Ca', 'Gabinete do Senador Humberto C', 'Gabinete do Senador Humberto C', 'Gabinete do Senador Humberto C', 'Gabinete do Senador Humberto C', 'SENADO FEDERAL – Gabinete do Senador Mecias de ', 'Gabinete do Senador Lasier Mar', 'Gabinete do Senador JADER BARB', 'Gabinete do Senador Humberto C', 'Gabinete do Senador Humberto C', 'Gabinete do Senador Humberto C', 'Gabinete do Senador Angelo Cor', 'Gabinete do Senador Angelo Cor']

In [19]:
def remove_gabinete(text):
    pattern = r'([\s\r\n]*Senado Federal[\s\r\n]*)?(?:Gabinete\s*(?:d[oa]\s*)?Senadora?\s+[a-zA-Zà-úÀ-Ú ]+[\s\r\n]+)'
    return re.sub(pattern, '', text, flags=re.IGNORECASE | re.MULTILINE)

In [20]:
mask = pec["texto_sem_cabecalho"].str.contains("Gabinete d", na=False)

# linhas com "Gabinete d"
pec.loc[mask, "texto_preprocessado"] = (
    pec.loc[mask, "texto_sem_cabecalho"]
       .apply(remove_gabinete)
)

# linhas sem "Gabinete d"
pec.loc[~mask, "texto_preprocessado"] = (
    pec.loc[~mask, "texto_sem_cabecalho"]
)

trechos_restantes = (
    pec.loc[
        pec["texto_preprocessado"].str.contains("Gabinete d", na=False),
        "texto_preprocessado"
    ]
    .str.findall(r".{0,20}Gabinete d.{0,20}")
)

print(trechos_restantes.tolist())

[]

#### Tag do LexEdit

In [21]:
pec.head().texto_preprocessado

0    Suprima-se os §§ 2º,  3º e 5º do art. 24 da PE...
1    Dê-se ao art. 34 da PEC 6/2019 a seguinte reda...
2    Suprimam-se os §§ § 6º, 7º, 8º e 9° do art. 8°...
3    Acrescente-se os seguintes artigos à Proposta ...
4    Dê-se aos §§ 3º, 7º, 14 e 19 do artigo 40 da C...
Name: texto_preprocessado, dtype: str

In [22]:
print(len(pec[pec.texto_preprocessado.str.contains("SF/")]))

269

In [23]:
pec.texto_preprocessado.values[0][-50:]

'GNER \nPT – BA  \nSF/19585.65892-18\n00100\nPEC 6/2019'

In [24]:
trechos_com_tag = (
    pec.loc[
        pec["texto_preprocessado"].str.contains(r"SF/\d+\.\d+-\d{2}", na=False),
        "texto_preprocessado"
    ]
    # Regex atualizada que aceita dinamicamente os dois casos
    .str.extractall(r"([\s\S]{0,40}SF/\d+\.\d+-\d{2}(?:\s+\d+\s+PEC\s+6/2019)?[\s\S]{0,40})")
)

print(trechos_com_tag[0].tolist()[:10])

['ssão, \nSenador JAQUES WAGNER \nPT – BA  \nSF/19585.65892-18\n00100\nPEC 6/2019', 'egimes próprios de Previdência Social. \nSF/19555.44275-07\n00101\nPEC 6/2019\n\n \n \nOs atuais servidores filiados a es', 'ssão, \nSenador JAQUES WAGNER \nPT – BA  \nSF/19555.44275-07', 'nalidade das mudanças pretendidas pela \nSF/19828.59769-90\n00102\nPEC 6/2019\n\nProposta de Emenda à Constituição nº 6', 'onto de contribuição previdência sobre \nSF/19828.59769-90\n\nvalores indenizatórios devidos aos ani', 'so, o deferimento da isenção, mesmo na \nSF/19828.59769-90\n\nausência de requerimento do interessad', '\ntribunais superiores sobre o assunto: \nSF/19828.59769-90\n\n“ADMINISTRATIVO. \nANISTIA POLÍTICA. \nD', 'rentes origens e fundamentos. Por essa \nSF/19828.59769-90\n\nrazão, não há nenhuma ilegalidade em c', 'ração integral às vítimas da ditadura: \nSF/19828.59769-90\n\n“De início, surge relevante para a sol', 'RMENTO, Daniel & SARLET, Ingo Wolfgang \nSF/19828.59769-90\n\n(Coordenadores). Direitos Fundamentais']

In [25]:
def remove_lexedit_tag(text):
    cleaned = re.sub(r'SF/\d+\.\d+-\d{2}(?:\s+\d+\s+PEC\s+6/2019)?', '', text)
    return cleaned

In [26]:
pec["texto_preprocessado"] = pec.texto_preprocessado.apply(remove_lexedit_tag)

In [27]:
print(len(pec[pec.texto_preprocessado.str.contains("SF/")]))

0

#### Assinatura Digital

In [28]:
print(len(pec[pec.texto_preprocessado.str.contains("Assinado eletronicamente")]))

0

#### Endereço

In [29]:
pec[pec.texto_preprocessado.str.contains("Praça|CEP|Ala|Gabinete")]

,num_emenda,materia,nome_arquivo,texto,cabecalho,texto_sem_cabecalho,texto_preprocessado
3,103,PEC_6_2019,EMENDA_103_-_PEC_6_2019.txt,\nSENADO FEDERAL \nGabinete do Senador Lasier...,SENADO FEDERAL \nGabinete do Senador Lasier Ma...,Acrescente-se os seguintes artigos à Proposta ...,Acrescente-se os seguintes artigos à Proposta ...
4,104,PEC_6_2019,EMENDA_104_-_PEC_6_2019.txt,\nGabinete do Senador Humberto Costa \n \n \n...,Gabinete do Senador Humberto Costa \n \n \n \n...,"Dê-se aos §§ 3º, 7º, 14 e 19 do artigo 40 da C...","Dê-se aos §§ 3º, 7º, 14 e 19 do artigo 40 da C..."
5,105,PEC_6_2019,EMENDA_105_-_PEC_6_2019.txt,\nGabinete do Senador Humberto Costa \n \n \n...,Gabinete do Senador Humberto Costa \n \n \n \n...,Acrescente-se ao artigo 201 da Constituição Fe...,Acrescente-se ao artigo 201 da Constituição Fe...
6,106,PEC_6_2019,EMENDA_106_-_PEC_6_2019.txt,\nGabinete do Senador Humberto Costa \n \n \n...,Gabinete do Senador Humberto Costa \n \n \n \n...,"Dê-se ao aos §§ 1º, 1º-A, 1º-B e 1º-C do artig...","Dê-se ao aos §§ 1º, 1º-A, 1º-B e 1º-C do artig..."
7,107,PEC_6_2019,EMENDA_107_-_PEC_6_2019.txt,\nGabinete do Senador Humberto Costa \n \n \n...,Gabinete do Senador Humberto Costa \n \n \n \n...,Acrescente-se ao artigo 40 da Constituição Fed...,Acrescente-se ao artigo 40 da Constituição Fed...
30,128,PEC_6_2019,EMENDA_128_-_PEC_6_2019.txt,\n \n \n \nS E N A D O F E D E R A L \nGabi...,S E N A D O F E D E R A L \nGabinete do Sena...,"Inclua-se, onde couber, na PEC nº6, de 2019, o...","Inclua-se, onde couber, na PEC nº6, de 2019, o..."
31,129,PEC_6_2019,EMENDA_129_-_PEC_6_2019.txt,\n \n SENADO FEDERAL \n \nGabinete d...,SENADO FEDERAL \n \nGabinete do Senador PAULO ...,Dê-se ao inciso IV do caput do art. 20 da PEC ...,Dê-se ao inciso IV do caput do art. 20 da PEC ...
33,130,PEC_6_2019,EMENDA_130_-_PEC_6_2019.txt,\n \n \n \n \n \n SENADO FEDERAL \n ...,SENADO FEDERAL \n \nGabinete do Senador PAULO ...,Acrescente-se o seguinte § 1º-D ao art. 149 da...,Acrescente-se o seguinte § 1º-D ao art. 149 da...
34,131,PEC_6_2019,EMENDA_131_-_PEC_6_2019.txt,\n \n SENADO FEDERAL \n \nGabinete d...,SENADO FEDERAL \n \nGabinete do Senador PAULO ...,"Acrescente-se ao art. 26 da PEC nº 6, de 2019,...","Acrescente-se ao art. 26 da PEC nº 6, de 2019,..."
35,132,PEC_6_2019,EMENDA_132_-_PEC_6_2019.txt,\n \n SENADO FEDERAL \n \nGabinete d...,SENADO FEDERAL \n \nGabinete do Senador PAULO ...,"Alterem-se, onde couber, na Proposta de Emenda...","Alterem-se, onde couber, na Proposta de Emenda..."
36,133,PEC_6_2019,EMENDA_133_-_PEC_6_2019.txt,\n \n \n \n \n \n SENADO FEDERAL \n ...,SENADO FEDERAL \n \nGabinete do Senador PAULO ...,Suprima-se o parágrafo único do art. 203 da Co...,Suprima-se o parágrafo único do art. 203 da Co...
37,134,PEC_6_2019,EMENDA_134_-_PEC_6_2019.txt,\n \n SENADO FEDERAL \n \nGabinete d...,SENADO FEDERAL \n \nGabinete do Senador PAULO ...,Suprima-se o § 2º do artigo 25 da PEC 06/2019....,Suprima-se o § 2º do artigo 25 da PEC 06/2019....
38,135,PEC_6_2019,EMENDA_135_-_PEC_6_2019.txt,\n \n SENADO FEDERAL \n \nGabinete d...,SENADO FEDERAL \n \nGabinete do Senador PAULO ...,Suprima-se o art. 26 da Proposta de Emenda à C...,Suprima-se o art. 26 da Proposta de Emenda à C...
39,136,PEC_6_2019,EMENDA_136_-_PEC_6_2019.txt,\n \n \n \n \n \n SENADO FEDERAL \n ...,SENADO FEDERAL \n \nGabinete do Senador PAULO ...,Suprima-se o inciso III do § 2º do art. 26 da ...,Suprima-se o inciso III do § 2º do art. 26 da ...
41,138,PEC_6_2019,EMENDA_138_-_PEC_6_2019.txt,\n \n SENADO FEDERAL \n \nGabinete d...,SENADO FEDERAL \n \nGabinete do Senador PAULO ...,Suprima-se na integralidade as expressões “e o...,Suprima-se na integralidade as expressões “e o...
42,139,PEC_6_2019,EMENDA_139_-_PEC_6_2019.txt,\n \n SENADO FEDERAL \n \nGabinete d...,SENADO FEDERAL \n \nGabinete do Senador PAULO ...,Suprima-se: \n \n \n \nI – a expressão “quando...,Suprima-se: \n \n \n \nI – a expressão “quando...
44,140,PEC_6_2019,EMENDA_140_-_PEC_6_2019.txt,\n \n SENADO FEDERAL \n \nGabinete d...,SENADO FEDERAL \n \nGabinete do Senador PAULO ...,Suprima-se o § 14 do artigo 37 da PEC 06/2019....,Suprima-se o § 14 do artigo 37 da PEC 06/2019....
45,141,PEC_6_2019,EMENDA_141_-_PEC_6_2019.txt,\n \n SENADO FEDERAL \n \nGabinete d...,SENADO FEDERAL \n \nGabinete do Senador PAULO ...,Suprima-se o termo “ou ocupação e o enquadrame...,Suprima-se o termo “ou ocupação e o enquadrame...
47,143,PEC_6_2019,EMENDA_143_-_PEC_6_2019.txt,\n \nSENADO FEDERAL \nGabinete Senador Rodrig...,SENADO FEDERAL \nGabinete Senador Rodrigo Cunh...,Suprima-se a alteração ao § 3º do art. 109 da ...,Suprima-se a alteração ao § 3º do art. 109 da ...
48,144,PEC_6_2019,EMENDA_144_-_PEC_6_2019.txt,\n \nSENADO FEDERAL \nGabinete Senador Rodrig...,SENADO FEDERAL \nGabinete Senador Rodrigo Cunh...,Suprima-se o parágrafo único do art. 203 da Co...,Suprima-se o parágrafo único do art. 203 da Co...
49,145,PEC_6_2019,EMENDA_145_-_PEC_6_2019.txt,\n \nSENADO FEDERAL \nGabinete Senador Rodrig...,SENADO FEDERAL \nGabinete Senador Rodrigo Cunh...,Suprima-se a expressão “quando se tratar da ún...,Suprima-se a expressão “quando se tratar da ún...
60,155,PEC_6_2019,EMENDA_155_-_PEC_6_2019.txt,\n \nSENADO FEDERAL \nGabinete Senador Rodrig...,SENADO FEDERAL \nGabinete Senador Rodrigo Cunh...,No art. 26 da Proposta de Emenda à Constituiçã...,No art. 26 da Proposta de Emenda à Constituiçã...
62,157,PEC_6_2019,EMENDA_157_-_PEC_6_2019.txt,\nSENADO FEDERAL \nGabinete do Senador CARLOS...,SENADO FEDERAL \nGabinete do Senador CARLOS VI...,Dê-se a seguinte redação ao § 7º do art. 40 da...,Dê-se a seguinte redação ao § 7º do art. 40 da...
63,158,PEC_6_2019,EMENDA_158_-_PEC_6_2019.txt,\nSENADO FEDERAL \nGabinete do Senador CARLOS...,SENADO FEDERAL \nGabinete do Senador CARLOS VI...,Dê-se ao parágrafo único do art. 203 da Consti...,Dê-se ao parágrafo único do art. 203 da Consti...
85,178,PEC_6_2019,EMENDA_178_-_PEC_6_2019.txt,\nGabinete do Senador Luis Carlos Heinze \n \...,Gabinete do Senador Luis Carlos Heinze \n \n \...,Acrescente-se o seguinte artigo 6º-A a Propost...,Acrescente-se o seguinte artigo 6º-A a Propost...
101,192,PEC_6_2019,EMENDA_192_-_PEC_6_2019.txt,\nSENADO FEDERAL \nGabinete do Senador Rogéri...,SENADO FEDERAL \nGabinete do Senador Rogério C...,Dê-se ao caput do art. 26 da Proposta de Emend...,Dê-se ao caput do art. 26 da Proposta de Emend...
103,194,PEC_6_2019,EMENDA_194_-_PEC_6_2019.txt,\nSENADO FEDERAL \nGabinete do Senador Rogéri...,SENADO FEDERAL \nGabinete do Senador Rogério C...,Acrescente-se o seguinte artigo 115 ao Ato das...,Acrescente-se o seguinte artigo 115 ao Ato das...
112,201,PEC_6_2019,EMENDA_201_-_PEC_6_2019.txt,\nSENADO FEDERAL \nGabinete do Senador Rogéri...,SENADO FEDERAL \nGabinete do Senador Rogério C...,Acrescente-se ao art. 35 da Proposta de Emenda...,Acrescente-se ao art. 35 da Proposta de Emenda...
113,202,PEC_6_2019,EMENDA_202_-_PEC_6_2019.txt,\nSENADO FEDERAL \nGabinete do Senador Rogéri...,SENADO FEDERAL \nGabinete do Senador Rogério C...,Acrescente-se o art. 4º-A na Proposta de Emend...,Acrescente-se o art. 4º-A na Proposta de Emend...
114,203,PEC_6_2019,EMENDA_203_-_PEC_6_2019.txt,\nSENADO FEDERAL \nGabinete do Senador Rogéri...,SENADO FEDERAL \nGabinete do Senador Rogério C...,Acrescente-se o art. 17-A na Proposta de Emend...,Acrescente-se o art. 17-A na Proposta de Emend...
116,205,PEC_6_2019,EMENDA_205_-_PEC_6_2019.txt,\nSENADO FEDERAL \nGabinete do Senador Rogéri...,SENADO FEDERAL \nGabinete do Senador Rogério C...,"Acrescente-se o art. 4º-A à PEC nº 06, de 2019...","Acrescente-se o art. 4º-A à PEC nº 06, de 2019..."
117,206,PEC_6_2019,EMENDA_206_-_PEC_6_2019.txt,\nSENADO FEDERAL \nGabinete do Senador Rogéri...,SENADO FEDERAL \nGabinete do Senador Rogério C...,Acrescente-se no art. 1º da Proposta de Emenda...,Acrescente-se no art. 1º da Proposta de Emenda...
142,229,PEC_6_2019,EMENDA_229_-_PEC_6_2019.txt,\nSENADO FEDERAL \nGabinete do Senador CID GO...,SENADO FEDERAL \nGabinete do Senador CID GOMES...,"Modifica o § 1º e suprime os § 2º e 3º, todos ...","Modifica o § 1º e suprime os § 2º e 3º, todos ..."
189,28,PEC_6_2019,EMENDA_28_-_PEC_6_2019.txt,\nGabinete do Senador Humberto Costa \n \n \n...,Gabinete do Senador Humberto Costa \n \n \n \n...,"Acrescente-se, onde couber, na PEC nº 6, de 20...","Acrescente-se, onde couber, na PEC nº 6, de 20..."
190,29,PEC_6_2019,EMENDA_29_-_PEC_6_2019.txt,\nGabinete do Senador Humberto Costa \n \n \n...,Gabinete do Senador Humberto Costa \n \n \n \n...,"Acrescente-se, onde couber, na PEC nº 6, de 20...","Acrescente-se, onde couber, na PEC nº 6, de 20..."
193,31,PEC_6_2019,EMENDA_31_-_PEC_6_2019.txt,\nGabinete do Senador Humberto Costa \n \n \n...,Gabinete do Senador Humberto Costa \n \n \n \n...,Suprimam-se o caput e o § 1º do art. 26 da PEC...,Suprimam-se o caput e o § 1º do art. 26 da PEC...
194,32,PEC_6_2019,EMENDA_32_-_PEC_6_2019.txt,\nGabinete do Senador Humberto Costa \n \n \n...,Gabinete do Senador Humberto Costa \n \n \n \n...,Dê-se ao inciso IV do caput do art. 20 da PEC ...,Dê-se ao inciso IV do caput do art. 20 da PEC ...
195,33,PEC_6_2019,EMENDA_33_-_PEC_6_2019.txt,\nSenador MECIAS DE JESUS \n \n \n \nSENADO F...,Senador MECIAS DE JESUS \n \n \n \nSENADO FEDE...,Art. 1º Dê-se a seguinte redação aos arts. 40 ...,Art. 1º Dê-se a seguinte redação aos arts. 40 ...
211,48,PEC_6_2019,EMENDA_48_-_PEC_6_2019.txt,\nSENADO FEDERAL \nGabinete do Senador Lasier...,SENADO FEDERAL \nGabinete do Senador Lasier Ma...,Acrescente os seguintes artigos à Proposta de ...,Acrescente os seguintes artigos à Proposta de ...
212,49,PEC_6_2019,EMENDA_49_-_PEC_6_2019.txt,\nSENADO FEDERAL \nGabinete do Senador CARLOS...,SENADO FEDERAL \nGabinete do Senador CARLOS VI...,Inclua-se o seguinte art. 26-A à Proposta de E...,Inclua-se o seguinte art. 26-A à Proposta de E...
213,4,PEC_6_2019,EMENDA_4_-_PEC_6_2019.txt,\nSENADO FEDERAL ...,SENADO FEDERAL ...,"Suprimem-se, na Proposta de Emenda à Constitui...","Suprimem-se, na Proposta de Emenda à Constitui..."
218,54,PEC_6_2019,EMENDA_54_-_PEC_6_2019.txt,\nGabinete do Senador Humberto Costa \n \n \n...,Gabinete do Senador Humberto Costa \n \n \n \n...,"Dê-se ao art. 10, § 2º, II, ao art. 19, § 1º, ...","Dê-se ao art. 10, § 2º, II, ao art. 19, § 1º, ..."
219,55,PEC_6_2019,EMENDA_55_-_PEC_6_2019.txt,\nGabinete do Senador Humberto Costa \n \n \n...,Gabinete do Senador Humberto Costa \n \n \n \n...,Supressiva \nSuprima-se o inciso III do § 2º d...,Supressiva \nSuprima-se o inciso III do § 2º d...
220,56,PEC_6_2019,EMENDA_56_-_PEC_6_2019.txt,\nGabinete do Senador Humberto Costa \n \n \n...,Gabinete do Senador Humberto Costa \n \n \n \n...,"Acrescente-se ao art. 26 da PEC nº 6, de 2019,...","Acrescente-se ao art. 26 da PEC nº 6, de 2019,..."
224,5,PEC_6_2019,EMENDA_5_-_PEC_6_2019.txt,\nSENADO FEDERAL \nGabinete do Senador CARLOS...,SENADO FEDERAL \nGabinete do Senador CARLOS VI...,Art. 1º O art. 142 da Constituição passa a vig...,Art. 1º O art. 142 da Constituição passa a vig...
230,65,PEC_6_2019,EMENDA_65_-_PEC_6_2019.txt,\nGabinete do Senador Angelo Coronel \n \n \n...,Gabinete do Senador Angelo Coronel \n \n \n \n...,Dê-se ao inciso IV do caput do art. 20 da Prop...,Dê-se ao inciso IV do caput do art. 20 da Prop...
231,66,PEC_6_2019,EMENDA_66_-_PEC_6_2019.txt,\nGabinete do Senador Angelo Coronel \n \n \n...,Gabinete do Senador Angelo Coronel \n \n \n \n...,Dê-se nova redação ao caput do art. 23; e supr...,Dê-se nova redação ao caput do art. 23; e supr...

In [30]:
trechos_com_endereco = (
    pec.loc[
        pec["texto_preprocessado"].str.contains(r"Praça\s|CEP\s|Ala\s|Gabinete\s", na=False),
        "texto_preprocessado"
    ]
    # Regex atualizada que aceita dinamicamente os dois casos
    .str.extractall(r"([\s\S]{0,70}(Praça\s|CEP\s|Ala\s|Gabinete\s)[\s\S]{0,70})")
)

print(trechos_com_endereco[0].tolist())

['válidos para o servidor público federal. \nSenado Federal – Anexo II – Ala Senador Alexandre Costa – Gabinete 3 \nCEP 70165-900 – Brasília DF \nPar', '$ 90 bilhões dos Estados e cerca de R$ 8 \nSenado Federal – Anexo II – Ala Senador Alexandre Costa – Gabinete 3 \nCEP 70165-900 – Brasília DF \nbil', '................................” (NR) \n\n\n \nSenado Federal, Anexo II, Ala Senador Ruy Carneiro, gabinete 01 | Praça dos Três Poderes | CEP 70165', 'ust que, na forma de lei complementar, \n\n\n \nSenado Federal, Anexo II, Ala Filinto Müller, gabinete 01 | Praça dos Três Poderes | CEP 70165-900 |', '............................ (NR)” \n \n \n\n\n \nSenado Federal, Anexo II, Ala Senador Ruy Carneiro, gabinete 01 | Praça dos Três Poderes | CEP 70165', 'ue apresentamos a \npresente emenda.  \n \n\n\n \nSenado Federal, Anexo II, Ala Filinto Müller, gabinete 01 | Praça dos Três Poderes | CEP 70165-900 |', 'S, \nRN e SC.  \n\n\n \n \n \n \nS E N A D O   F E D E R A L \nSenado Federal, Ala Senador Teotõnio Vilela, Anexo II, Gabinete 2, CEP 70165-900, Brasília', 'buição referido no item II, o \nchamado “pedágio”. \nSenado Federal - - Praça dos Três Poderes – Anexo I – 22º Andar - CEP 70165-900 – Brasília – DF', 'com nossos Pares que esta Emenda seja aprovada. \n \nSenado Federal - - Praça dos Três Poderes – Anexo I – 22º Andar - CEP 70165-900 – Brasília – DF', 'enção dos direitos previstos na data do ingresso. \nSenado Federal - - Praça dos Três Poderes – Anexo I – 22º Andar - CEP 70165-900 – Brasília – DF', 'ue essa \ncorreção seja feita à PEC nº 6, de 2019. \nSenado Federal - - Praça dos Três Poderes – Anexo I – 22º Andar - CEP 70165-900 – Brasília – DF', 'retendida por essa Emenda que, ora, apresentamos. \nSenado Federal - - Praça dos Três Poderes – Anexo I – 22º Andar - CEP 70165-900 – Brasília – DF', 'zar o fator de conversão para transformar o tempo \nSenado Federal - - Praça dos Três Poderes – Anexo I – 22º Andar - CEP 70165-900 – Brasília – DF', 'a Pública de 14.08.2019 da \nOAB/RS, in verbis:  \n \nSenado Federal - - Praça dos Três Poderes – Anexo I – 22º Andar - CEP 70165-900 – Brasília – DF', 'ífico-jurídico e de finalidade sociocultural, sem \nSenado Federal - - Praça dos Três Poderes – Anexo I – 22º Andar - CEP 70165-900 – Brasília – DF', 'rejudicar milhares de trabalhadores brasileiros.” \nSenado Federal - - Praça dos Três Poderes – Anexo I – 22º Andar - CEP 70165-900 – Brasília – DF', ' os trabalhadores brasileiros. \nSala da Comissão, \nSenado Federal - - Praça dos Três Poderes – Anexo I – 22º Andar - CEP 70165-900 – Brasília – DF', 'ia das contribuições, a crescida de 2% por ano de \nSenado Federal - - Praça dos Três Poderes – Anexo I – 22º Andar - CEP 70165-900 – Brasília – DF', 'ciadas decorrentes das mais diversas atividades e \nSenado Federal - - Praça dos Três Poderes – Anexo I – 22º Andar - CEP 70165-900 – Brasília – DF', 'e relação de trabalho, ou que receba um benefício \nSenado Federal - - Praça dos Três Poderes – Anexo I – 22º Andar - CEP 70165-900 – Brasília – DF', 'cos concursados, os quais detentores do direito à \nSenado Federal - - Praça dos Três Poderes – Anexo I – 22º Andar - CEP 70165-900 – Brasília – DF', 'ter uma aposentadoria por tempo de \ncontribuição. \nSenado Federal - - Praça dos Três Poderes – Anexo I – 22º Andar - CEP 70165-900 – Brasília – DF', 'nal. As normas modificadas pela reforma não podem \nSenado Federal - - Praça dos Três Poderes – Anexo I – 22º Andar - CEP 70165-900 – Brasília – DF', 'ial, possam ser convertidos, desde que hajam dois \nSenado Federal - - Praça dos Três Poderes – Anexo I – 22º Andar - CEP 70165-900 – Brasília – DF', 'ores \nespecializados e conhecedores da matéria. \n \nSenado Federal - - Praça dos Três Poderes – Anexo I – 22º Andar - CEP 70165-900 – Brasília – DF', 's consolidados do Conselho Nacional de Justiça \n\n\n \n \nSENADO FEDERAL \nGabinete Senador Rodrigo Cunha \n \n \n(CNJ), enquanto quase a metade dos municípi', 'endimento médico e o aumento do custo de vida? \n\n\n \n \nSENADO FEDERAL \nGabinete Senador Rodrigo Cunha \n \n \nEm suma, trata-se de uma norma que precisa ', ' terá valor mensal inferior ao salário mínimo. \n\n\n \n \nSENADO FEDERAL \nGabinete Senador Rodrigo Cunha \n \n \nCertos da relevância econômica e social des', 'rado, do mesmo modo como está proposto para os \n\n\n \n \nSENADO FEDERAL \nGabinete Senador Rodrigo Cunha \n \n \n \ndemais segurados. O valor será de 100% ap', 'ciários. Há maiores óbices que \n\n\n \n \n \n \nSenado Federal – Anexo II – Ala Teotônio Vilela, Gabinete 23 \n70165-900 – Brasília – DF \n2\nos enfrenta', 'ade social, nos termos da lei. \n\n\n \n \n \n \nSenado Federal – Anexo II – Ala Teotônio Vilela, Gabinete 23 \n70165-900 – Brasília – DF \n2\nDiante do e', 'gados da \nadministração municipal. \n \n\n\n \nSenado Federal - Anexo II – Gabinete 5 – Ala Senador Afonso Arinos – Térreo  \n Fones 61 3303 4124 – 4129 - ', 'CEP 70165.900 – Brasília – DF – E-mail: sen.luiscarlosheinze@senado.leg.br', 'a de trabalho ligado a esse regime.  \n\n\n \nSenado Federal - Anexo II – Gabinete 5 – Ala Senador Afonso Arinos – Térreo  \n Fones 61 3303 4124 – 4129 - ', 'CEP 70165.900 – Brasília – DF – E-mail: sen.luiscarlosheinze@senado.leg.br', 'tribuição, \nmas de 100% de todo o período. \nSenado Federal, Anexo II, Ala Teotônio Vilela, Gabinete 12 \nCep 70165-900 - Brasília - DF \n \n \n \n \nA', 'que corresponder ao sócio ou acionista.  \n \nSenado Federal, Anexo II, Ala Teotônio Vilela, Gabinete 12 \nCep 70165-900 - Brasília - DF \n \n \n§ 2º ', 'ração e Desenvolvimento \nEconômico (OCDE). \nSenado Federal, Anexo II, Ala Teotônio Vilela, Gabinete 12 \nCep 70165-900 - Brasília - DF \n \n \n \n \nU', 'correu, justamente, após a aplicação de um \nSenado Federal, Anexo II, Ala Teotônio Vilela, Gabinete 12 \nCep 70165-900 - Brasília - DF \n \n \nduro ', 'ual os economistas do governo e do mercado \nSenado Federal, Anexo II, Ala Teotônio Vilela, Gabinete 12 \nCep 70165-900 - Brasília - DF \n \n \nfinan', 'as sob risco de os congressistas aprovarem \nSenado Federal, Anexo II, Ala Teotônio Vilela, Gabinete 12 \nCep 70165-900 - Brasília - DF \n \n \niniqu', 'mização e de ordem. As regras de transição \nSenado Federal, Anexo II, Ala Teotônio Vilela, Gabinete 12 \nCep 70165-900 - Brasília - DF \n \n \ndevem', 'a para os servidores públicos federais que \nSenado Federal, Anexo II, Ala Teotônio Vilela, Gabinete 12 \nCep 70165-900 - Brasília - DF \n \n \ntenha', ' da Seguridade Social (Contribuição para o \nSenado Federal, Anexo II, Ala Teotônio Vilela, Gabinete 12 \nCep 70165-900 - Brasília - DF \n \n \nFinan', 'dias após o reconhecimento do direito. \n\n\n \nSenado Federal, Anexo II, Ala Filinto Müller, gabinete 01 | Praça dos Três Poderes | CEP 70165-900 |', 'a médica e sem quarentena, mesmo tendo \n\n\n \nSenado Federal, Anexo II, Ala Filinto Müller, gabinete 01 | Praça dos Três Poderes | CEP 70165-900 |', 'om esses verdadeiros heróis nacionais. \n\n\n \nSenado Federal, Anexo II, Ala Filinto Müller, gabinete 01 | Praça dos Três Poderes | CEP 70165-900 |', 'ós a conclusão de seu serviço militar. \n\n\n \nSenado Federal, Anexo II, Ala Filinto Müller, gabinete 01 | Praça dos Três Poderes | CEP 70165-900 |', 'ersos perigos, como minas subterrâneas \n\n\n \nSenado Federal, Anexo II, Ala Filinto Müller, gabinete 01 | Praça dos Três Poderes | CEP 70165-900 |', 'e resulte em situação mais \nfavorável. \n\n\n \nSenado Federal, Anexo II, Ala Filinto Müller, gabinete 01 | Praça dos Três Poderes | CEP 70165-900 |', 'a média após 40 anos de \ncontribuição. \n\n\n \nSenado Federal, Anexo II, Ala Filinto Müller, gabinete 01 | Praça dos Três Poderes | CEP 70165-900 |', 'mo Segunda Reforma da Previdência), 74 \n\n\n \nSenado Federal, Anexo II, Ala Filinto Müller, gabinete 01 | Praça dos Três Poderes | CEP 70165-900 |', ' trinta por cento do tempo faltante. \n \n\n\n \nSenado Federal, Anexo II, Ala Filinto Müller, gabinete 01 | Praça dos Três Poderes | CEP 70165-900 |', 'sional \ne \ninterdisciplinar.  \n\n\n \n \n \n \nSENADO FEDERAL – | Anexo II, Ala Senador Ruy  Carneiro, Gab. 02  \n CEP 70165-900 | Brasília DF I Telef ', 'o respectivo Poder Executivo, \n\n\n \n \n \n \nSENADO FEDERAL – | Anexo II, Ala Senador Ruy  Carneiro, Gab. 02  \n CEP 70165-900 | Brasília DF I Telef ', 'namento do deficit atuarial;  \n\n\n \n \n \n \nSENADO FEDERAL – | Anexo II, Ala Senador Ruy  Carneiro, Gab. 02  \n CEP 70165-900 | Brasília DF I Telef ', 'doria ou da pensão por morte. \n\n\n \n \n \n \nSENADO FEDERAL – | Anexo II, Ala Senador Ruy  Carneiro, Gab. 02  \n CEP 70165-900 | Brasília DF I Telef ', ' caracterização por categoria \n\n\n \n \n \n \nSENADO FEDERAL – | Anexo II, Ala Senador Ruy  Carneiro, Gab. 02  \n CEP 70165-900 | Brasília DF I Telef ', ' forem, respectivamente, \nde: \n\n\n \n \n \n \nSENADO FEDERAL – | Anexo II, Ala Senador Ruy  Carneiro, Gab. 02  \n CEP 70165-900 | Brasília DF I Telef ', 'belecidos na Constituição. Se \n\n\n \n \n \n \nSENADO FEDERAL – | Anexo II, Ala Senador Ruy  Carneiro, Gab. 02  \n CEP 70165-900 | Brasília DF I Telef ', 'à saúde, ou associação destes agentes; e \nSenado Federal – Anexo II – Ala Senador Alexandre Costa – Gabinete 3 \nCEP 70165-900 – Brasília DF \nd) ', 'trata o inciso \nIV do caput do art. 144; \nSenado Federal – Anexo II – Ala Senador Alexandre Costa – Gabinete 3 \nCEP 70165-900 – Brasília DF \nc) ', 'para estes quanto para aqueles que ainda \nSenado Federal – Anexo II – Ala Senador Alexandre Costa – Gabinete 3 \nCEP 70165-900 – Brasília DF \nven', 'de acordo com o substitutivo da Comissão \nSenado Federal – Anexo II – Ala Senador Alexandre Costa – Gabinete 3 \nCEP 70165-900 – Brasília DF \nEsp', ' resultar em nenhum benefício. \n\n\n \n \n \n \nSenado Federal – Anexo II – Ala Teotônio Vilela, Gabinete 23 \n70165-900 – Brasília – DF \n2\nDe outro la', 'ue o constituinte deu ao federalismo. \n(MDB/PA) \n \n \nSenado Federal - Praça dos Três Poderes - Anexo I – 2º Andar CEP 70165-900- Brasília DF \nTele', 'Federal, será concedida aposentadoria: \n\n\n \nSenado Federal, Anexo II, Ala Senador Ruy Carneiro, gabinete 01 | Praça dos Três Poderes | CEP 70165', 'artigo 26 desta Emenda Constitucional. \n\n\n \nSenado Federal, Anexo II, Ala Senador Ruy Carneiro, gabinete 01 | Praça dos Três Poderes | CEP 70165', 'ínima, além do tempo \nde contribuição. \n\n\n \nSenado Federal, Anexo II, Ala Senador Ruy Carneiro, gabinete 01 | Praça dos Três Poderes | CEP 70165', 'lidade no \ncálculo de seus benefícios. \n\n\n \nSenado Federal, Anexo II, Ala Senador Ruy Carneiro, gabinete 01 | Praça dos Três Poderes | CEP 70165', 'valentes, \ndesprezando os 20% menores. \n\n\n \nSenado Federal, Anexo II, Ala Senador Ruy Carneiro, gabinete 01 | Praça dos Três Poderes | CEP 70165', 'quase 50% a mais do que todo o \n\n\n \n \n \n \nSenado Federal – Anexo II – Ala Teotônio Vilela, Gabinete 23 \n70165-900 – Brasília – DF \n2\ngasto com o', 'ercer o direito que lhes é assegurado, sendo que para o servidor \n\n\n \nPraça dos Três Poderes | Senado Federal | Anexo 2 | Ala Senador Afonso Arino', 's | Gabinete 03 | CEP: 70165-900 | Brasília-DF \n \npúblico já é exigida idade mínima', 'm tela penaliza os beneficiários, além da perda do ente querido. \n\n\n \nPraça dos Três Poderes | Senado Federal | Anexo 2 | Ala Senador Afonso Arino', 's | Gabinete 03 | CEP: 70165-900 | Brasília-DF \n \nA redução da renda familiar, de a']

In [31]:
def remove_address(text):
    pattern = r'(?i)(?:S\s*E\s*N\s*A\s*D\s*O\s+F\s*E\s*D\s*E\s*R\s*A\s*L|Senado\s+Federal|Praça\s+dos\s+Três\s+Poderes)(?:[\s,|–-]*(?:Anexo\s+[IVX0-9]+|Ala\s+(?:Senador\s+)?[A-Za-zÀ-ÿ]+(?:\s+[A-Za-zÀ-ÿ]+){0,3}|Gabinete\s+(?:do\s+)?Senador[a]?\s+[A-Za-zÀ-ÿ]+(?:\s+[A-Za-zÀ-ÿ]+){0,2}|Gabinete\s+\d+|Gab\.\s*\d+|\d+º\s+Andar|Térreo|CEP\s*\d{5}(?:[-.]\d{3})?\.?|\d{5}[-.]\d{3}|Brasília(?:\s*[-–|I]*\s*DF)?|Fones?\s*[\d\s.–-]+|Telefones?:\s*\+?\d*|\bBra\b|\bGabine\b|Praça\s+dos\s+Três\s+Poderes|Senado\s+Federal)){1,10}'
    return re.sub(pattern, '', text, flags=re.IGNORECASE | re.MULTILINE)

In [32]:
pec["texto_preprocessado"] = pec.texto_preprocessado.apply(remove_address)

In [33]:
trechos_com_endereco = (
    pec.loc[
        pec.texto_preprocessado.str.contains(r"Praça\s|CEP\s|Ala\s|Gabinete\s", na=False),
        "texto_preprocessado"
    ]
    # Regex atualizada que aceita dinamicamente os dois casos
    .str.extractall(r"([\s\S]{0,80}(Praça\s|CEP\s|Ala\s|Gabinete\s)[\s\S]{0,80})")
)

print(trechos_com_endereco[0].tolist())

[]

In [34]:
pec.to_parquet("../data/datasets/PEC_6_2019_preprocessado.parquet", index=False)