In [9]:
import pandas as pd
from scipy.sparse import load_npz
from tqdm import tqdm
import numpy as np
tqdm.pandas()

# Leitura dos dados

In [2]:
embeddings = pd.read_parquet("../data/datasets/embeddings_v10.parquet")

In [3]:
embedding_cols = [
    'embedding__codefuse_ai__F2LLM_v2_14B__texto',
       'embedding__codefuse_ai__F2LLM_v2_14B__texto_preprocessado',
       'embedding__codefuse_ai__F2LLM_v2_14B__texto_preprocessado_sem_justificativa',
       'embedding__Octen__Octen_Embedding_8B__texto',
       'embedding__Octen__Octen_Embedding_8B__texto_preprocessado',
       'embedding__Octen__Octen_Embedding_8B__texto_preprocessado_sem_justificativa',
       'embedding__Qwen__Qwen3_Embedding_8B__texto',
       'embedding__Qwen__Qwen3_Embedding_8B__texto_preprocessado',
       'embedding__Qwen__Qwen3_Embedding_8B__texto_preprocessado_sem_justificativa',
       'embedding__nvidia__llama_embed_nemotron_8b__texto',
       'embedding__nvidia__llama_embed_nemotron_8b__texto_preprocessado',
       'embedding__nvidia__llama_embed_nemotron_8b__texto_preprocessado_sem_justificativa',
       'embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto',
       'embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto_preprocessado',
       'embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto_preprocessado_sem_justificativa',
       'embedding__joaorobson__harrier_oss_v1_27b__texto',
       'embedding__joaorobson__harrier_oss_v1_27b__texto_preprocessado',
       'embedding__joaorobson__harrier_oss_v1_27b__texto_preprocessado_sem_justificativa',
       'embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto',
       'embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto_preprocessado',
       'embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto_preprocessado_sem_justificativa',
       'embedding__openai__text_embedding_3_large__trunc8192__texto',
       'embedding__openai__text_embedding_3_large__trunc8192__texto_preprocessado',
       'embedding__openai__text_embedding_3_large__trunc8192__texto_preprocessado_sem_justificativa',
       'embedding__google__gemini_embedding_2__trunc8192__texto',
       'embedding__google__gemini_embedding_2__trunc8192__texto_preprocessado',
       'embedding__google__gemini_embedding_2__trunc8192__texto_preprocessado_sem_justificativa',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto_preprocessado',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto_preprocessado_sem_justificativa',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto_preprocessado',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto_preprocessado_sem_justificativa',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto_preprocessado',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto_preprocessado_sem_justificativa',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto_preprocessado',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto_preprocessado_sem_justificativa',
       'embedding__josedossantos__bertimbau_tuned__trunc512__texto',
       'embedding__josedossantos__bertimbau_tuned__trunc512__texto_preprocessado',
       'embedding__josedossantos__bertimbau_tuned__trunc512__texto_preprocessado_sem_justificativa',
       'embedding__josedossantos__bertimbau_tuned__meanpool512__texto',
       'embedding__josedossantos__bertimbau_tuned__meanpool512__texto_preprocessado',
       'embedding__josedossantos__bertimbau_tuned__meanpool512__texto_preprocessado_sem_justificativa',
       'embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto',
       'embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto_preprocessado',
       'embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto_preprocessado_sem_justificativa']

In [4]:
embeddings[embeddings.materia=="PEC_6_2019"].tema.value_counts()

tema
CUSTEIO                28
RPPS TRANSICAO         25
PENSÃO                 20
CALCULO APÓS           19
SERVIDOR               18
OUTROS                 15
BPC                    14
RGPS/RPPS TRANSICAO    13
PENSÃO MÍNIMA          13
AP ESP                 11
RGPS TRANSICAO          9
ABONO PERM              9
APOS INVALIDEZ          9
ESTADOS E MUN           8
ABONO SAL               8
RGPS                    7
PREV COMPL              7
ACUM BENEF              6
POLICIAIS               6
MAGISTERIO              4
ANISTIADOS              4
PCD                     4
AÇÕES JUD               3
MILITARES               2
OF JUSTIÇA              2
RURAIS                  1
RGPS (REPETE 146)       1
CSLL BANCOS             1
TRIBUTACAO LUCROS       1
Name: count, dtype: int64

In [5]:
embeddings.groupby(["materia", "tema"]).size().groupby("materia").agg(
    media="mean",
    mediana="median",
    desvio="std",
    min="min",
    max="max"
)

                 media  mediana     desvio  min  max
materia
MPV_612_2013  3.793103      1.0   9.818991    1   60
PEC_6_2019    9.241379      8.0   7.337064    1   28
PLP_68_2024   7.563218      3.0  11.313064    1   85

In [6]:
embeddings.query("materia == 'PLP_68_2024'") \
    .groupby("tema_nivel_2") \
    .size() \
    .agg(
        media="mean",
        mediana="median",
        desvio="std",
        min="min",
        max="max",
        quantidade="count"
    )

media          19.352941
mediana         7.000000
desvio         25.537643
min             1.000000
max           118.000000
quantidade    102.000000
dtype: float64

In [7]:
embeddings.query("materia == 'PLP_68_2024'") \
    .groupby("tema_macro") \
    .size() \
    .agg(
        media="mean",
        mediana="median",
        desvio="std",
        min="min",
        max="max",
        quantidade="count"
    )

media          56.400000
mediana        17.000000
desvio        112.426499
min             1.000000
max           475.000000
quantidade     35.000000
dtype: float64

In [10]:
for col in embedding_cols:

    normas = embeddings[col].apply(
        lambda x: np.linalg.norm(np.array(x))
    )

    print(
        f"{col:90s} "
        f"mean={normas.mean():.4f} "
        f"std={normas.std():.4f}"
    )

embedding__codefuse_ai__F2LLM_v2_14B__texto                                                mean=1.0001 std=0.0020
embedding__codefuse_ai__F2LLM_v2_14B__texto_preprocessado                                  mean=1.0000 std=0.0020
embedding__codefuse_ai__F2LLM_v2_14B__texto_preprocessado_sem_justificativa                mean=1.0000 std=0.0020
embedding__Octen__Octen_Embedding_8B__texto                                                mean=1.0001 std=0.0013
embedding__Octen__Octen_Embedding_8B__texto_preprocessado                                  mean=1.0002 std=0.0013
embedding__Octen__Octen_Embedding_8B__texto_preprocessado_sem_justificativa                mean=1.0001 std=0.0013
embedding__Qwen__Qwen3_Embedding_8B__texto                                                 mean=1.0002 std=0.0022
embedding__Qwen__Qwen3_Embedding_8B__texto_preprocessado                                   mean=1.0001 std=0.0022
embedding__Qwen__Qwen3_Embedding_8B__texto_preprocessado_sem_justificativa                 mean=1.0000 std=0.0022
embedding__nvidia__llama_embed_nemotron_8b__texto                                          mean=1.0000 std=0.0018
embedding__nvidia__llama_embed_nemotron_8b__texto_preprocessado                            mean=0.9999 std=0.0017
embedding__nvidia__llama_embed_nemotron_8b__texto_preprocessado_sem_justificativa          mean=0.9999 std=0.0016
embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto                     mean=1.0001 std=0.0019
embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto_preprocessado       mean=1.0001 std=0.0016
embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto_preprocessado_sem_justificativa mean=1.0002 std=0.0017
embedding__joaorobson__harrier_oss_v1_27b__texto                                           mean=1.0000 std=0.0019
embedding__joaorobson__harrier_oss_v1_27b__texto_preprocessado                             mean=1.0000 std=0.0017
embedding__joaorobson__harrier_oss_v1_27b__texto_preprocessado_sem_justificativa           mean=1.0000 std=0.0019
embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto                               mean=1.0000 std=0.0015
embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto_preprocessado                 mean=1.0001 std=0.0016
embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto_preprocessado_sem_justificativa mean=1.0001 std=0.0016
embedding__openai__text_embedding_3_large__trunc8192__texto                                mean=1.0000 std=0.0003
embedding__openai__text_embedding_3_large__trunc8192__texto_preprocessado                  mean=1.0000 std=0.0003
embedding__openai__text_embedding_3_large__trunc8192__texto_preprocessado_sem_justificativa mean=1.0000 std=0.0003
embedding__google__gemini_embedding_2__trunc8192__texto                                    mean=1.0000 std=0.0000
embedding__google__gemini_embedding_2__trunc8192__texto_preprocessado                      mean=1.0000 std=0.0000
embedding__google__gemini_embedding_2__trunc8192__texto_preprocessado_sem_justificativa    mean=1.0000 std=0.0000
embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto          mean=1.0000 std=0.0000
embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto_preprocessado mean=1.0000 std=0.0000
embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto_preprocessado_sem_justificativa mean=1.0000 std=0.0000
embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto       mean=1.0000 std=0.0000
embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto_preprocessado mean=1.0000 std=0.0000
embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto_preprocessado_sem_justificativa mean=1.0000 std=0.0000
embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto       mean=1.0000 std=0.0000
embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto_preprocessado mean=1.0000 std=0.0000
embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto_preprocessado_sem_justificativa mean=1.0000 std=0.0000
embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto    mean=1.0000 std=0.0000
embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto_preprocessado mean=1.0000 std=0.0000
embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto_preprocessado_sem_justificativa mean=1.0000 std=0.0000
embedding__josedossantos__bertimbau_tuned__trunc512__texto                                 mean=1.0000 std=0.0000
embedding__josedossantos__bertimbau_tuned__trunc512__texto_preprocessado                   mean=1.0000 std=0.0000
embedding__josedossantos__bertimbau_tuned__trunc512__texto_preprocessado_sem_justificativa mean=1.0000 std=0.0000
embedding__josedossantos__bertimbau_tuned__meanpool512__texto                              mean=1.0000 std=0.0000
embedding__josedossantos__bertimbau_tuned__meanpool512__texto_preprocessado                mean=1.0000 std=0.0000
embedding__josedossantos__bertimbau_tuned__meanpool512__texto_preprocessado_sem_justificativa mean=1.0000 std=0.0000
embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto                    mean=1.0007 std=0.0016
embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto_preprocessado      mean=1.0007 std=0.0016
embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto_preprocessado_sem_justificativa mean=1.0008 std=0.0016

# Avaliação

## Pré-processamento BM25

* Fonte: https://github.com/Convenio-Camara-dos-Deputados/papers-JURIX-2021

In [11]:
class Savoy:

    def __removeAllPTAccent(self, old_word):
        word = list(old_word)
        len_word = len(word)-1
        for i in range(len_word, -1, -1):
            if word[i] == 'ä':
                word[i] = 'a'
            if word[i] == 'â':
                word[i] = 'a'
            if word[i] == 'à':
                word[i] = 'a'
            if word[i] == 'á':
                word[i] = 'a'
            if word[i] == 'ã':
                word[i] = 'a'
            if word[i] == 'ê':
                word[i] = 'e'
            if word[i] == 'é':
                word[i] = 'e'
            if word[i] == 'è':
                word[i] = 'e'
            if word[i] == 'ë':
                word[i] = 'e'
            if word[i] == 'ï':
                word[i] = 'i'
            if word[i] == 'î':
                word[i] = 'i'
            if word[i] == 'ì':
                word[i] = 'i'
            if word[i] == 'í':
                word[i] = 'i'
            if word[i] == 'ü':
                word[i] = 'u'
            if word[i] == 'ú':
                word[i] = 'u'
            if word[i] == 'ù':
                word[i] = 'u'
            if word[i] == 'û':
                word[i] = 'u'
            if word[i] == 'ô':
                word[i] = 'o'
            if word[i] == 'ö':
                word[i] = 'o'
            if word[i] == 'ó':
                word[i] = 'o'
            if word[i] == 'ò':
                word[i] = 'o'
            if word[i] == 'õ':
                word[i] = 'o'
            if word[i] == 'ç':
                word[i] = 'c'

        new_word = "".join(word)
        return new_word

    def __finalVowelPortuguese(self, word):
        len_word = len(word)
        if len_word > 3:
            if word[-1] == 'e' or word[-1] == 'a' or word[-1] == 'o':
                word = word[:-1]

        return word

    def __remove_PTsuffix(self, word):
        len_word = len(word)

        if len_word > 3:
            if word[-1] == 's' and word[-2] == 'e' and (word[-3] == 'r' or word[-3] == 's' or word[-3] == 'z' or word[-3] == 'l'):
                word = word[:-2]
                return word
        if len_word > 2:
            if word[-1] == 's' and word[-2] == 'n':
                new_word = list(word)
                new_word[-2] = 'm'
                sing = "".join(new_word)
                sing = sing[:-1]
                return sing

        if len_word > 3:
            if (word[-1] == 's' and word[-2] == 'i') and (word[-3] == 'e' or word[-3] == 'é'):
                new_word = list(word)
                new_word[-3] = 'e'
                new_word[-2] = 'l'
                sing = "".join(new_word)
                sing = sing[:-1]
                return sing

        if len_word > 3:
            if word[-1] == 's' and word[-2] == 'i' and word[-3] == 'a':
                new_word = list(word)
                new_word[-2] = 'l'
                sing = "".join(new_word)
                sing = sing[:-1]
                return sing

        if len_word > 3:
            if word[-1] == 's' and word[-2] == 'i' and word[-3] == 'ó':
                new_word = list(word)
                new_word[-3] = 'o'
                new_word[-2] = 'l'
                sing = "".join(new_word)
                sing = sing[:-1]
                return sing

        if len_word > 3:
            if word[-1] == 's' and word[-2] == 'i':
                new_word = list(word)
                new_word[-1] = 'l'
                sing = "".join(new_word)
                return sing

        if len_word > 2:
            if word[-1] == 's' and word[-2] == 'e' and word[-3] == 'õ':
                new_word = list(word)
                new_word[-3] = 'ã'
                new_word[-2] = 'o'
                sing = "".join(new_word)
                sing = sing[:-1]
                return sing
            if word[-1] == 's' and word[-2] == 'e' and word[-3] == 'ã':
                new_word = list(word)
                new_word[-2] = 'o'
                sing = "".join(new_word)
                sing = sing[:-1]
                return sing

        if len_word > 5:
            if word[-1] == 'e' and word[-2] == 't' and word[-3] == 'n' and word[-4] == 'e' and word[-5] == 'm':
                word = word[:-5]
                return word

        if len_word > 2:
            if word[-1] == 's':
                word = word[:-1]

        return word

    def __normFemininPortuguese(self, word):

        len_word = len(word)

        if len_word < 3 or word[-1] != 'a':
            return word

        if len_word > 6:

            if word[-2] == 'h' and word[-3] == 'n' and word[-4] == 'i':
                new_word = list(word)
                new_word[-1] = 'o'
                masc = "".join(new_word)
                return masc

            if word[-2] == 'c' and word[-3] == 'a' and word[-4] == 'i':
                new_word = list(word)
                new_word[-1] = 'o'
                masc = "".join(new_word)
                return masc

            if word[-2] == 'r' and word[-3] == 'i' and word[-4] == 'e':
                new_word = list(word)
                new_word[-1] = 'o'
                masc = "".join(new_word)
                return masc

        if len_word > 5:
            if word[-2] == 'n' and word[-3] == 'o':
                new_word = list(word)
                new_word[-3] = 'ã'
                new_word[-2] = 'o'
                masc = "".join(new_word)
                masc = masc[:-1]
                return masc

            if word[-2] == 'r' and word[-3] == 'o':
                word = word[:-1]
                return word

            if word[-2] == 's' and word[-3] == 'o':
                new_word = list(word)
                new_word[-1] = 'o'
                masc = "".join(new_word)
                return masc

            if word[-2] == 's' and word[-3] == 'e':
                new_word = list(word)
                new_word[-3] = 'ê'
                masc = "".join(new_word)
                masc = masc[:-1]
                return masc

            if word[-2] == 'c' and word[-3] == 'i':
                new_word = list(word)
                new_word[-1] = 'o'
                masc = "".join(new_word)
                return masc

            if word[-2] == 'd' and word[-3] == 'i':
                new_word = list(word)
                new_word[-1] = 'o'
                masc = "".join(new_word)
                return masc

            if word[-2] == 'd' and word[-3] == 'a':
                new_word = list(word)
                new_word[-1] = 'o'
                masc = "".join(new_word)
                return masc

            if word[-2] == 'v' and word[-3] == 'i':
                new_word = list(word)
                new_word[-1] = 'o'
                masc = "".join(new_word)
                return masc

            if word[-2] == 'm' and word[-3] == 'a':
                new_word = list(word)
                new_word[-1] = 'o'
                masc = "".join(new_word)
                return masc

            if word[-2] == 'n':
                new_word = list(word)
                new_word[-1] = 'o'
                masc = "".join(new_word)
                return masc

        return word

    def stem(self, word):
        len_word = len(word)
        if len_word > 2:
            word = self.__remove_PTsuffix(word)
            word = self.__normFemininPortuguese(word)
            word = self.__finalVowelPortuguese(word)
            word = self.__removeAllPTAccent(word)

        return word

In [12]:
import nltk

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('rslp')

from nltk.tokenize import word_tokenize
from string import punctuation
import nltk
from unicodedata import normalize
from nltk.util import ngrams
from nltk.tokenize import RegexpTokenizer

# Remove os acentos de uma string
def _remove_acentos(txt):
    return normalize('NFKD', txt).encode('ASCII', 'ignore').decode('ASCII')

def stem_Savoy(txt):
    stemmer = Savoy()
    terms = word_tokenize(txt)
    terms = [stemmer.stem(word) for word in terms]
    return terms


# Remoção de stopwords + acentuação + steming + pontuação
def preprocess_Savoy(txt):
    txt = _remove_acentos(txt)
    stopwords = nltk.corpus.stopwords.words("portuguese")
    stopwords.extend(list(punctuation))

    stemmer = Savoy()
    tokenizer = RegexpTokenizer('\w+')
    terms = tokenizer.tokenize(txt.lower())
    terms = [stemmer.stem(word) for word in terms if word not in stopwords]
    return terms

#---------------------------------------------------------------------------------

def n_gram(txt, n):
    terms = word_tokenize(txt)
    ngram = list(ngrams(terms, n))

    return ngram

def preprocess_ngram_savoy(txt, n):
    txt = _remove_acentos(txt)
    stopwords = nltk.corpus.stopwords.words("portuguese")
    stopwords.extend(list(punctuation))

    stemmer = Savoy()
    # terms = word_tokenize(txt.lower())
    tokenizer = RegexpTokenizer('\w+')
    terms = tokenizer.tokenize(txt.lower())
    terms = [stemmer.stem(word) for word in terms if word not in stopwords]

    ngram = list(ngrams(terms, n))

    return ngram

<>:32: SyntaxWarning: invalid escape sequence '\w'
<>:52: SyntaxWarning: invalid escape sequence '\w'
<>:32: SyntaxWarning: invalid escape sequence '\w'
<>:52: SyntaxWarning: invalid escape sequence '\w'
C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_19048\3290414712.py:32: SyntaxWarning: invalid escape sequence '\w'
  tokenizer = RegexpTokenizer('\w+')
C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_19048\3290414712.py:52: SyntaxWarning: invalid escape sequence '\w'
  tokenizer = RegexpTokenizer('\w+')
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\3675-Robson\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\3675-Robson\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package rslp to
[nltk_data]     C:\Users\3675-Robson\AppData\Roaming\nltk_data...
[nltk_data]   Package rslp is already up-to-date!

In [14]:
def preprocess_txt_bm25(txt):

    unigrams = preprocess_Savoy(txt)

    bigrams = preprocess_ngram_savoy(
        txt,
        2
    )

    bigrams = [
        "_".join(bg)
        for bg in bigrams
    ]

    return " ".join(
        unigrams + bigrams
    )

In [15]:
import bm25s

# Create your corpus here
corpus = [
    "a cat is a feline and likes to purr",
    "a dog is the human's best friend and loves to play",
    "a bird is a beautiful animal that can fly",
]

# Tokenize the corpus and index it
corpus_tokens = bm25s.tokenize(corpus)
retriever = bm25s.BM25(corpus=corpus)
retriever.index(corpus_tokens)

# You can now search the corpus with a query
query = "does the fish purr like a cat?"
query_tokens = bm25s.tokenize(query)
docs, scores = retriever.retrieve(query_tokens, k=2)
print(f"Best result (score: {scores[0, 0]:.2f}): {docs[0, 0]}")
corpus_tokens.ids

Split strings:   0%|          | 0/3 [00:00<?, ?it/s]

BM25S Count Tokens:   0%|          | 0/3 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/3 [00:00<?, ?it/s]

Split strings:   0%|          | 0/1 [00:00<?, ?it/s]

BM25S Retrieve:   0%|          | 0/1 [00:00<?, ?it/s]

Best result (score: 0.86): a cat is a feline and likes to purr

[[0, 1, 2, 3], [4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [16]:
import gc
import bm25s
import numpy as np
import pandas as pd
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics.pairwise import cosine_similarity

import nltk
from string import punctuation
from nltk.tokenize import RegexpTokenizer
from nltk.util import ngrams
from unicodedata import normalize

# Supondo que a classe Savoy venha de algum pacote local/específico, 
# certifique-se de mantê-la importada. Ex: from seu_modulo import Savoy

# =====================================================
# CONFIGURAÇÕES E INSTÂNCIAS GLOBAIS (OTIMIZAÇÃO DE CPU)
# =====================================================
try:
    STOPWORDS_PT = set(nltk.corpus.stopwords.words("portuguese") + list(punctuation))
except LookupError:
    nltk.download("stopwords")
    STOPWORDS_PT = set(nltk.corpus.stopwords.words("portuguese") + list(punctuation))

TOKENIZER_REGEXP = RegexpTokenizer(r"\w+")
STEMMER_SAVOY = Savoy()  # Instanciado globalmente para evitar recarga em loops

# =====================================================
# UTILITÁRIOS E PRÉ-PROCESSAMENTO
# =====================================================

def _remove_acentos(txt):
    return normalize("NFKD", txt).encode("ASCII", "ignore").decode("ASCII")


def preprocess_Savoy(txt):
    txt = _remove_acentos(txt)
    terms = TOKENIZER_REGEXP.tokenize(txt.lower())
    
    # Busca O(1) usando hash set global
    return [
        STEMMER_SAVOY.stem(word)
        for word in terms
        if word not in STOPWORDS_PT
    ]


def preprocess_ngram_savoy(txt, n):
    txt = _remove_acentos(txt)
    terms = TOKENIZER_REGEXP.tokenize(txt.lower())
    
    terms_stemmed = [
        STEMMER_SAVOY.stem(word)
        for word in terms
        if word not in STOPWORDS_PT
    ]
    
    return list(ngrams(terms_stemmed, n))


def preprocess_txt_bm25(txt):
    unigrams = preprocess_Savoy(txt)
    bigrams = preprocess_ngram_savoy(txt, 2)
    
    bigrams_joined = [
        "_".join(bg)
        for bg in bigrams
    ]
    
    return " ".join(unigrams + bigrams_joined)


# =====================================================
# MOTOR BM25S (CORRIGIDO)
# =====================================================

def build_score_matrix_bm25s(corpus):
    # Tokeniza o corpus completo
    corpus_tokens = bm25s.tokenize(corpus, show_progress=False)
    
    # Inicializa o modelo no modo BM25L
    retriever = bm25s.BM25(method="bm25l")
    retriever.index(corpus_tokens)
    
    n = len(corpus)
    score_matrix = np.empty((n, n), dtype=np.float32)
    
    # Coleta os scores utilizando os IDs da estrutura fatiada
    for i in tqdm(range(n), desc="Calculando Matriz BM25S", leave=False):
        # CORREÇÃO: corpus_tokens[i].ids extrai a matriz de IDs do documento fatiado.
        # Como é apenas um documento, pegamos a primeira linha [0].
      
        score_matrix[i] = retriever.get_scores(corpus_tokens.ids[i])
        
    # Desconsidera o auto-match na similaridade do retrieval
    np.fill_diagonal(score_matrix, -np.inf)
    
    return score_matrix


# =====================================================
# MÉTRICAS DE AVALIAÇÃO (CORRIGIDAS)
# =====================================================

def average_precision_from_hits(hits):
    n_rel = hits.sum()
    if n_rel == 0:
        return np.nan

    precisions = []
    hit_count = 0
    for i, rel in enumerate(hits, start=1):
        if rel:
            hit_count += 1
            precisions.append(hit_count / i)
            
    return np.mean(precisions)


def retrieval_metrics_from_scores(score_matrix, labels):
    labels = np.asarray(labels)
    n_docs = len(labels)
    
    # Ordena os índices do maior score para o menor
    ranking = np.argsort(-score_matrix, axis=1)
    
    p1_scores = []
    mrr_scores = []
    rprec_scores = []
    ap_scores = []
    
    for i in range(n_docs):
        label = labels[i]
        
        # Cria a máscara do Ground Truth desconsiderando o próprio documento 'i'
        relevant_mask = (labels == label)
        relevant_mask[i] = False
        R = relevant_mask.sum()
        
        if R == 0:
            continue
            
        # Filtra o ranking para remover o auto-hit (documento 'i')
        ranked = ranking[i]
        ranked = ranked[ranked != i]
        
        # Mapeia as labels ordenadas preditas
        predicted_labels = labels[ranked]
        
        # Hits booleanos (1 se relevante, 0 caso contrário)
        hits = (predicted_labels == label).astype(int)
        
        # 1. Precision@1
        p1_scores.append(hits[0])
        
        # 2. MRR (Reciprocal Rank do 1º resultado relevante)
        # np.where encontra as posições dos acertos; se houver acerto, pegamos o 1º (+1 pois indexação começa em 0)
        first_hit_indices = np.where(hits == 1)[0]
        if len(first_hit_indices) > 0:
            reciprocal_rank = 1.0 / (first_hit_indices[0] + 1)
        else:
            reciprocal_rank = 0.0
        mrr_scores.append(reciprocal_rank)
        
        # 3. R-Precision (Corte na quantidade exata de relevantes R)
        rprec_scores.append(np.mean(hits[:R]))
        
        # 4. Average Precision (MAP)
        ap = average_precision_from_hits(hits)
        if not np.isnan(ap):
            ap_scores.append(ap)
            
    return {
        "precision@1": float(np.mean(p1_scores)) if p1_scores else 0.0,
        "mrr": float(np.mean(mrr_scores)) if mrr_scores else 0.0,
        "r_precision": float(np.mean(rprec_scores)) if rprec_scores else 0.0,
        "map": float(np.mean(ap_scores)) if ap_scores else 0.0,
    }


def retrieval_metrics_embeddings(X, labels):
    # Calcula similaridade angular via cosseno
    sim = cosine_similarity(X)
    np.fill_diagonal(sim, -np.inf)
    
    return retrieval_metrics_from_scores(sim, labels)


# =====================================================
# PIPELINE CONFIG E EXECUÇÃO
# =====================================================

materias = [
    "PEC_6_2019",
    "MPV_612_2013",
    "PLP_68_2024"
]

campos_textuais = [
    "texto",
    "texto_preprocessado",
    "texto_preprocessado_sem_justificativa"
]

resultados = {}
resultados_df = {}

# OBS: Certifique-se de que o DataFrame global 'embeddings' e a lista 
# 'embedding_cols' de colunas densas estejam instanciados no seu ambiente antes de rodar.

for materia in materias:
    print(f"\n{'='*60}\nProcessando Proposição: {materia}\n{'='*60}")
    
    embeddings_materia = (
        embeddings[embeddings["materia"] == materia]
        .copy()
        .reset_index(drop=True)
    )
    
    niveis = ["tema"]
    if materia == "PLP_68_2024":
        niveis = ["tema_macro", "tema_nivel_2", "tema"]
        
    resultados[materia] = []
    
    # -------------------------------------------------
    # Matrizes de Similaridade BM25L
    # -------------------------------------------------
    bm25_models = {}
    for campo in campos_textuais:
        print(f"-> Computando representações BM25L para campo: '{campo}'")
        
        corpus_raw = (
            embeddings_materia[campo]
            .fillna("")
            .astype(str)
            .str.lower()
            .tolist()
        )
        
        # Geração da matriz bruta (raw)
        bm25_models[f"{campo}__raw"] = build_score_matrix_bm25s(corpus_raw)
        
        # Geração da matriz estruturada (Savoy + Bigrams)
        print(f"   Aplicando Stemming Savoy e N-Grams em '{campo}'...")
        corpus_preprocess = [
            preprocess_txt_bm25(doc)
            for doc in corpus_raw
        ]
        bm25_models[f"{campo}__preprocess"] = build_score_matrix_bm25s(corpus_preprocess)
        
    # -------------------------------------------------
    # Execução das Métricas por Nível de Granularidade
    # -------------------------------------------------
    for nivel in niveis:
        labels = embeddings_materia[nivel].values
        print(f"\nAvaliando Granularidade: [Nível: {nivel}] | Amostras: {len(labels)}")
        
        # Evaluator 1: Embeddings Densos das LLMs
        for col in tqdm(embedding_cols, desc="Avaliando Vetores Densos"):
            X = np.vstack(embeddings_materia[col].values)
            metrics = retrieval_metrics_embeddings(X, labels)
            
            resultados[materia].append({
                "nivel": nivel,
                "embedding": col,
                **metrics
            })
            
        # Evaluator 2: Matrizes Léxicas do BM25L
        for nome, score_matrix in bm25_models.items():
            metrics = retrieval_metrics_from_scores(score_matrix, labels)
            
            resultados[materia].append({
                "nivel": nivel,
                "embedding": f"retrieval__bm25l__{nome}",
                **metrics
            })
            
    # Consolidação e ordenação do ranking da matéria
    resultados_df[materia] = (
        pd.DataFrame(resultados[materia])
        .sort_values(
            ["map", "r_precision", "precision@1"],
            ascending=False
        )
        .reset_index(drop=True)
    )
    
    # Exibe o Top 20 imediato na tela
    print(f"\n>>> TOP 20 RANKING - {materia} <<<")
    display(resultados_df[materia].head(20))
    
    # Limpeza de memória da iteração
    del bm25_models
    gc.collect()

============================================================
Processando Proposição: PEC_6_2019
============================================================
-> Computando representações BM25L para campo: 'texto'

BM25S Count Tokens:   0%|          | 0/268 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/268 [00:00<?, ?it/s]

   Aplicando Stemming Savoy e N-Grams em 'texto'...

BM25S Count Tokens:   0%|          | 0/268 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/268 [00:00<?, ?it/s]

-> Computando representações BM25L para campo: 'texto_preprocessado'

BM25S Count Tokens:   0%|          | 0/268 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/268 [00:00<?, ?it/s]

   Aplicando Stemming Savoy e N-Grams em 'texto_preprocessado'...

BM25S Count Tokens:   0%|          | 0/268 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/268 [00:00<?, ?it/s]

-> Computando representações BM25L para campo: 'texto_preprocessado_sem_justificativa'

BM25S Count Tokens:   0%|          | 0/268 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/268 [00:00<?, ?it/s]

   Aplicando Stemming Savoy e N-Grams em 'texto_preprocessado_sem_justificativa'...

BM25S Count Tokens:   0%|          | 0/268 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/268 [00:00<?, ?it/s]

Avaliando Granularidade: [Nível: tema] | Amostras: 268

Avaliando Vetores Densos: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:02<00:00, 19.61it/s]

>>> TOP 20 RANKING - PEC_6_2019 <<<

,nivel,embedding,precision@1,mrr,r_precision,map
0,tema,embedding__Octen__Octen_Embedding_8B__texto,0.867424,0.895425,0.669929,0.716369
1,tema,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.867424,0.897080,0.658753,0.713185
2,tema,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.856061,0.894553,0.653239,0.699050
3,tema,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.852273,0.893137,0.645340,0.694852
4,tema,embedding__Qwen__Qwen3_Embedding_8B__texto,0.856061,0.893263,0.640187,0.692511
5,tema,embedding__joaorobson__harrier_oss_v1_27b__texto,0.844697,0.888855,0.652145,0.690927
6,tema,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.825758,0.875471,0.639876,0.684038
7,tema,embedding__jinaai__jina_embeddings_v5_text_sma...,0.856061,0.896026,0.590560,0.642256
8,tema,embedding__jinaai__jina_embeddings_v5_text_sma...,0.795455,0.853279,0.588230,0.630028
9,tema,embedding__openai__text_embedding_3_large__tru...,0.799242,0.857111,0.576045,0.625862
10,tema,embedding__nvidia__llama_embed_nemotron_8b__te...,0.787879,0.843743,0.578752,0.617256
11,tema,embedding__ICT_TIME_and_Querit__ICT_TIME_and_Q...,0.799242,0.860090,0.568352,0.616891
12,tema,embedding__joaorobson__KaLM_Embedding_Gemma3_1...,0.795455,0.846515,0.507710,0.546598
13,tema,retrieval__bm25l__texto_preprocessado__preprocess,0.734848,0.806532,0.511232,0.544970
14,tema,embedding__codefuse_ai__F2LLM_v2_14B__texto,0.685606,0.771764,0.495264,0.539167
15,tema,retrieval__bm25l__texto_preprocessado__raw,0.738636,0.804027,0.490757,0.523457
16,tema,embedding__openai__text_embedding_3_large__tru...,0.659091,0.751371,0.462064,0.507273
17,tema,embedding__josedossantos__bertimbau_tuned__tru...,0.712121,0.771226,0.458136,0.497605
18,tema,embedding__nvidia__llama_embed_nemotron_8b__texto,0.700758,0.775257,0.458419,0.492568
19,tema,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.780303,0.827457,0.446936,0.487977

============================================================
Processando Proposição: MPV_612_2013
============================================================
-> Computando representações BM25L para campo: 'texto'

BM25S Count Tokens:   0%|          | 0/220 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/220 [00:00<?, ?it/s]

   Aplicando Stemming Savoy e N-Grams em 'texto'...

BM25S Count Tokens:   0%|          | 0/220 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/220 [00:00<?, ?it/s]

-> Computando representações BM25L para campo: 'texto_preprocessado'

BM25S Count Tokens:   0%|          | 0/220 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/220 [00:00<?, ?it/s]

   Aplicando Stemming Savoy e N-Grams em 'texto_preprocessado'...

BM25S Count Tokens:   0%|          | 0/220 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/220 [00:00<?, ?it/s]

-> Computando representações BM25L para campo: 'texto_preprocessado_sem_justificativa'

BM25S Count Tokens:   0%|          | 0/220 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/220 [00:00<?, ?it/s]

   Aplicando Stemming Savoy e N-Grams em 'texto_preprocessado_sem_justificativa'...

BM25S Count Tokens:   0%|          | 0/220 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/220 [00:00<?, ?it/s]

Avaliando Granularidade: [Nível: tema] | Amostras: 220

Avaliando Vetores Densos: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:01<00:00, 29.01it/s]

>>> TOP 20 RANKING - MPV_612_2013 <<<

,nivel,embedding,precision@1,mrr,r_precision,map
0,tema,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.765363,0.846049,0.624949,0.670250
1,tema,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.787709,0.860158,0.614590,0.663167
2,tema,embedding__joaorobson__harrier_oss_v1_27b__texto,0.798883,0.863221,0.619889,0.660557
3,tema,embedding__Octen__Octen_Embedding_8B__texto,0.759777,0.841334,0.607247,0.652603
4,tema,embedding__joaorobson__KaLM_Embedding_Gemma3_1...,0.810056,0.862353,0.599140,0.648100
5,tema,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.765363,0.834482,0.600504,0.643553
6,tema,embedding__Qwen__Qwen3_Embedding_8B__texto,0.787709,0.856162,0.582382,0.627372
7,tema,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.720670,0.814252,0.577354,0.624240
8,tema,embedding__ICT_TIME_and_Querit__ICT_TIME_and_Q...,0.776536,0.838145,0.576240,0.623840
9,tema,embedding__openai__text_embedding_3_large__tru...,0.770950,0.833216,0.582640,0.621127
10,tema,retrieval__bm25l__texto_preprocessado__preprocess,0.782123,0.844635,0.560455,0.596075
11,tema,embedding__codefuse_ai__F2LLM_v2_14B__texto,0.759777,0.833169,0.528424,0.584126
12,tema,embedding__joaorobson__KaLM_Embedding_Gemma3_1...,0.798883,0.859162,0.517574,0.575367
13,tema,retrieval__bm25l__texto__preprocess,0.759777,0.827957,0.542672,0.571026
14,tema,embedding__nvidia__llama_embed_nemotron_8b__te...,0.776536,0.831601,0.525949,0.569700
15,tema,embedding__openai__text_embedding_3_large__tru...,0.798883,0.851984,0.521717,0.555768
16,tema,embedding__jinaai__jina_embeddings_v5_text_sma...,0.759777,0.825552,0.523229,0.551008
17,tema,retrieval__bm25l__texto_preprocessado__raw,0.759777,0.830662,0.516099,0.543362
18,tema,embedding__google__gemini_embedding_2__trunc81...,0.782123,0.832075,0.501245,0.534132
19,tema,retrieval__bm25l__texto__raw,0.737430,0.813257,0.510542,0.533465

============================================================
Processando Proposição: PLP_68_2024
============================================================
-> Computando representações BM25L para campo: 'texto'

BM25S Count Tokens:   0%|          | 0/1974 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/1974 [00:00<?, ?it/s]

   Aplicando Stemming Savoy e N-Grams em 'texto'...

BM25S Count Tokens:   0%|          | 0/1974 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/1974 [00:00<?, ?it/s]

-> Computando representações BM25L para campo: 'texto_preprocessado'

BM25S Count Tokens:   0%|          | 0/1974 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/1974 [00:00<?, ?it/s]

   Aplicando Stemming Savoy e N-Grams em 'texto_preprocessado'...

BM25S Count Tokens:   0%|          | 0/1974 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/1974 [00:00<?, ?it/s]

-> Computando representações BM25L para campo: 'texto_preprocessado_sem_justificativa'

BM25S Count Tokens:   0%|          | 0/1974 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/1974 [00:00<?, ?it/s]

   Aplicando Stemming Savoy e N-Grams em 'texto_preprocessado_sem_justificativa'...

BM25S Count Tokens:   0%|          | 0/1974 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/1974 [00:00<?, ?it/s]

Avaliando Granularidade: [Nível: tema_macro] | Amostras: 1974

Avaliando Vetores Densos: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [01:09<00:00,  1.45s/it]

Avaliando Granularidade: [Nível: tema_nivel_2] | Amostras: 1974

Avaliando Vetores Densos: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [01:08<00:00,  1.44s/it]

Avaliando Granularidade: [Nível: tema] | Amostras: 1974

Avaliando Vetores Densos: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:59<00:00,  1.25s/it]

>>> TOP 20 RANKING - PLP_68_2024 <<<

,nivel,embedding,precision@1,mrr,r_precision,map
0,tema,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.817750,0.871135,0.570928,0.606218
1,tema,embedding__joaorobson__harrier_oss_v1_27b__texto,0.809826,0.864308,0.567635,0.605676
2,tema,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.811410,0.864705,0.568953,0.604211
3,tema,embedding__Octen__Octen_Embedding_8B__texto,0.813524,0.868455,0.569140,0.603232
4,tema,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.824089,0.874946,0.565604,0.598048
5,tema,embedding__Qwen__Qwen3_Embedding_8B__texto,0.807713,0.863557,0.556748,0.589823
6,tema,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.816165,0.867719,0.554392,0.587796
7,tema,embedding__ICT_TIME_and_Querit__ICT_TIME_and_Q...,0.817750,0.867598,0.534817,0.561174
8,tema,retrieval__bm25l__texto_preprocessado__preprocess,0.793450,0.850869,0.528529,0.558958
9,tema,embedding__nvidia__llama_embed_nemotron_8b__te...,0.808769,0.861080,0.528156,0.557408
10,tema,embedding__jinaai__jina_embeddings_v5_text_sma...,0.808769,0.862247,0.529498,0.556340
11,tema,embedding__codefuse_ai__F2LLM_v2_14B__texto,0.768621,0.841877,0.523102,0.551965
12,tema_nivel_2,embedding__joaorobson__harrier_oss_v1_27b__texto,0.887122,0.921211,0.515840,0.551145
13,tema,retrieval__bm25l__texto_preprocessado_sem_just...,0.809297,0.860929,0.530126,0.549929
14,tema,embedding__openai__text_embedding_3_large__tru...,0.802958,0.857330,0.520260,0.548547
15,tema_nivel_2,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.893279,0.923567,0.511797,0.547637
16,tema_nivel_2,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.901488,0.928998,0.505385,0.537700
17,tema,embedding__nvidia__llama_embed_nemotron_8b__texto,0.796091,0.854550,0.508490,0.535450
18,tema_nivel_2,embedding__Octen__Octen_Embedding_8B__texto,0.900975,0.928881,0.502123,0.534709
19,tema_nivel_2,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.906619,0.933199,0.502920,0.533126

In [29]:
embedding_cols

['embedding__codefuse_ai__F2LLM_v2_14B__texto',
 'embedding__codefuse_ai__F2LLM_v2_14B__texto_preprocessado',
 'embedding__codefuse_ai__F2LLM_v2_14B__texto_preprocessado_sem_justificativa',
 'embedding__Octen__Octen_Embedding_8B__texto',
 'embedding__Octen__Octen_Embedding_8B__texto_preprocessado',
 'embedding__Octen__Octen_Embedding_8B__texto_preprocessado_sem_justificativa',
 'embedding__Qwen__Qwen3_Embedding_8B__texto',
 'embedding__Qwen__Qwen3_Embedding_8B__texto_preprocessado',
 'embedding__Qwen__Qwen3_Embedding_8B__texto_preprocessado_sem_justificativa',
 'embedding__nvidia__llama_embed_nemotron_8b__texto',
 'embedding__nvidia__llama_embed_nemotron_8b__texto_preprocessado',
 'embedding__nvidia__llama_embed_nemotron_8b__texto_preprocessado_sem_justificativa',
 'embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto',
 'embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto_preprocessado',
 'embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto_preprocessado_sem_justificativa',
 'embedding__joaorobson__harrier_oss_v1_27b__texto',
 'embedding__joaorobson__harrier_oss_v1_27b__texto_preprocessado',
 'embedding__joaorobson__harrier_oss_v1_27b__texto_preprocessado_sem_justificativa',
 'embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto',
 'embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto_preprocessado',
 'embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto_preprocessado_sem_justificativa',
 'embedding__openai__text_embedding_3_large__trunc8192__texto',
 'embedding__openai__text_embedding_3_large__trunc8192__texto_preprocessado',
 'embedding__openai__text_embedding_3_large__trunc8192__texto_preprocessado_sem_justificativa',
 'embedding__google__gemini_embedding_2__trunc8192__texto',
 'embedding__google__gemini_embedding_2__trunc8192__texto_preprocessado',
 'embedding__google__gemini_embedding_2__trunc8192__texto_preprocessado_sem_justificativa',
 'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto',
 'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto_preprocessado',
 'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto_preprocessado_sem_justificativa',
 'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto',
 'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto_preprocessado',
 'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto_preprocessado_sem_justificativa',
 'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto',
 'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto_preprocessado',
 'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto_preprocessado_sem_justificativa',
 'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto',
 'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto_preprocessado',
 'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto_preprocessado_sem_justificativa',
 'embedding__josedossantos__bertimbau_tuned__trunc512__texto',
 'embedding__josedossantos__bertimbau_tuned__trunc512__texto_preprocessado',
 'embedding__josedossantos__bertimbau_tuned__trunc512__texto_preprocessado_sem_justificativa',
 'embedding__josedossantos__bertimbau_tuned__meanpool512__texto',
 'embedding__josedossantos__bertimbau_tuned__meanpool512__texto_preprocessado',
 'embedding__josedossantos__bertimbau_tuned__meanpool512__texto_preprocessado_sem_justificativa',
 'embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto',
 'embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto_preprocessado',
 'embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto_preprocessado_sem_justificativa']

In [18]:
def extract_text_type(name):
    if "texto_preprocessado_sem_justificativa" in name:
        return "texto_preprocessado_sem_justificativa"
    
    elif "texto_preprocessado" in name:
        return "texto_preprocessado"
    
    elif "texto" in name:
        return "texto"
    
    else:
        return "outro"

In [19]:
df_all = pd.concat(
    [df.assign(materia=m) for m, df in resultados_df.items()],
    ignore_index=True
)
df_all["tipo_texto"] = df_all["embedding"].apply(extract_text_type)

In [24]:
df_all.to_parquet("../data/datasets/resultados_retrieval_com_mrr.parquet", index=False)

In [25]:
metricas = ["precision@1", "r_precision", "map", "mrr"]

In [26]:
df_media_texto = df_all[df_all.nivel == 'tema'].groupby(["materia","nivel", "tipo_texto"])[metricas].mean()

In [27]:
df_media_texto

                                                          precision@1  \
materia      nivel tipo_texto
MPV_612_2013 tema  texto                                     0.682185
                   texto_preprocessado                       0.741775
                   texto_preprocessado_sem_justificativa     0.698324
PEC_6_2019   tema  texto                                     0.688552
                   texto_preprocessado                       0.768308
                   texto_preprocessado_sem_justificativa     0.690657
PLP_68_2024  tema  texto                                     0.726390
                   texto_preprocessado                       0.773376
                   texto_preprocessado_sem_justificativa     0.755679

                                                          r_precision  \
materia      nivel tipo_texto
MPV_612_2013 tema  texto                                     0.468168
                   texto_preprocessado                       0.525195
                   texto_preprocessado_sem_justificativa     0.445092
PEC_6_2019   tema  texto                                     0.445058
                   texto_preprocessado                       0.511322
                   texto_preprocessado_sem_justificativa     0.367378
PLP_68_2024  tema  texto                                     0.437057
                   texto_preprocessado                       0.473127
                   texto_preprocessado_sem_justificativa     0.418109

                                                               map       mrr
materia      nivel tipo_texto
MPV_612_2013 tema  texto                                  0.499759  0.770841
                   texto_preprocessado                    0.561047  0.818435
                   texto_preprocessado_sem_justificativa  0.481841  0.784593
PEC_6_2019   tema  texto                                  0.482643  0.759972
                   texto_preprocessado                    0.553202  0.825061
                   texto_preprocessado_sem_justificativa  0.397677  0.755232
PLP_68_2024  tema  texto                                  0.456013  0.795261
                   texto_preprocessado                    0.494370  0.831008
                   texto_preprocessado_sem_justificativa  0.431105  0.811144

In [136]:
embedding_cols_abertos = [
    'embedding__codefuse_ai__F2LLM_v2_14B__texto',
       'embedding__codefuse_ai__F2LLM_v2_14B__texto_preprocessado',
       'embedding__codefuse_ai__F2LLM_v2_14B__texto_preprocessado_sem_justificativa',
       'embedding__Octen__Octen_Embedding_8B__texto',
       'embedding__Octen__Octen_Embedding_8B__texto_preprocessado',
       'embedding__Octen__Octen_Embedding_8B__texto_preprocessado_sem_justificativa',
       'embedding__Qwen__Qwen3_Embedding_8B__texto',
       'embedding__Qwen__Qwen3_Embedding_8B__texto_preprocessado',
       'embedding__Qwen__Qwen3_Embedding_8B__texto_preprocessado_sem_justificativa',
       'embedding__nvidia__llama_embed_nemotron_8b__texto',
       'embedding__nvidia__llama_embed_nemotron_8b__texto_preprocessado',
       'embedding__nvidia__llama_embed_nemotron_8b__texto_preprocessado_sem_justificativa',
       'embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto',
       'embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto_preprocessado',
       'embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto_preprocessado_sem_justificativa',
       'embedding__joaorobson__harrier_oss_v1_27b__texto',
       'embedding__joaorobson__harrier_oss_v1_27b__texto_preprocessado',
       'embedding__joaorobson__harrier_oss_v1_27b__texto_preprocessado_sem_justificativa',
       'embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto',
       'embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto_preprocessado',
       'embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto_preprocessado_sem_justificativa',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto_preprocessado',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto_preprocessado_sem_justificativa',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto_preprocessado',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto_preprocessado_sem_justificativa',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto_preprocessado',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto_preprocessado_sem_justificativa',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto_preprocessado',
       'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto_preprocessado_sem_justificativa',
       'embedding__josedossantos__bertimbau_tuned__trunc512__texto',
       'embedding__josedossantos__bertimbau_tuned__trunc512__texto_preprocessado',
       'embedding__josedossantos__bertimbau_tuned__trunc512__texto_preprocessado_sem_justificativa',
       'embedding__josedossantos__bertimbau_tuned__meanpool512__texto',
       'embedding__josedossantos__bertimbau_tuned__meanpool512__texto_preprocessado',
       'embedding__josedossantos__bertimbau_tuned__meanpool512__texto_preprocessado_sem_justificativa',
       'embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto',
       'embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto_preprocessado',
       'embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto_preprocessado_sem_justificativa']

In [140]:
MODEL_SIZE = {
    "F2LLM_v2_14B": 14.0,
    "Octen_Embedding_8B": 8.0,
    "Qwen3_Embedding_8B": 8.0,
    "llama_embed_nemotron_8b": 8.0,
    "harrier_oss_v1_27b": 27.0,
    "KaLM_Embedding_Gemma3_12B_2511": 12.0,
    "jina_embeddings_v5_text_small": 0.6,      # 330M
    "serafim_335m_portuguese_pt_sentence_encoder": 0.335,
    "serafim_335m_portuguese_pt_sentence_encoder_ir": 0.335,
    "bertimbau_tuned": 0.335,                   # BERTimbau Large ≈335M
    "ICT_TIME_and_Querit_embedding_v1": 4  # preencher quando souber
}


def get_model_size(name):
    for model, size in MODEL_SIZE.items():
        if model in name:
            return size
    return np.nan

In [143]:
df_all["size"] = df_all.embedding.apply(get_model_size)

In [145]:
df_abertos = df_all[(df_all.tipo_texto == "texto_preprocessado") & (df_all.nivel == "tema") & (df_all.embedding.isin(embedding_cols_abertos))].copy()

In [165]:
import pandas as pd

metricas = ["precision@1", "r_precision", "map"]

ranks = []

for metrica in metricas:
    r = (
        df_all[(df_all.tipo_texto == "texto_preprocessado") & (df_all.nivel == "tema")].groupby("materia")
          .apply(lambda x:
                 x.assign(
                     rank=x[metrica].rank(
                         ascending=False,
                         method="average"
                     )
                 )[["embedding", "materia", "rank"]]
          )
          .reset_index(drop=True)
    )
    r["metrica"] = metrica
    ranks.append(r)

ranks = pd.concat(ranks)

ranking_medio = (
    ranks.groupby("embedding")
         .agg(
             ranking_medio=("rank","mean"),
             desvio=("rank","std"),
             melhor=("rank","min"),
             pior=("rank","max")
         )
         .sort_values("ranking_medio")
)

ranking_medio

C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_15412\3530993989.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x:
C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_15412\3530993989.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x:
C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_15412\3530993989.py:10: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x:

,ranking_medio,desvio,melhor,pior
embedding,,,,
embedding__Octen__Octen_Embedding_8B__texto_preprocessado,1.888889,2.161854,1.0,7.5
embedding__joaorobson__harrier_oss_v1_27b__texto_preprocessado,2.388889,0.993031,2.0,5.0
embedding__Qwen__Qwen3_Embedding_8B__texto_preprocessado,4.055556,1.379412,3.0,7.5
embedding__codefuse_ai__F2LLM_v2_14B__texto_preprocessado,4.888889,3.370625,1.0,13.0
embedding__ICT_TIME_and_Querit__ICT_TIME_and_Querit_embedding_v1__texto_preprocessado,5.833333,1.785357,2.5,8.0
embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto_preprocessado,6.944444,2.615392,2.5,10.0
embedding__openai__text_embedding_3_large__trunc8192__texto_preprocessado,7.055556,1.379412,5.0,9.0
embedding__nvidia__llama_embed_nemotron_8b__texto_preprocessado,7.333333,1.561249,4.5,9.0
embedding__joaorobson__KaLM_Embedding_Gemma3_12B_2511__texto_preprocessado,7.555556,3.876568,1.0,11.0
retrieval__bm25l__texto_preprocessado__preprocess,8.000000,2.549510,3.0,12.0
retrieval__bm25l__texto_preprocessado__raw,10.444444,0.583333,9.5,11.0
embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__meanpool128__texto_preprocessado,12.277778,1.092906,10.5,14.0
embedding__google__gemini_embedding_2__trunc8192__texto_preprocessado,13.777778,1.481366,12.0,16.0
embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__meanpool128__texto_preprocessado,14.444444,1.236033,13.0,16.0
embedding__josedossantos__bertimbau_tuned__meanpool512__texto_preprocessado,15.000000,1.414214,13.0,18.0
embedding__josedossantos__bertimbau_tuned__trunc512__texto_preprocessado,15.222222,2.048034,12.0,17.0
embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder_ir__trunc128__texto_preprocessado,16.888889,0.927961,15.0,18.0
embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto_preprocessado,17.000000,1.732051,13.0,18.0

In [152]:
from scipy.stats import spearmanr
import pandas as pd

metrics = ["precision@1", "r_precision", "map"]

results = []

for materia in df_abertos["materia"].unique():
    sub = df_abertos[df_abertos["materia"] == materia]
    
    for metric in metrics:
        rho, p = spearmanr(sub["size"], sub[metric])
        
        results.append({
            "materia": materia,
            "metric": metric,
            "spearman_rho": rho,
            "p_value": p
        })

df_corr = pd.DataFrame(results)
df_corr

        materia       metric  spearman_rho   p_value
0    PEC_6_2019  precision@1      0.769647  0.001286
1    PEC_6_2019  r_precision      0.822869  0.000301
2    PEC_6_2019          map      0.822869  0.000301
3  MPV_612_2013  precision@1      0.764483  0.001451
4  MPV_612_2013  r_precision      0.878033  0.000036
5  MPV_612_2013          map      0.887227  0.000023
6   PLP_68_2024  precision@1      0.790130  0.000772
7   PLP_68_2024  r_precision      0.832063  0.000223
8   PLP_68_2024          map      0.845854  0.000138

In [162]:
(embeddings["texto_preprocessado"]
.str.split()
.str.len()
.groupby(embeddings["materia"])
.agg(["mean", "std"]))

                    mean         std
materia
MPV_612_2013  345.781818  381.845229
PEC_6_2019    499.541045  467.714975
PLP_68_2024   619.674265  547.459315

In [147]:
from scipy.stats import spearmanr

metrics = ["precision@1", "r_precision", "map"]

for m in metrics:
    rho, p = spearmanr(df_abertos["size"], df_abertos[m])
    print(f"\nMetric: {m}")
    print(f"Spearman rho = {rho:.3f}")
    print(f"p-value = {p:.4f}")

Metric: precision@1
Spearman rho = 0.758
p-value = 0.0000

Metric: r_precision
Spearman rho = 0.821
p-value = 0.0000

Metric: map
Spearman rho = 0.805
p-value = 0.0000

In [114]:
import gc
import scipy.stats as stats
import pandas as pd
import numpy as np

# =====================================================================
# 1. CONSOLIDAÇÃO DAS ESTATÍSTICAS DESCRITIVAS (MÉDIA E DESVIO PADRÃO)
# =====================================================================
print("--- Calculando Média e Desvio Padrão por Tratamento ---")

print("\n" + "="*70)
print("INICIANDO ANÁLISE ESTATÍSTICA COMPLETA")
print("="*70)

# =====================================================================
# 2. CONSOLIDAÇÃO DAS ESTATÍSTICAS DESCRITIVAS (MÉDIA E DESVIO PADRÃO)
# =====================================================================
print("\n--- 1. Calculando Média e Desvio Padrão por Tratamento ---")

df_estatisticas = (
    df_all[df_all["nivel"] == "tema"]
    .groupby(["materia", "tipo_texto"])[metricas]
    .agg(["mean", "std"])
)

# Simplifica o multi-index das colunas para 'metrica_mean' e 'metrica_std'
df_estatisticas.columns = [f"{metric}_{stat}" for metric, stat in df_estatisticas.columns]
display(df_estatisticas)


# =====================================================================
# 3. TESTES DE SIGNIFICÂNCIA ESTATÍSTICA (MELHORA EM RELAÇÃO AO BRUTO)
# =====================================================================
print("\n--- 2. Executando Testes de Wilcoxon (Melhora vs. Bruto) ---")

# Filtra apenas o nível 'tema'
df_filtrado = df_all[df_all["nivel"] == "tema"].copy()
lista_materias = df_filtrado["materia"].unique()
registros_testes = []

for materia in lista_materias:
    df_mat = df_filtrado[df_filtrado["materia"] == materia]
    
    # Isola o baseline fixo: Texto Bruto
    df_bruto = df_mat[df_mat["tipo_texto"] == "texto"]
    
    if df_bruto.empty:
        print(f"[Aviso] Matéria {materia} não possui dados para o tipo 'texto' (Bruto).")
        continue
        
    for metric in metricas:
        # Vetor de pontuações do Baseline Bruto (tamanho 10, um para cada modelo)
        scores_bruto = df_bruto.sort_values("embedding")[metric].values
        
        # -----------------------------------------------------------------
        # Teste 1: Pré-processado COMPLETO (Alt. + Just.) SUPEROU o Bruto?
        # -----------------------------------------------------------------
        df_alt_just = df_mat[df_mat["tipo_texto"] == "texto_preprocessado"]
        if not df_alt_just.empty:
            scores_alt_just = df_alt_just.sort_values("embedding")[metric].values
            
            if len(scores_alt_just) == len(scores_bruto):
                # 'greater' testa se: scores_alt_just > scores_bruto
                _, p_val_alt_just = stats.wilcoxon(scores_alt_just, scores_bruto, alternative="greater")
            else:
                p_val_alt_just = np.nan
        else:
            p_val_alt_just = np.nan
            
        # -----------------------------------------------------------------
        # Teste 2: Pré-processado SEM Justificativa (Alt. Pura) SUPEROU o Bruto?
        # -----------------------------------------------------------------
        df_sem_j = df_mat[df_mat["tipo_texto"] == "texto_preprocessado_sem_justificativa"]
        if not df_sem_j.empty:
            scores_sem_j = df_sem_j.sort_values("embedding")[metric].values
            
            if len(scores_sem_j) == len(scores_bruto):
                # 'greater' testa se: scores_sem_j > scores_bruto
                _, p_val_sem_j = stats.wilcoxon(scores_sem_j, scores_bruto, alternative="greater")
            else:
                p_val_sem_j = np.nan
        else:
            p_val_sem_j = np.nan
            
        # Guarda os p-values calculados para esta métrica nesta matéria
        registros_testes.append({
            "materia": materia,
            "metrica": metric,
            "p_val_Alt_Just_vs_Bruto": p_val_alt_just,
            "p_val_Alt_SemJust_vs_Bruto": p_val_sem_j
        })

# Consolida os resultados em DataFrame
df_p_values = pd.DataFrame(registros_testes)

# Define o nível de significância rigoroso do seu paper (Alpha = 0.05)
ALPHA_CORTE = 0.05

# Cria as colunas de veredito se houve ganho ou não em relação ao bruto
df_p_values["Melhorou_Alt_Just?"] = df_p_values["p_val_Alt_Just_vs_Bruto"].apply(
    lambda p: "SIM (*)" if p < ALPHA_CORTE else "Não"
)
df_p_values["Melhorou_Alt_SemJust?"] = df_p_values["p_val_Alt_SemJust_vs_Bruto"].apply(
    lambda p: "SIM (*)" if p < ALPHA_CORTE else "Não"
)

# Reorganiza as colunas para melhor leitura na tela
colunas_ordenadas = [
    "materia", "metrica", 
    "p_val_Alt_Just_vs_Bruto", "Melhorou_Alt_Just?",
    "p_val_Alt_SemJust_vs_Bruto", "Melhorou_Alt_SemJust?"
]
df_p_values = df_p_values[colunas_ordenadas]

print("\n>>> TABELA DE VEREDITO FINAL (Confiança de 95%) <<<")
display(df_p_values)

# Limpeza de memória final
del df_filtrado, registros_testes
gc.collect()

--- Calculando Média e Desvio Padrão por Tratamento ---

======================================================================
INICIANDO ANÁLISE ESTATÍSTICA COMPLETA
======================================================================

--- 1. Calculando Média e Desvio Padrão por Tratamento ---

                                                    precision@1_mean  \
materia      tipo_texto
MPV_612_2013 texto                                          0.682185
             texto_preprocessado                            0.741775
             texto_preprocessado_sem_justificativa          0.698324
PEC_6_2019   texto                                          0.688552
             texto_preprocessado                            0.768308
             texto_preprocessado_sem_justificativa          0.690657
PLP_68_2024  texto                                          0.726390
             texto_preprocessado                            0.773376
             texto_preprocessado_sem_justificativa          0.755679

                                                    precision@1_std  \
materia      tipo_texto
MPV_612_2013 texto                                         0.132312
             texto_preprocessado                           0.043719
             texto_preprocessado_sem_justificativa         0.068663
PEC_6_2019   texto                                         0.117446
             texto_preprocessado                           0.066746
             texto_preprocessado_sem_justificativa         0.067884
PLP_68_2024  texto                                         0.096281
             texto_preprocessado                           0.049412
             texto_preprocessado_sem_justificativa         0.055048

                                                    r_precision_mean  \
materia      tipo_texto
MPV_612_2013 texto                                          0.468168
             texto_preprocessado                            0.525195
             texto_preprocessado_sem_justificativa          0.445092
PEC_6_2019   texto                                          0.445058
             texto_preprocessado                            0.511322
             texto_preprocessado_sem_justificativa          0.367378
PLP_68_2024  texto                                          0.437057
             texto_preprocessado                            0.473127
             texto_preprocessado_sem_justificativa          0.418109

                                                    r_precision_std  map_mean  \
materia      tipo_texto
MPV_612_2013 texto                                         0.105806  0.499759
             texto_preprocessado                           0.069147  0.561047
             texto_preprocessado_sem_justificativa         0.049062  0.481841
PEC_6_2019   texto                                         0.136084  0.482643
             texto_preprocessado                           0.110038  0.553202
             texto_preprocessado_sem_justificativa         0.072038  0.397677
PLP_68_2024  texto                                         0.104323  0.456013
             texto_preprocessado                           0.086558  0.494370
             texto_preprocessado_sem_justificativa         0.083541  0.431105

                                                     map_std
materia      tipo_texto
MPV_612_2013 texto                                  0.114735
             texto_preprocessado                    0.077517
             texto_preprocessado_sem_justificativa  0.054412
PEC_6_2019   texto                                  0.141545
             texto_preprocessado                    0.114494
             texto_preprocessado_sem_justificativa  0.074130
PLP_68_2024  texto                                  0.117151
             texto_preprocessado                    0.098259
             texto_preprocessado_sem_justificativa  0.090968

--- 2. Executando Testes de Wilcoxon (Melhora vs. Bruto) ---

>>> TABELA DE VEREDITO FINAL (Confiança de 95%) <<<

,materia,metrica,p_val_Alt_Just_vs_Bruto,Melhorou_Alt_Just?,p_val_Alt_SemJust_vs_Bruto,Melhorou_Alt_SemJust?
0,PEC_6_2019,precision@1,0.000265,SIM (*),0.534733,Não
1,PEC_6_2019,r_precision,0.000027,SIM (*),0.994797,Não
2,PEC_6_2019,map,0.000011,SIM (*),0.994797,Não
3,MPV_612_2013,precision@1,0.003396,SIM (*),0.802180,Não
4,MPV_612_2013,r_precision,0.000072,SIM (*),0.916325,Não
5,MPV_612_2013,map,0.000019,SIM (*),0.901806,Não
6,PLP_68_2024,precision@1,0.000163,SIM (*),0.142961,Não
7,PLP_68_2024,r_precision,0.000019,SIM (*),0.867737,Não
8,PLP_68_2024,map,0.000019,SIM (*),0.901806,Não

0

In [90]:
embeddings[(embeddings["materia"] == "PLP_68_2024")].tema.value_counts()

tema
IBS e CBS (Sujeição Passiva)                                                       85
IBS e CBS (Não Cumulatividade)                                                     72
Imposto Seletivo (Incidência)                                                      64
Regime Específico - Serviços Financeiros                                           46
IBS e CBS (Administração)                                                          45
                                                                                   ..
Imposto Seletivo (Base de Cálculo) - cigarros                                       1
IBS e CBS (Fato Gerador) - Bens de uso e consumo pessoal (Cooperativa de Saúde)     1
Redução de 60% - insumos agropecuários (alimentos para animais domésticos)          1
IBS e CBS (Fato Gerador) - Não incidência fundos investimento                       1
Regime Específico - Bens Imóveis (Crédito)                                          1
Name: count, Length: 261, dtype: int64

In [79]:
df_all[
    (df_all["tipo_texto"] == "texto_preprocessado") &
    (df_all["materia"] == "PLP_68_2024")
].groupby("nivel")[["precision@1", "r_precision", "map"]].mean()

              precision@1  r_precision       map
nivel
tema             0.774182     0.472649  0.494394
tema_macro       0.901510     0.353293  0.369324
tema_nivel_2     0.866058     0.412585  0.428026

In [120]:
import gc
import scipy.stats as stats
import pandas as pd
import numpy as np

# ============================================================
# 0. FILTRO BASE (APENAS PLP 68)
# ============================================================
df_filtrado = df_all[
    (df_all["tipo_texto"] == "texto_preprocessado") &
    (df_all["materia"] == "PLP_68_2024")
].copy()

metricas = ["precision@1", "r_precision", "map"]

# ============================================================
# 1. ESTATÍSTICAS DESCRITIVAS
# ============================================================
df_estatisticas = (
    df_filtrado
    .groupby("nivel")[metricas]
    .agg(["mean", "std"])
)

df_estatisticas.columns = [
    f"{metrica}_{estat}"
    for metrica, estat in df_estatisticas.columns
]

display(df_estatisticas)

# ============================================================
# 2. TESTE HIERÁRQUICO:
#    tema_nivel_2 > tema
#    tema_macro > tema
# ============================================================

nivel_ref = "tema"
niveles_teste = ["tema_nivel_2", "tema_macro"]

df_ref = df_filtrado[df_filtrado["nivel"] == nivel_ref]

resultados = []

for nivel in niveles_teste:

    df_comp = df_filtrado[df_filtrado["nivel"] == nivel]

    if df_comp.empty or df_ref.empty:
        continue

    for metrica in metricas:

        # ============================================================
        # 🔥 ALINHAMENTO POR EMBEDDING (CRÍTICO)
        # ============================================================
        df_join = df_ref[["embedding", metrica]].rename(columns={metrica: "tema"}).merge(
            df_comp[["embedding", metrica]].rename(columns={metrica: "comp"}),
            on="embedding",
            how="inner"
        )

        if len(df_join) < 3:
            p = np.nan
            sig = "n.s."
        else:
            # ========================================================
            # H1: nível > tema (teste DIRECIONAL correto)
            # ========================================================
            _, p = stats.wilcoxon(
                df_join["comp"],
                df_join["tema"],
                alternative="greater"
            )

            sig = "SIM (*)" if p < 0.05 else "Não"

        resultados.append({
            "materia": "PLP_68_2024",
            "comparacao": f"{nivel} vs tema",
            "metrica": metrica,
            "p_value": p,
            "melhora_hierarquica?": sig
        })

df_p_values = pd.DataFrame(resultados)

display(df_p_values)

gc.collect()

,precision@1_mean,precision@1_std,r_precision_mean,r_precision_std,map_mean,map_std
nivel,,,,,,
tema,0.773376,0.049412,0.473127,0.086558,0.494370,0.098259
tema_macro,0.901605,0.027891,0.355508,0.049206,0.371190,0.056138
tema_nivel_2,0.865829,0.038926,0.412807,0.079692,0.427868,0.091952

,materia,comparacao,metrica,p_value,melhora_hierarquica?
0,PLP_68_2024,tema_nivel_2 vs tema,precision@1,0.000004,SIM (*)
1,PLP_68_2024,tema_nivel_2 vs tema,r_precision,1.000000,Não
2,PLP_68_2024,tema_nivel_2 vs tema,map,1.000000,Não
3,PLP_68_2024,tema_macro vs tema,precision@1,0.000098,SIM (*)
4,PLP_68_2024,tema_macro vs tema,r_precision,1.000000,Não
5,PLP_68_2024,tema_macro vs tema,map,1.000000,Não

0

In [37]:
df_all.materia.unique()

array(['PEC_6_2019', 'MPV_612_2013', 'PLP_68_2024'], dtype=object)

In [125]:
(df_all[(df_all.tipo_texto == "texto_preprocessado") & (df_all.nivel=="tema")].sort_values(["materia", "precision@1"], ascending=[True, False])
      .groupby("materia")
      .head(3))

,nivel,embedding,precision@1,r_precision,map,materia,tipo_texto
58,tema,embedding__joaorobson__KaLM_Embedding_Gemma3_1...,0.810056,0.599140,0.648100,MPV_612_2013,texto_preprocessado
55,tema,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.787709,0.614590,0.663167,MPV_612_2013,texto_preprocessado
64,tema,retrieval__bm25l__texto_preprocessado__preprocess,0.782123,0.560455,0.596075,MPV_612_2013,texto_preprocessado
1,tema,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.867424,0.658753,0.713185,PEC_6_2019,texto_preprocessado
2,tema,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.856061,0.653239,0.699050,PEC_6_2019,texto_preprocessado
7,tema,embedding__jinaai__jina_embeddings_v5_text_sma...,0.856061,0.590560,0.642256,PEC_6_2019,texto_preprocessado
112,tema,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.824089,0.565604,0.598048,PLP_68_2024,texto_preprocessado
108,tema,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.817750,0.570928,0.606218,PLP_68_2024,texto_preprocessado
115,tema,embedding__ICT_TIME_and_Querit__ICT_TIME_and_Q...,0.817750,0.534817,0.561174,PLP_68_2024,texto_preprocessado

In [133]:
df_all[(df_all.tipo_texto == "texto_preprocessado") & (df_all.nivel=="tema") & (
    (df_all.embedding.str.contains("PORTULAN")) | (df_all.embedding.str.contains("jose")))].describe()

       precision@1  r_precision        map
count    18.000000    18.000000  18.000000
mean      0.702279     0.404366   0.429306
std       0.030937     0.054100   0.060244
min       0.653631     0.300759   0.310988
25%       0.688547     0.356848   0.384140
50%       0.693659     0.427992   0.452423
75%       0.718533     0.441580   0.476840
max       0.767036     0.460886   0.497605

In [134]:
df_all[(df_all.tipo_texto == "texto_preprocessado") & (df_all.nivel=="tema") & (
    (~df_all.embedding.str.contains("PORTULAN")) & (~df_all.embedding.str.contains("jose")))].describe()

       precision@1  r_precision        map
count    36.000000    36.000000  36.000000
mean      0.790590     0.552639   0.589656
std       0.037890     0.060259   0.069014
min       0.720670     0.402040   0.415376
25%       0.765363     0.519220   0.548060
50%       0.792657     0.563030   0.597061
75%       0.812599     0.584620   0.629960
max       0.867424     0.658753   0.713185

In [127]:
(df_all[(df_all.tipo_texto == "texto_preprocessado") & (df_all.nivel=="tema")].sort_values(["materia", "r_precision"], ascending=[True, False])
      .groupby("materia")
      .head(3))

,nivel,embedding,precision@1,r_precision,map,materia,tipo_texto
54,tema,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.765363,0.624949,0.670250,MPV_612_2013,texto_preprocessado
55,tema,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.787709,0.614590,0.663167,MPV_612_2013,texto_preprocessado
59,tema,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.765363,0.600504,0.643553,MPV_612_2013,texto_preprocessado
1,tema,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.867424,0.658753,0.713185,PEC_6_2019,texto_preprocessado
2,tema,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.856061,0.653239,0.699050,PEC_6_2019,texto_preprocessado
3,tema,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.852273,0.645340,0.694852,PEC_6_2019,texto_preprocessado
108,tema,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.817750,0.570928,0.606218,PLP_68_2024,texto_preprocessado
110,tema,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.811410,0.568953,0.604211,PLP_68_2024,texto_preprocessado
112,tema,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.824089,0.565604,0.598048,PLP_68_2024,texto_preprocessado

In [126]:
(df_all[(df_all.tipo_texto == "texto_preprocessado") & (df_all.nivel=="tema")].sort_values(["materia", "map"], ascending=[True, False])
      .groupby("materia")
      .head(3))

,nivel,embedding,precision@1,r_precision,map,materia,tipo_texto
54,tema,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.765363,0.624949,0.670250,MPV_612_2013,texto_preprocessado
55,tema,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.787709,0.614590,0.663167,MPV_612_2013,texto_preprocessado
58,tema,embedding__joaorobson__KaLM_Embedding_Gemma3_1...,0.810056,0.599140,0.648100,MPV_612_2013,texto_preprocessado
1,tema,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.867424,0.658753,0.713185,PEC_6_2019,texto_preprocessado
2,tema,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.856061,0.653239,0.699050,PEC_6_2019,texto_preprocessado
3,tema,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.852273,0.645340,0.694852,PEC_6_2019,texto_preprocessado
108,tema,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.817750,0.570928,0.606218,PLP_68_2024,texto_preprocessado
110,tema,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.811410,0.568953,0.604211,PLP_68_2024,texto_preprocessado
112,tema,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.824089,0.565604,0.598048,PLP_68_2024,texto_preprocessado

In [63]:
import re

def map_latex_names(df, column="embedding"):
    """
    Mapeia nomes longos de embeddings/retrieval para nomes curtos de tabela LaTeX.
    
    Parameters
    ----------
    df : pd.DataFrame
        DataFrame com coluna de embeddings/retrieval
    column : str
        Nome da coluna que contém os identificadores longos
    
    Returns
    -------
    pd.Series
        Série com nomes mapeados para LaTeX
    """

    mapping_rules = [
        (r".*bm25l.*raw.*", "BM25L"),
        (r".*bm25l.*preprocess.*", "BM25L (prep)"),
        
        (r".*Octen.*", "OCTEN"),
        (r".*ICT_TIME_and_Querit.*", "ICTT"),
        (r".*F2LLM.*", "F2LLM"),
        (r".*harrier.*", "HARRIER"),
        (r".*KaLM.*", "KALM"),
        (r".*nemo.*", "NEMO"),
        (r".*Qwen3.*", "QWEN3"),
        (r".*gemini_embedding_2.*", "GOOGLE"),
        (r".*text_embedding_3_large.*", "OPENAI"),
        (r".*jina_embeddings_v5.*clustering.*", "JINA (clust)"),
        (r".*jina_embeddings_v5.*text_matching.*", "JINA (text-m)"),
        (r".*bertimbau.*meanpool.*", "BERT (mp)"),
        (r".*bertimbau.*trunc.*", "BERT (trunc)"),
        (r".*serafim_335m_portuguese_pt_sentence_encoder__.*meanpool.*", "SRFB (mp)"),
        (r".*serafim_335m_portuguese_pt_sentence_encoder__.*trunc.*", "SRFB (trunc)"),
        (r".*serafim_335m_portuguese_pt_sentence_encoder_ir.*meanpool.*", "SRFIR (mp)"),
        (r".*serafim_335m_portuguese_pt_sentence_encoder_ir.*trunc.*", "SRFIR (trunc)"),
    ]

    def _map_name(name):
        for pattern, latex_name in mapping_rules:
            if re.match(pattern, name, re.IGNORECASE):
                return latex_name
        return name  # fallback

    return df[column].apply(_map_name)

In [62]:
df_all.embedding.values[-3]

'embedding__PORTULAN__serafim_335m_portuguese_pt_sentence_encoder__trunc128__texto'

In [64]:
df_all["nome_latex"] =  map_latex_names(df_all)

In [65]:
with pd.option_context('display.max_columns', None,
                       'display.max_colwidth', None,
                       'display.max_rows', None):

    display(
        df_all[
            (df_all.tipo_texto == "texto_preprocessado") &
            (df_all.nivel == "tema") &
            (df_all.materia == "PLP_68_2024")
        ]
        .sort_values(by="map", ascending=False)
        .reset_index(drop=True)
        [["nivel", "nome_latex", "precision@1", "r_precision", "map"]]
        .sort_values("nome_latex")
        .round(3)
    )

   nivel     nome_latex  precision@1  r_precision    map
15  tema      BERT (mp)        0.710        0.386  0.406
16  tema   BERT (trunc)        0.703        0.347  0.358
9   tema          BM25L        0.792        0.505  0.531
5   tema   BM25L (prep)        0.793        0.529  0.559
2   tema          F2LLM        0.824        0.566  0.598
14  tema         GOOGLE        0.741        0.413  0.415
1   tema        HARRIER        0.811        0.569  0.604
4   tema           ICTT        0.818        0.535  0.561
10  tema   JINA (clust)        0.789        0.464  0.495
7   tema  JINA (text-m)        0.809        0.529  0.556
11  tema           KALM        0.788        0.461  0.477
6   tema           NEMO        0.809        0.528  0.557
0   tema          OCTEN        0.818        0.571  0.606
8   tema         OPENAI        0.803        0.520  0.549
3   tema          QWEN3        0.816        0.554  0.588
13  tema      SRFB (mp)        0.755        0.423  0.439
18  tema   SRFB (trunc)        0.670        0.311  0.311
12  tema     SRFIR (mp)        0.767        0.437  0.456
17  tema  SRFIR (trunc)        0.694        0.332  0.326

In [168]:
(
    df_all[
        (df_all.materia == "PLP_68_2024") &
        (df_all.tipo_texto == "texto_preprocessado")
    ]
    .groupby("nivel", group_keys=False)
    .apply(lambda x: x.sort_values("map", ascending=False).head(5))
)

C:\Users\3675-Robson\AppData\Local\Temp\ipykernel_17684\467523099.py:7: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sort_values("map", ascending=False).head(5))

,nivel,embedding,precision@1,precision@5,precision@10,r_precision,map,materia,tipo_texto
102,tema,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.816693,0.713154,0.594929,0.569827,0.606205,PLP_68_2024,texto_preprocessado
104,tema,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.811410,0.702483,0.588325,0.567297,0.604219,PLP_68_2024,texto_preprocessado
106,tema,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.823560,0.715161,0.595404,0.565193,0.598040,PLP_68_2024,texto_preprocessado
108,tema,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.816693,0.705864,0.581035,0.555434,0.587803,PLP_68_2024,texto_preprocessado
109,tema,embedding__nvidia__llama_embed_nemotron_8b__te...,0.808769,0.687163,0.559535,0.527765,0.557408,PLP_68_2024,texto_preprocessado
152,tema_macro,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.918108,0.857375,0.795473,0.432594,0.456115,PLP_68_2024,texto_preprocessado
158,tema_macro,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.929298,0.866124,0.798678,0.418519,0.446019,PLP_68_2024,texto_preprocessado
161,tema_macro,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.933876,0.870600,0.801068,0.413150,0.437846,PLP_68_2024,texto_preprocessado
169,tema_macro,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.924720,0.854730,0.786928,0.398897,0.426461,PLP_68_2024,texto_preprocessado
182,tema_macro,embedding__openai__text_embedding_3_large__mea...,0.915565,0.839471,0.767447,0.384644,0.403981,PLP_68_2024,texto_preprocessado
116,tema_nivel_2,embedding__joaorobson__harrier_oss_v1_27b__tex...,0.893279,0.801437,0.715546,0.511592,0.547639,PLP_68_2024,texto_preprocessado
117,tema_nivel_2,embedding__Octen__Octen_Embedding_8B__texto_pr...,0.901488,0.809749,0.718625,0.505205,0.537704,PLP_68_2024,texto_preprocessado
120,tema_nivel_2,embedding__codefuse_ai__F2LLM_v2_14B__texto_pr...,0.906619,0.816727,0.722165,0.502640,0.533126,PLP_68_2024,texto_preprocessado
124,tema_nivel_2,embedding__Qwen__Qwen3_Embedding_8B__texto_pre...,0.897383,0.797948,0.703540,0.482712,0.515534,PLP_68_2024,texto_preprocessado
139,tema_nivel_2,embedding__openai__text_embedding_3_large__mea...,0.890200,0.783889,0.686352,0.464260,0.484986,PLP_68_2024,texto_preprocessado

In [54]:
df = resultados_df["PEC_6_2019"].copy()

df["tipo_texto"] = df["embedding"].str.extract(
    r"(texto_preprocessado_sem_justificativa|texto_preprocessado|texto)$"
)

df = df.sort_values(
    ["nivel", "tipo_texto", "map"],
    ascending=[True, True, False]
)

display(
    df.style.format({
        "precision@1": "{:.4f}",
        "precision@5": "{:.4f}",
        "precision@10": "{:.4f}",
        "ndcg@10": "{:.4f}",
        "map": "{:.4f}",
    })
)

In [46]:
embeddings.embedding__google__gemini_embedding_2__trunc8192__texto.values[0]

array([-0.01851333, -0.03862364, -0.01106149, ...,  0.00012041,
       -0.00608956,  0.00334658], shape=(3072,))

In [41]:
df = resultados_df["MPV_612_2013"].copy()

df["tipo_texto"] = df["embedding"].str.extract(
    r"(texto_preprocessado_sem_justificativa|texto_preprocessado|texto)$"
)

df = df.sort_values(["tipo_texto", "map"], ascending=[True, False])

display(
    df.style.format({
        "precision@1": "{:.4f}",
        "precision@5": "{:.4f}",
        "precision@10": "{:.4f}",
        "ndcg@10": "{:.4f}",
        "map": "{:.4f}",
    })
)

In [30]:
with pd.option_context(
    "display.max_colwidth", None,
    "display.max_rows", None,
):
    display(
        resultados_df["PLP_68_2024"]
        .sort_values("precision@1", ascending=False)
        .reset_index(drop=True)
        .style.format({
            "precision@1": "{:.4f}",
            "precision@5": "{:.4f}",
            "precision@10": "{:.4f}",
            "ndcg@10": "{:.4f}",
        })
    )

In [40]:
with pd.option_context(
    "display.max_colwidth", None,
    "display.max_rows", None,
):
    display(
        resultados_df["MPV_612_2013"]
        .sort_values("precision@1", ascending=False)
        .reset_index(drop=True)
        .style.format({
            "precision@1": "{:.4f}",
            "precision@5": "{:.4f}",
            "precision@10": "{:.4f}",
            "ndcg@10": "{:.4f}",
        })
    )

In [89]:
resultado_pec_6_df.embedding.values

array(['embedding__codefuse_ai__F2LLM_v2_14B__texto_preprocessado',
       'embedding__Octen__Octen_Embedding_8B__texto_preprocessado',
       'embedding__Octen__Octen_Embedding_8B__texto',
       'embedding__Qwen__Qwen3_Embedding_8B__texto',
       'embedding__Qwen__Qwen3_Embedding_8B__texto_preprocessado',
       'embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto_preprocessado',
       'embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto',
       'embedding__nvidia__llama_embed_nemotron_8b__texto_preprocessado',
       'embedding__codefuse_ai__F2LLM_v2_14B__texto_preprocessado_sem_justificativa',
       'embedding__tfidf__texto_preprocessado',
       'embedding__Octen__Octen_Embedding_8B__texto_preprocessado_sem_justificativa',
       'embedding__codefuse_ai__F2LLM_v2_14B__texto',
       'embedding__Qwen__Qwen3_Embedding_8B__texto_preprocessado_sem_justificativa',
       'embedding__nvidia__llama_embed_nemotron_8b__texto',
       'embedding__jinaai__jina_embeddings_v5_text_small__text_matching__texto_preprocessado_sem_justificativa',
       'embedding__tfidf__texto',
       'embedding__tfidf__texto_preprocessado_sem_justificativa',
       'embedding__jinaai__jina_embeddings_v5_text_small__clustering__texto_preprocessado',
       'embedding__nvidia__llama_embed_nemotron_8b__texto_preprocessado_sem_justificativa',
       'embedding__jinaai__jina_embeddings_v5_text_small__clustering__texto',
       'embedding__jinaai__jina_embeddings_v5_text_small__clustering__texto_preprocessado_sem_justificativa'],
      dtype=object)